import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import net from 'node:net';import {spawn} from 'node:child_process';
const root=path.resolve(import.meta.dirname,'..'),data=path.join(root,'.test-features-112-'+Date.now());fs.mkdirSync(data);fs.mkdirSync(path.join(data,'sockets'));
const port=await new Promise(resolve=>{let s=net.createServer();s.listen(0,'127.0.0.1',()=>{let p=s.address().port;s.close(()=>resolve(p));});});const secret=crypto.randomBytes(24).toString('hex');let token='';
const processBackend=spawn(path.join(root,'runtime/bin/java.exe'),['-Djdk.net.unixdomain.tmpdir='+path.join(data,'sockets'),'-jar',path.join(root,'backend/target/thuchi-'+JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8')).version+'.jar')],{windowsHide:true,env:{...process.env,VK_DATA_DIR:data,VK_PORT:String(port),VK_BRIDGE_SECRET:secret,VK_DESKTOP:'true'},stdio:['pipe','pipe','pipe']});let log='';processBackend.stdout.on('data',x=>log+=x);processBackend.stderr.on('data',x=>log+=x);
async function api(route,method='GET',body,expected=200){let r=await fetch('http://127.0.0.1:'+port+'/api'+route,{method,headers:{'X-VK-Bridge':secret,Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});let v=await r.json();assert.equal(r.status,expected,route+' '+JSON.stringify(v));return v;}
const post=(route,body,expected)=>api(route,'POST',body,expected);const del=(route,row)=>api(route,'DELETE',{version:row.version,reason:'Nhập nhầm'});const item=(table,r)=>({table,id:r.id,version:r.version});
try{
 let ready=false;for(let i=0;i<120;i++){try{await api('/health');ready=true;break;}catch{}await new Promise(r=>setTimeout(r,250));}assert(ready,log);
 await post('/auth/register',{username:'admin',name:'Kế toán thử',password:'1'});token=(await post('/auth/login',{username:'admin',password:'1'})).token;
 const employee=await post('/masters/contacts',{name:'Nhân viên thử',kind:'EMPLOYEE',job_title:'Trưởng bộ phận'});assert.equal(employee.job_title,'Trưởng bộ phận');const changed=await api('/masters/contacts/'+employee.id,'PUT',{...employee,job_title:'Kế toán trưởng'});assert.equal(changed.job_title,'Kế toán trưởng');
 const fund=await post('/masters/funds',{name:'Quỹ thử',kind:'BANK',opening:10000000,opening_date:'2026-10-01'});
 const adv=await post('/obligations',{kind:'ADVANCE',salary_month:'2026-10',date:'2026-10-08',contact_id:employee.id,amount:3000000,description:'Ứng lương tháng 10'});assert.equal(adv.salary_month,'2026-10');
 const other=await post('/masters/contacts',{name:'Đối tác thử',kind:'SUPPLIER'});await post('/obligations',{kind:'ADVANCE',date:'2026-10-08',contact_id:other.id,amount:100,description:'Không phải nhân viên'},400);
 const issue=await post('/vouchers',{type:'EXPENSE',purpose:'ADVANCE_ISSUE',date:'2026-10-08',contact_id:employee.id,obligation_id:adv.id,fund_id:fund.id,amount:3000000,description:'Chi ứng'});
 const balance=async()=>(await api('/report?from=2026-10-01&to=2026-10-31')).funds.find(f=>f.id===fund.id).balance;
 assert.equal(await balance(),7000000);await post('/obligations/'+adv.id+'/clear',{date:'2026-10-31',amount:3000000,note:'Khấu trừ bảng lương tháng 10'});assert.equal(await balance(),7000000);let o=(await api('/obligations')).find(x=>x.id===adv.id);assert.equal(o.deducted,3000000);assert.equal(o.returned,0);assert.equal(o.outstanding,0);await post('/obligations/'+adv.id+'/clear',{date:'2026-10-31',amount:1,note:'Vượt'},400);const clearing=(await api('/clearings'))[0];await del('/clearings/'+clearing.id,clearing);assert.equal((await api('/obligations')).find(x=>x.id===adv.id).outstanding,3000000);let deletedClearing=(await api('/trash')).find(x=>x.table==='clearings'&&x.id===clearing.id);await post('/trash/restore',{items:[item('clearings',deletedClearing)],reason:'Khấu trừ đúng'});assert.equal((await api('/obligations')).find(x=>x.id===adv.id).outstanding,0);assert.equal(await balance(),7000000);console.log('PASS correction/restoration of salary deduction does not change cash');
 console.log('PASS salary advances, employee-only, month, deduction without double payment');
 const expense=await post('/vouchers',{type:'EXPENSE',date:'2026-10-08',fund_id:fund.id,amount:100000,description:'Nhập nhầm'});await del('/vouchers/'+expense.id,expense);assert.equal(await balance(),7000000);let row=(await api('/trash')).find(x=>x.table==='vouchers'&&x.id===expense.id);assert(row.deleted_at);
 await post('/trash/restore',{items:[item('vouchers',row)],reason:'Khôi phục'});assert.equal(await balance(),6900000);let active=(await api('/vouchers')).find(x=>x.id===expense.id);await del('/vouchers/'+active.id,active);row=(await api('/trash')).find(x=>x.table==='vouchers'&&x.id===expense.id);
 await post('/trash/purge',{items:[item('vouchers',row)],reason:'Sai thật',confirmed:false},400);await post('/trash/purge',{items:[item('vouchers',row)],reason:'Sai thật',confirmed:true});assert.equal(await balance(),7000000);assert(!(await api('/vouchers')).some(x=>x.id===expense.id));assert((await api('/audit')).filter(x=>x.entity==='vouchers'&&x.entity_id===expense.id).every(x=>x.action==='PURGE'));console.log('PASS trash restore/purge changes balance once and retains minimal audit');
 const unused=await post('/masters/funds',{name:'Quỹ xóa',kind:'CASH',opening:0,opening_date:'2026-10-01'});const linked=await post('/vouchers',{type:'EXPENSE',date:'2026-10-08',fund_id:unused.id,amount:100,description:'Liên kết'});await del('/vouchers/'+linked.id,linked);await del('/masters/funds/'+unused.id,unused);let trash=await api('/trash');const fi=trash.find(x=>x.table==='funds'&&x.id===unused.id),vi=trash.find(x=>x.table==='vouchers'&&x.id===linked.id);await post('/trash/purge',{items:[item('funds',fi)],reason:'Chưa xóa phiếu',confirmed:true},400);await post('/trash/restore',{items:[item('vouchers',vi)],reason:'Thiếu quỹ'},400);assert((await api('/trash')).some(x=>x.table==='funds'&&x.id===unused.id));await post('/trash/purge',{items:[item('funds',fi),item('vouchers',vi)],reason:'Xóa cả nhóm',confirmed:true});console.log('PASS dependency checks, atomic rollback, batch purge in dependency order');
 const source=crypto.randomUUID(),file=path.join(data,'finance-sync.json');let doc={id:'1',code:'NK-TEST-1',status:'POSTED',deleted:false,supplier_id:'11',supplier_code:'NCC-TEST',supplier_name:'Kho mẫu NCC',phone:'',address:'',date:'2026-10-08',note:'',priced:true,amount:1000000,items:[{code:'LK',name:'Linh kiện',unit:'cái',quantity:10,unit_cost:100000}]};const write=()=>fs.writeFileSync(file,JSON.stringify({format:'VK-WAREHOUSE-FINANCE-1',source_id:source,generated_at:new Date().toISOString(),documents:[doc,{...doc,id:'2',code:'DRAFT',status:'DRAFT'}]}));write();await post('/warehouse/connect',{path:file});let synced=await post('/warehouse/sync',{source});assert.equal(synced.created,1);assert.equal(synced.skipped,1);synced=await post('/warehouse/sync',{source});assert.equal(synced.created,0);assert.equal(synced.unchanged,1);let link=(await api('/warehouse/documents'))[0];let debt=(await api('/obligations')).find(x=>x.id===link.obligation_id);assert.equal(debt.outstanding,1000000);await post('/vouchers',{type:'EXPENSE',date:'2026-10-08',fund_id:fund.id,contact_id:debt.contact_id,obligation_id:debt.id,amount:300000,description:'Trả một phần'});assert.equal((await api('/obligations')).find(x=>x.id===debt.id).outstanding,700000);
 doc={...doc,amount:2000000};write();assert.equal((await post('/warehouse/sync',{source})).issues,1);assert.equal((await api('/obligations')).find(x=>x.id===debt.id).amount,1000000);doc={...doc,deleted:true};write();await post('/warehouse/sync',{source});assert.equal((await api('/warehouse/documents'))[0].state,'CANCELLED');console.log('PASS warehouse connection, confirmed-only, duplicate protection, partial payment, edit/cancel reconciliation');
 const disposable={...doc,id:'3',code:'NK-WRONG',status:'POSTED',deleted:false};fs.writeFileSync(file,JSON.stringify({format:'VK-WAREHOUSE-FINANCE-1',source_id:source,generated_at:new Date().toISOString(),documents:[doc,disposable]}));await post('/warehouse/sync',{source});const wrongLink=(await api('/warehouse/documents')).find(x=>x.document_id==='3');const wrongDebt=(await api('/obligations')).find(x=>x.id===wrongLink.obligation_id);await del('/obligations/'+wrongDebt.id,wrongDebt);const wrongTrash=(await api('/trash')).find(x=>x.table==='obligations'&&x.id===wrongDebt.id);await post('/trash/purge',{items:[item('obligations',wrongTrash)],reason:'Nhập nhầm từ kho',confirmed:true});assert.equal((await api('/warehouse/documents')).find(x=>x.document_id==='3').snapshot_json,'{}');assert.equal((await post('/warehouse/sync',{source})).created,0);console.log('PASS purge removes warehouse snapshot content and retains only duplicate-prevention marker');
 const user=await post('/auth/register',{username:'viewer',name:'Chỉ xem',password:'1',role:'VIEWER'});token=(await post('/auth/login',{username:'viewer',password:'1'})).token;await post('/trash/purge',{items:[],confirmed:true,reason:'Không cho'},403);await post('/warehouse/sync',{source},403);await api('/warehouse/documents');console.log('PASS viewer cannot purge or sync; warehouse details readable');
 console.log('All 1.1.2 feature checks passed');
}catch(e){console.error(e);console.error(log.slice(-4000));process.exitCode=1;}finally{processBackend.stdin.end();await new Promise(resolve=>{let t=setTimeout(()=>{processBackend.kill();resolve();},8000);processBackend.once('exit',()=>{clearTimeout(t);resolve();});});}
