import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import net from 'node:net';import {spawn} from 'node:child_process';
const root=path.resolve(import.meta.dirname,'..'),data=path.join(root,'.test-features-112-'+Date.now());fs.mkdirSync(data);fs.mkdirSync(path.join(data,'sockets'));
const port=await new Promise(resolve=>{let s=net.createServer();s.listen(0,'127.0.0.1',()=>{let p=s.address().port;s.close(()=>resolve(p));});});const secret=crypto.randomBytes(24).toString('hex');let token='';
const processBackend=spawn(path.join(root,'runtime/bin/java.exe'),['-Djdk.net.unixdomain.tmpdir='+path.join(data,'sockets'),'-jar',path.join(root,'backend/target/thuchi-'+JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8')).version+'.jar')],{windowsHide:true,env:{...process.env,VK_DATA_DIR:data,VK_PORT:String(port),VK_BRIDGE_SECRET:secret,VK_DESKTOP:'true'},stdio:['pipe','pipe','pipe']});let log='';processBackend.stdout.on('data',x=>log+=x);processBackend.stderr.on('data',x=>log+=x);
async function api(route,method='GET',body,expected=200){let r=await fetch('http://127.0.0.1:'+port+'/api'+route,{method,headers:{'X-VK-Bridge':secret,Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});let v=await r.json();assert.equal(r.status,expected,route+' '+JSON.stringify(v));return v;}
const post=(route,body,expected)=>api(route,'POST',body,expected);const del=(route,row)=>api(route,'DELETE',{version:row.version,reason:'Nhập nhầm'});const item=(table,r)=>({table,id:r.id,version:r.version});
try{
 let ready=false;for(let i=0;i<120;i++){try{await api('/health');ready=true;break;}catch{}await new Promise(r=>setTimeout(r,250));}assert(ready,log);
 await post('/auth/register',{username:'admin',name:'Kế toán thử',password:'1'});token=(await post('/auth/login',{username:'admin',password:'1'})).token;
 const fund=await post('/masters/funds',{name:'Tài khoản công ty',kind:'BANK',opening:20000000,opening_date:'2026-10-01'});
 const source=crypto.randomUUID(),file=path.join(data,'finance-sync.json');let docs=[10000000,2000000].map((amount,i)=>({id:String(i+1),code:'NK-'+(i+1),operation:'IN',status:'POSTED',deleted:false,supplier_id:'1',supplier_name:'NCC linh kiện',supplier_code:'NCC1',phone:'',address:'',date:'2026-10-08',note:'',priced:true,amount,items:[]}));
 const write=()=>fs.writeFileSync(file,JSON.stringify({format:'VK-WAREHOUSE-FINANCE-1',source_id:source,generated_at:new Date().toISOString(),documents:docs}));write();await post('/warehouse/connect',{path:file});assert.equal((await post('/warehouse/sync',{source})).created,2);
 const vendor=(await api('/supplier-ledger'))[0],id=vendor.id;const debt=async()=>(await api('/supplier-ledger/'+id)).balance;const cash=async()=>(await api('/report?from=2026-10-01&to=2026-10-31')).funds[0].balance;
 assert.equal(await debt(),12000000);const pay=await post('/vouchers',{type:'EXPENSE',purpose:'SUPPLIER_PAYMENT',contact_id:id,fund_id:fund.id,date:'2026-10-08',amount:200000,description:'Trả tổng nợ'});assert.equal(pay.obligation_id,null);assert.equal(await debt(),11800000);assert.equal(await cash(),19800000);
 docs.push({...docs[0],id:'3',code:'TH-1',operation:'RETURN',amount:500000});write();assert.equal((await post('/warehouse/sync',{source})).created,1);assert.equal(await debt(),11300000);assert.equal(await cash(),19800000);assert.equal((await post('/warehouse/sync',{source})).created,0);let ledger=await api('/supplier-ledger/'+id);assert.deepEqual(ledger.events.map(e=>e.balance),[10000000,12000000,11800000,11300000]);let report=await api('/report?from=2026-10-01&to=2026-10-31');assert.equal(report.obligations.find(x=>x.debt_group==='SUPPLIER').outstanding,11300000);console.log('PASS 10m + 2m - payment 200k - return 500k = 11.3m; no cash from return, no per-lot allocation, dashboard matches');
 docs[0].amount=9000000;write();assert.equal((await post('/warehouse/sync',{source})).issues,1);assert.equal(await debt(),11300000);let link=(await api('/warehouse/documents')).find(x=>x.document_id==='1');await post('/warehouse/reconcile',{source,document:'1',confirmed:true,pending_json:'invalid'},409);await post('/warehouse/reconcile',{source,document:'1',confirmed:true,pending_json:link.pending_json});assert.equal(await debt(),10300000);assert.equal(await cash(),19800000);console.log('PASS paid supplier edits require reconciliation and preserve actual payments; stale confirmation rejected');
 const credit=await post('/supplier-adjustments',{contact_id:id,date:'2026-10-08',amount:10500000,description:'Trả thêm hàng được NCC xác nhận'});assert.equal(await debt(),-200000);await post('/vouchers',{type:'RECEIPT',purpose:'SUPPLIER_REFUND',contact_id:id,fund_id:fund.id,date:'2026-10-08',amount:200001,description:'Hoàn vượt'},400);const refund=await post('/vouchers',{type:'RECEIPT',purpose:'SUPPLIER_REFUND',contact_id:id,fund_id:fund.id,date:'2026-10-08',amount:200000,description:'NCC hoàn tiền thật'});assert.equal(await debt(),0);assert.equal(await cash(),20000000);await post('/vouchers',{...pay,amount:1},400);console.log('PASS supplier credit and real refund separated; payment/refund over balance rejected');
 await del('/supplier-adjustments/'+credit.id,credit);assert.equal(await debt(),10500000);assert.equal(await cash(),20000000);let trash=(await api('/trash')).find(x=>x.table==='supplier_adjustments'&&x.id===credit.id);await post('/trash/restore',{items:[item('supplier_adjustments',trash)],reason:'Khôi phục phiếu đúng'});assert.equal(await debt(),0);assert.equal(await cash(),20000000);let active=(await api('/supplier-adjustments')).find(x=>x.id===credit.id);await del('/supplier-adjustments/'+active.id,active);trash=(await api('/trash')).find(x=>x.table==='supplier_adjustments'&&x.id===credit.id);await post('/trash/purge',{items:[item('supplier_adjustments',trash)],reason:'Nhập nhầm',confirmed:true});assert.equal(await debt(),10500000);console.log('PASS return soft-delete/restore/purge updates debt once and never changes cash');
 await del('/vouchers/'+pay.id,pay);assert.equal(await debt(),10700000);assert.equal(await cash(),20200000);trash=(await api('/trash')).find(x=>x.table==='vouchers'&&x.id===pay.id);await post('/trash/restore',{items:[item('vouchers',trash)],reason:'Đúng thanh toán'});assert.equal(await debt(),10500000);assert.equal(await cash(),20000000);
 const vendor2=await post('/masters/contacts',{name:'NCC chưa thanh toán',kind:'SUPPLIER'});docs.push({...docs[0],id:'4',code:'NK-4',supplier_id:'2',supplier_name:vendor2.name,amount:1000000});write();await post('/warehouse/sync',{source});docs[3].amount=1500000;write();assert.equal((await post('/warehouse/sync',{source})).updated,1);assert.equal((await api('/supplier-ledger/'+vendor2.id)).balance,1500000);assert.equal(await cash(),20000000);
 docs[1].deleted=true;write();await post('/warehouse/sync',{source});link=(await api('/warehouse/documents')).find(x=>x.document_id==='2');await post('/warehouse/reconcile',{source,document:'2',confirmed:true,pending_json:link.pending_json});assert.equal(await debt(),8500000);assert.equal(await cash(),20000000);await post('/warehouse/sync',{source});assert.equal((await api('/warehouse/documents')).find(x=>x.document_id==='2').state,'CANCELLED_CONFIRMED');console.log('PASS unpaid import auto-update, canceled import confirmed once, cash preserved');
 const legacy=(await api('/obligations')).find(x=>x.contact_id===id&&x.amount===9000000);await post('/vouchers',{type:'EXPENSE',contact_id:id,obligation_id:legacy.id,fund_id:fund.id,date:'2026-10-08',amount:100000,description:'Thanh toán liên kết cũ'});assert.equal(await debt(),8400000);assert.equal((await api('/supplier-ledger/'+id)).events.at(-1).balance,8400000);console.log('PASS legacy per-lot payment coexists with aggregate payments without double counting');
 await post('/auth/register',{username:'viewer',name:'Chỉ xem',password:'1',role:'VIEWER'});token=(await post('/auth/login',{username:'viewer',password:'1'})).token;await post('/supplier-adjustments',{contact_id:id,date:'2026-10-08',amount:1,description:'Không cho'},403);await post('/warehouse/reconcile',{source,document:'1',confirmed:true},403);await api('/supplier-ledger');console.log('PASS read-only user cannot alter credit or reconciliation');
}catch(e){console.error(e);console.error(log.slice(-4000));process.exitCode=1;}finally{processBackend.stdin.end();await new Promise(resolve=>{let t=setTimeout(()=>{processBackend.kill();resolve();},8000);processBackend.once('exit',()=>{clearTimeout(t);resolve();});});}
