import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import net from 'node:net';import {spawn} from 'node:child_process';
const root=path.resolve(import.meta.dirname,'..'),data=path.join(root,'.test-features-112-'+Date.now());fs.mkdirSync(data);fs.mkdirSync(path.join(data,'sockets'));
const port=await new Promise(resolve=>{let s=net.createServer();s.listen(0,'127.0.0.1',()=>{let p=s.address().port;s.close(()=>resolve(p));});});const secret=crypto.randomBytes(24).toString('hex');let token='';
const processBackend=spawn(path.join(root,'runtime/bin/java.exe'),['-Djdk.net.unixdomain.tmpdir='+path.join(data,'sockets'),'-jar',path.join(root,'backend/target/thuchi-'+JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8')).version+'.jar')],{windowsHide:true,env:{...process.env,VK_DATA_DIR:data,VK_PORT:String(port),VK_BRIDGE_SECRET:secret,VK_DESKTOP:'true'},stdio:['pipe','pipe','pipe']});let log='';processBackend.stdout.on('data',x=>log+=x);processBackend.stderr.on('data',x=>log+=x);
async function api(route,method='GET',body,expected=200){let r=await fetch('http://127.0.0.1:'+port+'/api'+route,{method,headers:{'X-VK-Bridge':secret,Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});let v=await r.json();assert.equal(r.status,expected,route+' '+JSON.stringify(v));return v;}
const post=(route,body,expected)=>api(route,'POST',body,expected);const del=(route,row)=>api(route,'DELETE',{version:row.version,reason:'Nhập nhầm'});const item=(table,r)=>({table,id:r.id,version:r.version});
try{
 let ready=false;for(let i=0;i<120;i++){try{await api('/health');ready=true;break;}catch{}await new Promise(r=>setTimeout(r,250));}assert(ready,log);
 await post('/auth/register',{username:'admin',name:'Kế toán thử',password:'1'});token=(await post('/auth/login',{username:'admin',password:'1'})).token;
 const fund=await post('/masters/funds',{name:'Tài khoản phụ',kind:'BANK',opening:100000,opening_date:'2026-10-01'}),rich=await post('/masters/funds',{name:'Tài khoản công ty',kind:'BANK',opening:10000000,opening_date:'2026-10-01'}),vendor=await post('/masters/contacts',{name:'Mingzhen',kind:'SUPPLIER'}),employee=await post('/masters/contacts',{name:'Nhân viên',kind:'EMPLOYEE'});
 await post('/obligations',{kind:'PAYABLE',contact_id:employee.id,date:'2026-10-08',amount:100000,description:'Nhầm'},400);
 await post('/obligations',{kind:'PAYABLE',contact_id:vendor.id,date:'2026-10-08',amount:1000000,description:'Nhập linh kiện'});
 const pay={type:'EXPENSE',purpose:'SUPPLIER_PAYMENT',contact_id:vendor.id,fund_id:fund.id,date:'2026-10-08',amount:100001,description:'Trả nhà cung cấp'};
 const count=async()=>(await api('/vouchers')).length;await post('/vouchers',pay,400);assert.equal(await count(),0);assert.equal((await api('/supplier-ledger/'+vendor.id)).balance,1000000);
 let p=await post('/vouchers',{...pay,amount:100000});assert.equal((await api('/report?from=2026-10-01&to=2026-10-31')).funds.find(f=>f.id===fund.id).balance,0);await post('/vouchers',{...pay,amount:1},400);await api('/vouchers/'+p.id,'PUT',{...p,amount:100001,reason:'Tăng chi'},400);assert.equal((await api('/supplier-ledger/'+vendor.id)).balance,900000);console.log('PASS insufficient selected account blocks debt payment atomically; exact balance allowed; other rich account cannot cover it; edit cannot overdraw');
 await post('/vouchers',{type:'TRANSFER',fund_id:fund.id,to_fund_id:rich.id,date:'2026-10-08',amount:1,description:'Không đủ'},400);await post('/vouchers',{type:'TRANSFER',fund_id:rich.id,to_fund_id:fund.id,date:'2026-10-08',amount:10000000,fee:1,description:'Thiếu phí'},400);console.log('PASS transfers include fee, no overdraft');
 const cash=await post('/masters/funds',{name:'Quỹ theo ngày',kind:'CASH',opening:0,opening_date:'2026-10-01'}),receipt=await post('/vouchers',{type:'RECEIPT',fund_id:cash.id,date:'2026-10-10',amount:500000,description:'Thu sau'});
 await post('/vouchers',{type:'EXPENSE',fund_id:cash.id,date:'2026-10-09',amount:1,description:'Chi trước thu'},400);const exp=await post('/vouchers',{type:'EXPENSE',fund_id:cash.id,date:'2026-10-10',amount:500000,description:'Chi đủ'});await del('/vouchers/'+receipt.id,receipt).then(()=>assert.fail('must reject')).catch(e=>{assert(e.message.includes('không đủ tiền'))});await api('/masters/funds/'+rich.id,'PUT',{...rich,opening:0},200);await del('/vouchers/'+exp.id,exp);await del('/vouchers/'+receipt.id,receipt);let trash=(await api('/trash')).find(x=>x.table==='vouchers'&&x.id===exp.id);await post('/trash/restore',{items:[item('vouchers',trash)],reason:'Thiếu tiền'},400);assert((await api('/trash')).some(x=>x.id===exp.id&&x.table==='vouchers'));console.log('PASS chronological balances, removing income and restoring expense protected with rollback');
}catch(e){console.error(e);console.error(log.slice(-4000));process.exitCode=1;}finally{processBackend.stdin.end();await new Promise(resolve=>{let t=setTimeout(()=>{processBackend.kill();resolve();},8000);processBackend.once('exit',()=>{clearTimeout(t);resolve();});});}
