import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {spawn} from 'node:child_process';import crypto from 'node:crypto';import net from 'node:net';
const root=path.resolve(import.meta.dirname,'..');const data=path.join(root,'.test-data-'+Date.now());fs.mkdirSync(data);const java=path.join(root,'runtime/bin/java.exe');const secret=crypto.randomBytes(24).toString('hex');
const port=await new Promise(r=>{let s=net.createServer();s.listen(0,'127.0.0.1',()=>{let p=s.address().port;s.close(()=>r(p));});});const base='http://127.0.0.1:'+port;
fs.mkdirSync(path.join(data,'sockets'));const child=spawn(java,['-Djdk.net.unixdomain.tmpdir='+path.join(data,'sockets'),'-jar',path.join(root,'backend/target/thuchi-1.1.0.jar')],{windowsHide:true,env:{...process.env,VK_DATA_DIR:data,VK_PORT:String(port),VK_BRIDGE_SECRET:secret,VK_DESKTOP:'true'},stdio:['pipe','pipe','pipe']});let output='';child.stdout.on('data',b=>output+=b);child.stderr.on('data',b=>output+=b);let token='',checks=[];
async function call(route,method='GET',body=null,expected=200){let r=await fetch(base+'/api'+route,{method,headers:{'X-VK-Bridge':secret,Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body===null?undefined:JSON.stringify(body)});let v=await r.json();assert.equal(r.status,expected,route+' '+JSON.stringify(v));return v;}
function check(name){checks.push(name);console.log('PASS',name);}
const password='Test-VinhKhang!2026';
try{
 let ready=false;for(let i=0;i<120;i++){try{await call('/health');ready=true;break;}catch{}if(child.exitCode!==null)break;await new Promise(r=>setTimeout(r,250));}assert(ready,output);
 assert.equal((await fetch(base+'/api/health')).status,403);assert.equal((await call('/health')).initialized,false);check('Backend chỉ nhận kết nối từ desktop bridge');
 let reg=await call('/auth/register','POST',{username:'admin',name:'Kế toán kiểm thử',password});assert(reg.recoveryCode);let login=await call('/auth/login','POST',{username:'admin',password});token=login.token;let adminToken=token;check('Tạo Admin, BCrypt và đăng nhập');
 let f1=await call('/masters/funds','POST',{name:'Ngân hàng',kind:'BANK',opening:10000000,opening_date:'2026-05-01'});let f2=await call('/masters/funds','POST',{name:'Tiền mặt',kind:'CASH',opening:2000000,opening_date:'2026-05-01'});assert(f1.id>0&&f2.id>f1.id);
 let customer=await call('/masters/contacts','POST',{name:'Đại lý A',kind:'CUSTOMER'});let supplier=await call('/masters/contacts','POST',{name:'Linh kiện B',kind:'SUPPLIER'});let employee=await call('/masters/contacts','POST',{name:'Nhân viên C',kind:'EMPLOYEE'});let category=await call('/masters/categories','POST',{name:'Chi linh kiện',kind:'OUT'});
 let receipt=await call('/vouchers','POST',{type:'RECEIPT',date:'2026-10-03',description:'Thu bán hàng',amount:500000,fund_id:f1.id});let expense=await call('/vouchers','POST',{type:'EXPENSE',date:'2026-10-03',description:'Chi linh kiện',amount:100000,fund_id:f2.id,category_id:category.id});let transfer=await call('/vouchers','POST',{type:'TRANSFER',date:'2026-10-03',description:'Rút tiền có phí',amount:1000000,fee:1100,fund_id:f1.id,to_fund_id:f2.id});
 let report=await call('/report?from=2026-10-01&to=2026-10-31');assert.equal(report.totals.income,500000);assert.equal(report.totals.expense,101100);assert.equal(report.funds.find(f=>f.id===f1.id).balance,9498900);assert.equal(report.funds.find(f=>f.id===f2.id).balance,2900000);assert.equal(report.funds.reduce((s,f)=>s+f.balance,0),12398900);check('Thu/chi, chuyển quỹ, phí và số dư đối soát');
 await call('/vouchers','POST',{type:'EXPENSE',date:'2026-10-03',description:'Âm',amount:-1,fund_id:f1.id},400);await call('/vouchers','POST',{type:'EXPENSE',date:'2026-10-03',description:'Lẻ',amount:1.2,fund_id:f1.id},400);await call('/vouchers','POST',{type:'EXPENSE',date:'2026-04-30',description:'Trước kỳ',amount:1,fund_id:f1.id},400);await call('/vouchers','POST',{type:'TRANSFER',date:'2026-10-03',description:'Cùng quỹ',amount:1,fund_id:f1.id,to_fund_id:f1.id},400);await call('/vouchers','POST',{type:'RECEIPT',date:'2026-10-03',description:'Nhóm sai',amount:1,fund_id:f1.id,category_id:category.id},400);check('Chặn số tiền âm/lẻ, ngày trước đầu kỳ, chuyển cùng quỹ, danh mục sai');
 receipt=await call('/vouchers/'+receipt.id,'PUT',{...receipt,amount:600000,reason:'Sửa số tiền'});await call('/vouchers/'+receipt.id,'PUT',{...receipt,version:1,amount:700000,reason:'Ghi đè'},409);await call('/vouchers/'+expense.id,'DELETE',{version:expense.version,reason:'Nhập nhầm'});report=await call('/report?from=2026-10-01&to=2026-10-31');assert.equal(report.totals.income,600000);assert.equal(report.totals.expense,1100);assert.equal((await call('/vouchers')).find(v=>v.id===expense.id).deleted,1);let journal=await call('/audit');assert(journal.some(a=>a.action==='UPDATE'&&a.entity==='vouchers'&&JSON.parse(a.before_json).amount===500000&&JSON.parse(a.after_json).amount===600000));assert(journal.some(a=>a.action==='VOID'));check('Sửa/hủy phiếu, chống ghi đè, giữ trước/sau và tính lại số dư');
 await call('/obligations','POST',{kind:'RECEIVABLE',contact_id:customer.id,description:'Không dùng',amount:100,date:'2026-10-01'},400);
 let ap=await call('/obligations','POST',{kind:'PAYABLE',contact_id:supplier.id,description:'Nợ mua hàng',amount:2000000,date:'2026-09-01'});await call('/vouchers','POST',{type:'EXPENSE',date:'2026-10-03',description:'Trả nợ',amount:2000000,fund_id:f1.id,contact_id:supplier.id,obligation_id:ap.id});assert.equal((await call('/obligations')).find(o=>o.id===ap.id).outstanding,0);check('Công nợ phải trả; chặn tạo công nợ khách hàng');

 customer=await call('/masters/contacts/'+customer.id,'PUT',{...customer,customer_type:'DEALER',address:'Địa chỉ mẫu'});assert.equal(customer.customer_type,'DEALER');assert.equal(customer.address,'Địa chỉ mẫu');
 let loan=await call('/obligations','POST',{kind:'PAYABLE',debt_group:'LOAN',contact_id:supplier.id,description:'Vay kiểm thử',amount:3000000,date:'2026-10-01',due_date:''});
 let loanReceive=await call('/vouchers','POST',{type:'RECEIPT',purpose:'LOAN_RECEIVE',receipt_group:'BORROWING',date:'2026-10-03',description:'Nhận tiền vay',amount:3000000,fund_id:f1.id,contact_id:supplier.id,obligation_id:loan.id});
 let interest=await call('/vouchers','POST',{type:'EXPENSE',purpose:'LOAN_INTEREST',date:'2026-10-03',description:'Trả lãi',amount:300000,fund_id:f1.id,contact_id:supplier.id,obligation_id:loan.id});
 assert.equal((await call('/obligations')).find(o=>o.id===loan.id).outstanding,3000000);
 let principal=await call('/vouchers','POST',{type:'EXPENSE',purpose:'LOAN_PRINCIPAL',date:'2026-10-03',description:'Trả gốc',amount:1000000,fund_id:f1.id,contact_id:supplier.id,obligation_id:loan.id});
 assert.equal((await call('/obligations')).find(o=>o.id===loan.id).outstanding,2000000);
 await call('/vouchers','POST',{...principal,id:undefined,amount:3000000},400);
 await call('/vouchers','POST',{...loanReceive,id:undefined,amount:1},400);
 await call('/vouchers/'+principal.id,'DELETE',{version:principal.version,reason:'Hủy thử gốc'});assert.equal((await call('/obligations')).find(o=>o.id===loan.id).outstanding,3000000);
 await call('/vouchers','POST',{...principal,amount:3000000,description:'Trả hết gốc'});assert.equal((await call('/obligations')).find(o=>o.id===loan.id).outstanding,0);await call('/vouchers','POST',{...interest,amount:15000,description:'Lãi sau tất toán'});assert.equal((await call('/obligations')).find(o=>o.id===loan.id).outstanding,0);await call('/obligations/'+loan.id,'PUT',{...loan,debt_group:'OTHER',reason:'Đổi nhóm sai'},400);await call('/obligations/'+loan.id,'PUT',{...loan,amount:2000000,reason:'Giảm gốc sai'},400);
 for(const group of ['CARRIER','OTHER'])assert.equal((await call('/obligations','POST',{kind:'PAYABLE',debt_group:group,contact_id:supplier.id,description:'Nợ '+group,amount:100,date:'2026-10-01'})).debt_group,group);
 check('Bốn nhóm công nợ, hạn tùy chọn; nhận vay, gốc/lãi riêng, chống trả vượt và hủy trả gốc');
 async function evidence(entity,id,bytes,name='bill.png',expected=200){let f=new FormData();f.append('file',new Blob([bytes]),name);f.append('caption','Bill thử nghiệm');let r=await fetch(base+'/api/evidence/'+entity+'/'+id,{method:'POST',headers:{'X-VK-Bridge':secret,Authorization:'Bearer '+token},body:f});let v=await r.json();assert.equal(r.status,expected,JSON.stringify(v));return v;}
 const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64');
 let ev=await evidence('vouchers',receipt.id,png);assert.equal((await call('/evidence/file/'+ev.id)).base64,png.toString('base64'));await evidence('vouchers',receipt.id,png,'duplicate.png',409);await evidence('vouchers',receipt.id,Buffer.from('<svg/>'),'fake.png',400);await evidence('vouchers',expense.id,png,'void.png',400);
 ev=await call('/evidence/'+ev.id,'PUT',{version:ev.version,caption:'Chú thích đã sửa',reason:'Đối chiếu'});await call('/evidence/'+ev.id,'DELETE',{version:1,reason:'Sai phiên bản'},409);await call('/evidence/'+ev.id,'DELETE',{version:ev.version,reason:'Gỡ nhưng giữ lịch sử'});assert.equal((await call('/evidence/file/'+ev.id)).base64,png.toString('base64'));
 let pdf=Buffer.from('%PDF-1.4\n% fixture only\n%%EOF');let debtEvidence=await evidence('obligations',loan.id,pdf,'contract.pdf');assert.equal(debtEvidence.mime,'application/pdf');
 check('Bằng chứng PNG/PDF: kiểm tra nội dung, chống trùng, sửa/gỡ lưu lịch sử, giữ file gốc');

 let adv=await call('/obligations','POST',{kind:'ADVANCE',contact_id:employee.id,description:'Đi công tác',amount:1000000,date:'2026-10-01'});let issue=await call('/vouchers','POST',{type:'EXPENSE',purpose:'ADVANCE_ISSUE',date:'2026-10-02',description:'Cấp ứng',amount:1000000,fund_id:f2.id,contact_id:employee.id,obligation_id:adv.id});let returnPay=await call('/vouchers','POST',{type:'RECEIPT',purpose:'ADVANCE_RETURN',date:'2026-10-03',description:'Hoàn tiền dư',amount:200000,fund_id:f2.id,contact_id:employee.id,obligation_id:adv.id});report=await call('/report?from=2026-10-01&to=2026-10-31');let before=report.funds.find(f=>f.id===f2.id).balance;await call('/obligations/'+adv.id+'/clear','POST',{date:'2026-10-03',amount:800000,note:'Hóa đơn khách sạn và xe'});assert.equal((await call('/obligations')).find(o=>o.id===adv.id).outstanding,0);assert.equal((await call('/report?from=2026-10-01&to=2026-10-31')).funds.find(f=>f.id===f2.id).balance,before);await call('/vouchers/'+issue.id,'DELETE',{version:1,reason:'Hủy sai'},400);await call('/vouchers/'+issue.id,'PUT',{...issue,amount:500000,reason:'Giảm sai'},400);await call('/vouchers/'+issue.id,'PUT',{...issue,date:'2026-10-04',reason:'Sai thứ tự'},400);check('Cấp ứng, hoàn ứng và quyết toán không trừ quỹ hai lần; giữ nhất quán khi sửa/xóa');
 assert.equal((await call('/import/preview')).length,0);let form=new FormData();form.append('file',new Blob([fs.readFileSync(process.env.VK_TEST_EXCEL||path.join(root,'tests/fixtures/ledger.xlsx'))]),'ledger.xlsx');let upload=await fetch(base+'/api/import/upload',{method:'POST',headers:{'X-VK-Bridge':secret,Authorization:'Bearer '+token},body:form});assert.equal(upload.status,200,await upload.text());let preview=await call('/import/preview');assert.equal(preview.length,process.env.VK_TEST_EXCEL?476:4);assert(preview.some(x=>x.issues.includes('BOTH_IN_AND_OUT')));assert(!preview.some(x=>x.description==='Bảng phụ không có tồn'));let row=preview.find(x=>!x.issues.length&&x.type==='EXPENSE');let imp={sourceId:row.id,date:row.date,type:row.type,amount:row.amount,fund_id:f1.id};await call('/import/commit','POST',[imp]);await call('/import/commit','POST',[imp],409);assert((await call('/import/preview')).find(x=>x.id===row.id).imported);check('Nhập Excel được chọn, loại bảng phụ và chống nhập trùng');
 // Bank metadata remains text, and attendance never moves money.
 let balanceBefore=(await call('/report?from=2026-10-01&to=2026-10-31')).funds.reduce((s,f)=>s+f.balance,0);
 f1=await call('/masters/funds/'+f1.id,'PUT',{...f1,bank_name:'Ngân hàng mẫu',account_number:'0012345678',account_holder:'Công ty mẫu'});assert.equal(f1.account_number,'0012345678');
 let bank2=await call('/masters/funds','POST',{name:'Ngân hàng thứ hai',kind:'BANK',opening:0,opening_date:'2026-05-01',bank_name:'Ngân hàng mẫu',account_number:'0099999999',account_holder:'Công ty mẫu'});assert.notEqual(bank2.id,f1.id);
 await call('/masters/funds','POST',{name:'Trùng',kind:'BANK',opening:0,opening_date:'2026-05-01',bank_name:'Ngân hàng mẫu',account_number:'0012345678'},400);
 await call('/masters/funds/'+f1.id,'PUT',{...f1,account_number:12.5},400);
 employee=await call('/masters/contacts/'+employee.id,'PUT',{...employee,attendance_code:'0007'});assert.equal(employee.attendance_code,'0007');
 await call('/masters/contacts','POST',{name:'Trùng mã',kind:'EMPLOYEE',attendance_code:'0007'},400);
 let work=await call('/attendance','POST',{employee_id:employee.id,date:'2026-10-01',status:'WORK',overtime_minutes:90,version:0});
 let half=await call('/attendance','POST',{employee_id:employee.id,date:'2026-10-02',status:'HALF',overtime_minutes:0,version:0});
 await call('/attendance','POST',{employee_id:employee.id,date:'2026-10-03',status:'PAID_LEAVE',overtime_minutes:0,version:0});
 await call('/attendance','POST',{...work,version:0},409);await call('/attendance','POST',{...work,overtime_minutes:91,reason:'Sai bước'},400);
 await call('/attendance','POST',{employee_id:customer.id,date:'2026-10-01',status:'WORK',version:0},400);
 work=await call('/attendance','POST',{...work,overtime_minutes:120,reason:'Đối chiếu tăng ca'});assert.equal(work.version,2);
 await call('/attendance/'+half.id,'DELETE',{version:half.version,reason:'Ghi nhầm'});assert.equal((await call('/attendance/2026-10')).entries.length,2);
 await call('/attendance','POST',{employee_id:employee.id,date:half.date,status:'HALF',version:0},400);
 half=await call('/attendance','POST',{employee_id:employee.id,date:half.date,status:'HALF',version:0,reason:'Chấm lại theo xác nhận'});assert.equal(half.id,2);assert.equal(half.version,3);
 let locked=await call('/attendance/month','POST',{month:'2026-10',locked:1,version:0,reason:'Chốt công'});assert.equal(locked.locked,1);
 await call('/attendance','POST',{...work,reason:'Thử sửa tháng khóa'},409);await call('/attendance/'+half.id,'DELETE',{version:half.version,reason:'Thử xóa'},409);
 await call('/attendance/month','POST',{month:'2026-10',locked:0,version:locked.version,reason:'Bổ sung chứng từ'});
 await call('/masters/contacts/'+employee.id,'PUT',{...employee,kind:'CUSTOMER'},400);
 assert.equal((await call('/report?from=2026-10-01&to=2026-10-31')).funds.reduce((s,f)=>s+f.balance,0),balanceBefore);
 assert((await call('/audit')).some(x=>x.action==='ATTENDANCE_UPDATE'&&JSON.parse(x.before_json).overtime_minutes===90));
 check('Hai ngân hàng, giữ số 0 đầu; công, tăng ca, sửa/xóa, khóa tháng và lịch sử không đổi số dư');
 let cat=await call('/masters/categories','POST',{name:'Tạm',kind:'BOTH'});cat=await call('/masters/categories/'+cat.id,'PUT',{...cat,name:'Đã sửa'});await call('/masters/categories/'+cat.id,'DELETE',{version:cat.version,reason:'Không dùng'});await call('/masters/funds/'+f1.id,'DELETE',{version:f1.version,reason:'Không dùng'},400);check('CRUD danh mục và bảo vệ dữ liệu đã được dùng');
 let viewerReg=await call('/auth/register','POST',{username:'viewer',name:'Chủ xem báo cáo',password,role:'VIEWER'});let viewer=await call('/auth/login','POST',{username:'viewer',password});token=viewer.token;assert.equal((await call('/evidence/file/'+ev.id)).base64,png.toString('base64'));await evidence('vouchers',receipt.id,png,'viewer.png',403);await call('/report?from=2026-10-01&to=2026-10-31');await call('/vouchers','POST',{type:'RECEIPT'},403);await call('/backup','POST',null,403);await call('/auth/register','POST',{username:'hack',password,name:'hack',role:'ADMIN'},403);await call('/attendance','POST',{employee_id:employee.id,date:'2026-10-04',status:'WORK',version:0},403);await call('/attendance/month','POST',{month:'2026-10',locked:1,version:2,reason:'Thử khóa'},403);assert.equal((await call('/attendance/2026-10')).entries.length,3);check('Vai trò chỉ xem không sửa dữ liệu, đăng ký Admin hoặc sao lưu');token=adminToken;
 let backup=await call('/backup','POST');let bytes=await fetch(base+'/api/backups/'+backup.file,{headers:{'X-VK-Bridge':secret,Authorization:'Bearer '+token}}).then(r=>r.arrayBuffer());assert(bytes.byteLength>1000);let balances=await call('/report?from=2026-10-01&to=2026-10-31');await call('/vouchers','POST',{type:'RECEIPT',date:'2026-10-03',description:'Sau sao lưu',amount:123456,fund_id:f1.id});let f=new FormData();f.append('file',new Blob([bytes]),'backup.sqlite');f.append('password',password);let restored=await fetch(base+'/api/restore',{method:'POST',headers:{'X-VK-Bridge':secret,Authorization:'Bearer '+token},body:f});assert.equal(restored.status,200,await restored.text());await call('/auth/me','GET',null,401);token=(await call('/auth/login','POST',{username:'admin',password})).token;assert.deepEqual((await call('/report?from=2026-10-01&to=2026-10-31')).totals,balances.totals);assert(!(await call('/vouchers')).some(x=>x.description==='Sau sao lưu'));assert.equal((await call('/attendance/2026-10')).entries.length,3);assert.equal((await call('/masters/funds')).find(x=>x.id===f1.id).account_number,'0012345678');assert.equal((await call('/evidence/file/'+ev.id)).base64,png.toString('base64'));assert.equal((await call('/evidence/file/'+debtEvidence.id)).base64,pdf.toString('base64'));assert.equal((await call('/evidence/vouchers/'+receipt.id))[0].deleted,1);check('Sao lưu bao gồm ảnh/PDF và lịch sử; SQLite toàn vẹn, khôi phục đúng số dư, giữ bản an toàn và thu hồi phiên');
 f=new FormData();f.append('file',new Blob(['invalid']),'invalid.sqlite');f.append('password',password);let bad=await fetch(base+'/api/restore',{method:'POST',headers:{'X-VK-Bridge':secret,Authorization:'Bearer '+token},body:f});assert.equal(bad.status,400);assert.deepEqual((await call('/report?from=2026-10-01&to=2026-10-31')).totals,balances.totals);check('Từ chối file khôi phục hỏng và giữ dữ liệu hiện tại');
 await call('/auth/password','POST',{oldPassword:password,password:'New-Password!2026'});await call('/auth/me','GET',null,401);await call('/auth/login','POST',{username:'admin',password},401);token=(await call('/auth/login','POST',{username:'admin',password:'New-Password!2026'})).token;await call('/auth/logout','POST');await call('/auth/me','GET',null,401);token='';await call('/auth/reset','POST',{username:'viewer',recoveryCode:'wrong-code',password:'ResetPassword!2026'},400);let reset=await call('/auth/reset','POST',{username:'viewer',recoveryCode:viewerReg.recoveryCode,password:'ResetPassword!2026'});assert(reset.recoveryCode!==viewerReg.recoveryCode);await call('/auth/reset','POST',{username:'viewer',recoveryCode:viewerReg.recoveryCode,password:'ResetPassword!2026'},400);token=(await call('/auth/login','POST',{username:'viewer',password:'ResetPassword!2026'})).token;check('Đổi/quên mật khẩu, xoay mã khôi phục và đăng xuất');
 fs.writeFileSync(path.join(root,'docs/TEST-RESULTS.md'),'# Kiểm thử backend V1\n\n'+checks.map(x=>'- Đạt: '+x).join('\n')+'\n\nDữ liệu kiểm thử riêng: '+path.basename(data)+'. Không dùng dữ liệu vận hành.\n');console.log(checks.length+' groups passed');
}catch(e){console.error(e);console.error(output.slice(-9000));process.exitCode=1;}finally{child.stdin.end();await new Promise(r=>{if(child.exitCode!==null)return r();let t=setTimeout(()=>{child.kill();r();},10000);child.once('exit',()=>{clearTimeout(t);r();});});}
