import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import net from 'node:net';import {spawn} from 'node:child_process';
const root=path.resolve(import.meta.dirname,'..'),data=path.join(root,'.test-data-migration-'+Date.now());fs.mkdirSync(path.join(data,'sockets'),{recursive:true});const password='Migration-Test!2026',secret=crypto.randomBytes(24).toString('hex');let child,base,token='',log='';
async function request(route,method='GET',body,expected=200){let r=await fetch(base+'/api'+route,{method,headers:{'X-VK-Bridge':secret,Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});let v=await r.json();assert.equal(r.status,expected,JSON.stringify(v));return v;}
async function start(jar){assert(fs.existsSync(jar),'Set VK_OLD_JAR to backend.jar from release 1.0.1 to run migration test');let port=await new Promise(res=>{let s=net.createServer();s.listen(0,'127.0.0.1',()=>{let p=s.address().port;s.close(()=>res(p));});});base='http://127.0.0.1:'+port;token='';log='';child=spawn(path.join(root,'runtime/bin/java.exe'),['-Djdk.net.unixdomain.tmpdir='+path.join(data,'sockets'),'-jar',jar],{windowsHide:true,env:{...process.env,VK_DATA_DIR:data,VK_PORT:String(port),VK_BRIDGE_SECRET:secret,VK_DESKTOP:'true'},stdio:['pipe','pipe','pipe']});child.stdout.on('data',b=>log+=b);child.stderr.on('data',b=>log+=b);for(let i=0;i<120;i++){try{await request('/health');return;}catch{}if(child.exitCode!==null)break;await new Promise(r=>setTimeout(r,250));}throw Error(log);}
async function stop(){if(!child||child.exitCode!==null)return;child.stdin.end();await new Promise(res=>{let t=setTimeout(()=>{child.kill();res();},10000);child.once('exit',()=>{clearTimeout(t);res();});});}
async function login(){token=(await request('/auth/login','POST',{username:'migration',password})).token;}
async function restore(bytes,status=200){let f=new FormData();f.append('file',new Blob([bytes]),'backup.sqlite');f.append('password',password);let r=await fetch(base+'/api/restore',{method:'POST',headers:{'X-VK-Bridge':secret,Authorization:'Bearer '+token},body:f});assert.equal(r.status,status,await r.text());}
try{
 await start(process.env.VK_OLD_JAR||path.join(root,'backend/target/thuchi-1.0.1.jar'));await request('/auth/register','POST',{username:'migration',name:'Kế toán thử nâng cấp',password});await login();let fund=await request('/masters/funds','POST',{name:'Ngân hàng cũ',kind:'BANK',opening:10000000,opening_date:'2026-10-01'});let employee=await request('/masters/contacts','POST',{name:'Nhân viên cũ',kind:'EMPLOYEE'});let voucher=await request('/vouchers','POST',{type:'RECEIPT',date:'2026-10-02',amount:500000,fund_id:fund.id,description:'Phiếu thử trước nâng cấp'});let audit=await request('/audit');let backup=await request('/backup','POST');let bytes=Buffer.from(await fetch(base+'/api/backups/'+backup.file,{headers:{'X-VK-Bridge':secret,Authorization:'Bearer '+token}}).then(r=>r.arrayBuffer()));await stop();
 await start(path.join(root,'backend/target/thuchi-1.1.0.jar'));await login();let f=(await request('/masters/funds')).find(x=>x.id===fund.id);assert.equal(f.bank_name,'');assert.equal(f.version,fund.version);assert.equal((await request('/vouchers')).find(x=>x.id===voucher.id).amount,500000);assert.equal((await request('/report?from=2026-10-01&to=2026-10-31')).funds[0].balance,10500000);let history=await request('/audit');for(let old of audit)assert.deepEqual(history.find(x=>x.id===old.id),old);assert.equal((await request('/attendance/2026-10')).entries.length,0);assert(fs.readdirSync(path.join(data,'backups')).length>=2);console.log('PASS upgrade real v1 database: users, bank balance, voucher IDs and audit preserved; backup before migration');
 await request('/attendance','POST',{employee_id:employee.id,date:'2026-10-03',status:'WORK',overtime_minutes:60,version:0});await restore(bytes);await request('/auth/me','GET',undefined,401);await login();assert.equal((await request('/attendance/2026-10')).entries.length,0);assert.equal((await request('/report?from=2026-10-01&to=2026-10-31')).funds[0].balance,10500000);console.log('PASS restore v1 backup into v2 app, migrate temporary file before replacement and preserve financial data');
 let corrupt=Buffer.from(bytes);corrupt.writeUInt32BE(3,60);await restore(corrupt,400);assert.equal((await request('/vouchers')).length,1);corrupt.writeUInt32BE(999,60);await restore(corrupt,400);assert.equal((await request('/report?from=2026-10-01&to=2026-10-31')).funds[0].balance,10500000);console.log('PASS reject mismatched / future-schema backups while retaining current database');
}catch(e){console.error(e);process.exitCode=1;}finally{await stop();}
