const {_electron}=require('C:/Users/Doan Huy/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const fs=require('fs'),path=require('path'),assert=require('assert/strict'),crypto=require('crypto');
const root=path.resolve(__dirname,'..'),data=path.join(root,'.test-ui-112-'+Date.now());fs.mkdirSync(data);
(async()=>{const app=await _electron.launch({executablePath:process.env.VK_TEST_EXECUTABLE||path.join(root,'node_modules/electron/dist/electron.exe'),args:process.env.VK_TEST_EXECUTABLE?[]:[root],env:{...process.env,VK_DATA_DIR:data,VK_TEST_HIDDEN:'true'},timeout:60000});try{const page=await app.firstWindow({timeout:60000});page.setDefaultTimeout(12000);let errors=[];page.on('pageerror',e=>errors.push(e.message));
const field=name=>name==='Tên'?page.locator('.modal input[name=name]'):page.getByLabel(new RegExp('^'+name));const button=name=>page.getByRole('button',{name,exact:true});
await field('Họ tên').fill('Kế toán kiểm thử');await field('Tên đăng nhập').fill('admin');await field('Mật khẩu').fill('1');await button('Tạo tài khoản').click();await button('Tôi đã lưu mã').click();await field('Tên đăng nhập').fill('admin');await field('Mật khẩu').fill('1');await button('Đăng nhập').click();await page.locator('h1').filter({hasText:'Tổng quan'}).waitFor();
const seed=await page.evaluate(async()=>{const login=await window.vk.api('/api/auth/login','POST',{username:'admin',password:'1'},'');const api=(p,b)=>window.vk.api('/api'+p,'POST',b,login.token);const c=await api('/masters/contacts',{name:'NCC linh kiện',kind:'SUPPLIER'});await api('/masters/funds',{name:'Ngân hàng công ty',kind:'BANK',opening:20000000,opening_date:'2026-10-01'});for(const amount of [10000000,2000000])await api('/obligations',{kind:'PAYABLE',debt_group:'SUPPLIER',contact_id:c.id,date:'2026-10-08',amount,description:'Nhập linh kiện '+amount});await api('/masters/funds',{name:'Quỹ không đủ',kind:'CASH',opening:100000,opening_date:'2026-10-01'});await api('/masters/contacts',{name:'Nhân viên không ở phải trả',kind:'EMPLOYEE'});for(const debt_group of ['CARRIER','LOAN','OTHER'])await api('/obligations',{kind:'PAYABLE',debt_group,contact_id:c.id,date:'2026-10-08',amount:300000,description:debt_group});return c;});
await button('↻ Làm mới').click();await page.locator('nav button').filter({hasText:'Công nợ phải trả'}).click();await page.getByLabel('Nhà cung cấp xem công nợ').selectOption(String(seed.id));await page.locator('.kpi strong').filter({hasText:'12.000.000'}).first().waitFor();await button('+ Thêm mới').click();assert.equal(await page.getByLabel('Loại khoản').inputValue(),'Phải trả');assert(await page.getByLabel('Loại khoản').evaluate(e=>e.readOnly));assert.equal(await page.locator('.modal select[name=kind]').count(),0);assert(!(await field('Đối tác').innerText()).includes('Nhân viên không ở phải trả'));assert.equal(await field('Đối tác / nhân viên').count(),0);await button('Hủy').click();await page.getByRole('img',{name:/Cơ cấu công nợ/}).waitFor();await page.getByRole('img',{name:/Công nợ theo đối tác/}).waitFor();await button('+ Thanh toán nhà cung cấp').click();assert.equal(await page.getByLabel('Đối tác thanh toán').inputValue(),'NCC linh kiện');assert(await page.getByLabel('Đối tác thanh toán').evaluate(e=>e.readOnly));assert.equal(await field('Công nợ / tạm ứng liên kết').count(),0);await field('Nguồn tiền').selectOption({label:'Quỹ không đủ'});await page.locator('.modal input[name=amount]').fill('200000');await button('Lưu thay đổi').click();await page.getByRole('alert').filter({hasText:'không đủ tiền'}).waitFor();await field('Nguồn tiền').selectOption({label:'Ngân hàng công ty'});await page.locator('.modal input[name=amount]').fill('200000');assert.equal(await page.locator('.modal input[name=amount]').inputValue(),'200.000');await button('Lưu thay đổi').click();await page.locator('.kpi strong').filter({hasText:'11.800.000'}).waitFor();
await button('+ Trả hàng giảm nợ').click();await page.locator('.modal input[name=amount]').fill('500000');assert.equal(await page.locator('.modal input[name=amount]').inputValue(),'500.000');await button('Lưu thay đổi').click();await page.locator('.kpi strong').filter({hasText:'11.300.000'}).waitFor();await page.getByRole('cell',{name:/Thanh toán tổng nợ/}).waitFor();await page.getByRole('cell',{name:/Trả hàng giảm nợ · TH/}).waitFor();assert.deepEqual(errors,[]);await page.screenshot({path:path.join(root,'outputs/cong-no-1.1.4.png'),fullPage:true});console.log('PASS supplier dashboard cards, aggregate payment without lot, live money grouping, return credit, ledger totals 11.3m, no renderer errors');
}finally{await app.close();}})().catch(e=>{console.error(e);process.exitCode=1});
