package vn.vinhkhang.warehouse;
import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.annotation.PostConstruct;import jakarta.annotation.PreDestroy;
import org.springframework.stereotype.Component;import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.beans.factory.annotation.Value;
import java.nio.file.*;import java.util.*;import java.math.*;import java.time.*;import java.util.concurrent.*;
/** Local, read-only accounting export. It never changes warehouse records. */
@Component public class FinanceSnapshot {
 public static void main(String[] args)throws Exception{if(args.length!=1)throw new IllegalArgumentException("Data directory required");var ds=new org.springframework.jdbc.datasource.DriverManagerDataSource("jdbc:h2:file:"+Path.of(args[0]).toAbsolutePath().resolve("warehouse")+";ACCESS_MODE_DATA=r;IFEXISTS=TRUE","sa","");var snapshot=new FinanceSnapshot(new JdbcTemplate(ds),new ObjectMapper(),new org.springframework.jdbc.datasource.DataSourceTransactionManager(ds),args[0]);snapshot.publish();snapshot.stop();} final org.springframework.transaction.support.TransactionTemplate exportTx;final JdbcTemplate db;final ObjectMapper json;final Path data;final ScheduledExecutorService timer=Executors.newSingleThreadScheduledExecutor(r->{Thread t=new Thread(r,"finance-snapshot");t.setDaemon(true);return t;});
 public FinanceSnapshot(JdbcTemplate db,ObjectMapper json,org.springframework.transaction.PlatformTransactionManager manager,@Value("${VK_DATA_DIR:./data}") String data){this.exportTx=new org.springframework.transaction.support.TransactionTemplate(manager);exportTx.setReadOnly(true);exportTx.setIsolationLevel(org.springframework.transaction.TransactionDefinition.ISOLATION_REPEATABLE_READ);this.db=db;this.json=json;this.data=Path.of(data).toAbsolutePath();}
 @PostConstruct public void start(){timer.scheduleWithFixedDelay(this::publish,2,10,TimeUnit.SECONDS);}
 @PreDestroy public void stop(){timer.shutdownNow();}
 public synchronized void publish(){try{exportTx.executeWithoutResult(status->{try{doPublish();}catch(Exception e){throw new IllegalStateException(e);}});}catch(Exception e){System.err.println("Finance export unavailable: "+e.getClass().getSimpleName());}}
 private static void addCarrier(List<Map<String,Object>> out,Map<String,Object>d,String type,String status){Object price=d.get("TRANSPORT_COST");BigDecimal amount=price instanceof BigDecimal n?n:BigDecimal.ZERO;String name=Objects.toString(d.get("CARRIER_NAME"),"").trim();if(amount.signum()==0&&name.isEmpty())return;var row=new LinkedHashMap<String,Object>();row.put("id","CARRIER-"+type+"-"+d.get("ID"));row.put("code",d.get("CODE"));row.put("status",status);row.put("operation","CARRIER");row.put("deleted",Boolean.TRUE.equals(d.get("DELETED")));row.put("supplier_id",name.isEmpty()?"":"CARRIER:"+name.toLowerCase(Locale.ROOT));row.put("supplier_name",name);row.put("supplier_code","Nhà xe");row.put("phone",Objects.toString(d.get("CARRIER_PHONE"),""));row.put("address","");Object day=d.get(type.equals("VEHICLE")?"SHIPMENT_DATE":"SALE_DATE");Object created=d.get("CREATED_AT");row.put("date",day!=null?day.toString():created instanceof OffsetDateTime t?t.atZoneSameInstant(ZoneId.of("Asia/Ho_Chi_Minh")).toLocalDate().toString():created.toString().substring(0,10));row.put("note","Cước vận chuyển phiếu xuất · "+d.get("CODE"));row.put("cost_known",!Boolean.FALSE.equals(d.get("CARRIER_COST_KNOWN")));row.put("priced",!Boolean.FALSE.equals(d.get("CARRIER_COST_KNOWN")));row.put("amount",amount.setScale(0,RoundingMode.HALF_UP).longValueExact());row.put("items",List.of());row.put("customer_transport_fee",d.getOrDefault("TRANSPORT_FEE",BigDecimal.ZERO));out.add(row);}
 private void doPublish()throws Exception {
  Files.createDirectories(data);Path identity=data.resolve("finance-source.id");if(!Files.exists(identity))Files.writeString(identity,UUID.randomUUID().toString(),StandardOpenOption.CREATE_NEW);
  var documents=db.queryForList("SELECT d.*,s.code supplier_code,s.name supplier_name,s.phone,s.address FROM stock_documents d LEFT JOIN suppliers s ON s.id=d.supplier_id WHERE d.type IN ('IN','OUT') ORDER BY d.id");
  var out=new ArrayList<Map<String,Object>>();
  for(var d:documents){boolean returned=Objects.toString(d.get("TYPE"),"").equals("OUT")&&d.get("RETURN_SOURCE_ID")!=null;if(Objects.toString(d.get("TYPE"),"").equals("OUT")&&!returned){addCarrier(out,d,"PART",Objects.toString(d.get("STATUS"),""));continue;}var row=new LinkedHashMap<String,Object>();row.put("id",d.get("ID").toString());row.put("code",d.get("CODE"));row.put("status",d.get("STATUS"));row.put("operation",returned?"RETURN":"IN");row.put("return_source_id",Objects.toString(d.get("RETURN_SOURCE_ID"),""));row.put("deleted",d.get("DELETED"));row.put("supplier_id",Objects.toString(d.get("SUPPLIER_ID"),""));row.put("supplier_code",Objects.toString(d.get("SUPPLIER_CODE"),""));row.put("supplier_name",Objects.toString(d.get("SUPPLIER_NAME"),""));row.put("phone",Objects.toString(d.get("PHONE"),""));row.put("address",Objects.toString(d.get("ADDRESS"),""));Object created=d.get("CREATED_AT");row.put("date",returned&&d.get("RETURN_DATE")!=null?d.get("RETURN_DATE").toString():created instanceof OffsetDateTime t?t.atZoneSameInstant(ZoneId.of("Asia/Ho_Chi_Minh")).toLocalDate().toString():created.toString().substring(0,10));row.put("note",Objects.toString(d.get("NOTE"),""));
   var lines=db.queryForList("SELECT p.code,p.name,p.unit,l.quantity,l.unit_cost FROM stock_document_lines l JOIN parts p ON p.id=l.part_id WHERE l.document_id=? ORDER BY l.id",d.get("ID"));var items=new ArrayList<Map<String,Object>>();BigDecimal total=BigDecimal.ZERO;boolean priced=!lines.isEmpty();
   for(var l:lines){var item=new LinkedHashMap<String,Object>();item.put("code",l.get("CODE"));item.put("name",l.get("NAME"));item.put("unit",l.get("UNIT"));item.put("quantity",l.get("QUANTITY"));item.put("unit_cost",l.get("UNIT_COST"));items.add(item);if(l.get("UNIT_COST")==null)priced=false;else total=total.add(((BigDecimal)l.get("QUANTITY")).multiply((BigDecimal)l.get("UNIT_COST")));}
   row.put("items",items);row.put("priced",priced);row.put("amount",total.setScale(0,RoundingMode.HALF_UP).longValueExact());out.add(row);
  }
  boolean hasShipments=db.queryForObject("SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='VEHICLE_SHIPMENTS'",Integer.class)>0;
  if(hasShipments)for(var d:db.queryForList("SELECT * FROM vehicle_shipments ORDER BY id"))addCarrier(out,d,"VEHICLE","POSTED");
  var payload=Map.of("format","VK-WAREHOUSE-FINANCE-1","source_id",Files.readString(identity).trim(),"generated_at",Instant.now().toString(),"documents",out);
  Path temp=data.resolve("finance-sync.tmp");Files.write(temp,json.writeValueAsBytes(payload));try{Files.move(temp,data.resolve("finance-sync.json"),StandardCopyOption.REPLACE_EXISTING,StandardCopyOption.ATOMIC_MOVE);}catch(AtomicMoveNotSupportedException e){Files.move(temp,data.resolve("finance-sync.json"),StandardCopyOption.REPLACE_EXISTING);}

 }
}
