package vn.vinhkhang.warehouse;
import org.junit.jupiter.api.Test;import org.junit.jupiter.api.io.TempDir;import java.nio.file.*;import java.util.*;import com.fasterxml.jackson.databind.ObjectMapper;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.jdbc.datasource.*;import static org.junit.jupiter.api.Assertions.*;
class FinanceSnapshotTest {
 @TempDir Path dir;
 @Test void exportsConfirmedReceiptsPricesAndCancellationWithoutChangingSource()throws Exception{
  var ds=new DriverManagerDataSource("jdbc:h2:mem:finance"+UUID.randomUUID()+";DB_CLOSE_DELAY=-1","sa","");var db=new JdbcTemplate(ds);
  db.execute("CREATE TABLE suppliers(id BIGINT PRIMARY KEY,code VARCHAR,name VARCHAR,phone VARCHAR,address VARCHAR)");db.execute("CREATE TABLE stock_documents(id BIGINT PRIMARY KEY,code VARCHAR,status VARCHAR,deleted BOOLEAN,supplier_id BIGINT,created_at TIMESTAMP WITH TIME ZONE,note VARCHAR,type VARCHAR)");db.execute("CREATE TABLE parts(id BIGINT PRIMARY KEY,code VARCHAR,name VARCHAR,unit VARCHAR)");db.execute("CREATE TABLE stock_document_lines(id BIGINT PRIMARY KEY,document_id BIGINT,part_id BIGINT,quantity DECIMAL(18,3),unit_cost DECIMAL(18,2))");
  db.update("INSERT INTO suppliers VALUES(1,'NCC','Nhà cung cấp','0900','Địa chỉ')");db.update("INSERT INTO parts VALUES(1,'LK','Linh kiện','cái')");db.update("INSERT INTO stock_documents VALUES(1,'NK1','POSTED',FALSE,1,TIMESTAMP WITH TIME ZONE '2026-10-07 20:00:00+00','nhập hàng','IN')");db.update("INSERT INTO stock_document_lines VALUES(1,1,1,10,100000)");
  var json=new ObjectMapper();var snapshot=new FinanceSnapshot(db,json,new DataSourceTransactionManager(ds),dir.toString());snapshot.publish();Path file=dir.resolve("finance-sync.json");var export=json.readTree(Files.readAllBytes(file));assertEquals("VK-WAREHOUSE-FINANCE-1",export.get("format").asText());assertEquals(1000000,export.get("documents").get(0).get("amount").asLong());assertEquals("2026-10-08",export.get("documents").get(0).get("date").asText());assertEquals(10,export.get("documents").get(0).get("items").get(0).get("quantity").asInt());db.execute("ALTER TABLE stock_documents ADD return_source_id BIGINT");db.execute("ALTER TABLE stock_documents ADD return_date DATE");db.update("INSERT INTO stock_documents(id,code,status,deleted,supplier_id,created_at,note,type,return_source_id,return_date) VALUES(2,'TH1','POSTED',FALSE,1,CURRENT_TIMESTAMP,'trả','OUT',1,DATE '2026-10-09')");db.update("INSERT INTO stock_document_lines VALUES(2,2,1,2,100000)");db.update("INSERT INTO stock_documents(id,code,status,deleted,supplier_id,created_at,note,type) VALUES(3,'XK1','POSTED',FALSE,1,CURRENT_TIMESTAMP,'xuất bán','OUT')");snapshot.publish();export=json.readTree(Files.readAllBytes(file));assertEquals(2,export.get("documents").size());assertEquals("RETURN",export.get("documents").get(1).get("operation").asText());assertEquals(200000,export.get("documents").get(1).get("amount").asLong());assertEquals("2026-10-09",export.get("documents").get(1).get("date").asText());db.execute("ALTER TABLE stock_documents ADD carrier_name VARCHAR");db.execute("ALTER TABLE stock_documents ADD carrier_phone VARCHAR");db.execute("ALTER TABLE stock_documents ADD transport_cost DECIMAL(18,2) DEFAULT 0");db.execute("ALTER TABLE stock_documents ADD transport_fee DECIMAL(18,2) DEFAULT 0");db.execute("UPDATE stock_documents SET carrier_name='A.Hùng',carrier_phone='0900',transport_cost=500000,transport_fee=800000 WHERE id=3");db.execute("CREATE TABLE vehicle_shipments(id BIGINT,code VARCHAR,deleted BOOLEAN,created_at TIMESTAMP WITH TIME ZONE,shipment_date DATE,carrier_name VARCHAR,carrier_phone VARCHAR,transport_cost DECIMAL(18,2),transport_fee DECIMAL(18,2))");db.execute("INSERT INTO vehicle_shipments VALUES(1,'XE-1',FALSE,CURRENT_TIMESTAMP,DATE '2026-10-08','A.Hùng','0900',600000,900000)");snapshot.publish();export=json.readTree(Files.readAllBytes(file));assertEquals(4,export.get("documents").size());assertEquals("CARRIER",export.get("documents").get(2).get("operation").asText());assertEquals(500000,export.get("documents").get(2).get("amount").asLong());assertEquals(800000,export.get("documents").get(2).get("customer_transport_fee").asLong());assertEquals("CARRIER-VEHICLE-1",export.get("documents").get(3).get("id").asText());assertEquals(600000,export.get("documents").get(3).get("amount").asLong());String id=export.get("source_id").asText();
  db.update("UPDATE stock_document_lines SET unit_cost=NULL");snapshot.publish();export=json.readTree(Files.readAllBytes(file));assertFalse(export.get("documents").get(0).get("priced").asBoolean());assertEquals(id,export.get("source_id").asText());
  db.update("UPDATE stock_documents SET deleted=TRUE");snapshot.publish();export=json.readTree(Files.readAllBytes(file));assertTrue(export.get("documents").get(0).get("deleted").asBoolean());assertEquals(3,db.queryForObject("SELECT COUNT(*) FROM stock_documents",Integer.class));snapshot.stop();
 }
}
