package vn.vinhkhang.warehouse;
import java.util.*;import java.math.*;import java.time.*;import org.springframework.jdbc.core.JdbcTemplate;
final class SalesFlow {
 static BigDecimal amount(Map<String,Object> m,String key){return RevenueReports.money(Map.of(key,Objects.toString(m.get(key),"").isBlank()?"0":m.get(key)),key,false);}
 static void header(JdbcTemplate db,String type,long id,Map<String,Object> m){boolean known=!(m.containsKey("transport_cost")&&Objects.toString(m.get("transport_cost"),"").isBlank());db.update("UPDATE "+(type.equals("VEHICLE")?"vehicle_shipments":"stock_documents")+" SET carrier_cost_known=? WHERE id=?",known,id);String carrier=RevenueReports.text(m,"carrier_name",200,false),carrierPhone=RevenueReports.text(m,"carrier_phone",100,false);db.update("UPDATE "+(type.equals("VEHICLE")?"vehicle_shipments":"stock_documents")+" SET carrier_name=?,carrier_phone=? WHERE id=?",carrier,carrierPhone,id);String channel=Objects.toString(m.get("sale_channel"),"STORE");if(!Set.of("STORE","DEALER").contains(channel))throw new Api.Problem(400,"Chọn khách cửa hàng hoặc đại lý");BigDecimal discount=amount(m,"discount"),support=amount(m,"support");if(channel.equals("STORE")&&(discount.signum()!=0||support.signum()!=0))throw new Api.Problem(400,"Chiết khấu và hỗ trợ chỉ dành cho đại lý");String code=RevenueReports.text(m,"party_code",80,false),province=RevenueReports.text(m,"province",200,false);BigDecimal transport=amount(m,"transport_cost"),fee=amount(m,"transport_fee");if(type.equals("VEHICLE"))db.update("UPDATE vehicle_shipments SET shipment_purpose=?,sale_channel=?,party_code=?,province=?,discount=?,support=?,transport_cost=?,transport_fee=? WHERE id=?",SalesShipments.purpose(m),channel,code,province,discount,support,transport,fee,id);else{String purpose=Objects.toString(m.get("sales_purpose"),"INTERNAL");if(!Set.of("INTERNAL","SALE").contains(purpose))throw new Api.Problem(400,"Mục đích xuất không hợp lệ");db.update("UPDATE stock_documents SET sales_purpose=?,sale_channel=?,party_code=?,party_name=?,phone=?,province=?,sale_date=?,discount=?,support=?,transport_cost=?,transport_fee=? WHERE id=?",purpose,channel,code,RevenueReports.text(m,"party_name",200,purpose.equals("SALE")),RevenueReports.text(m,"phone",100,false),province,RevenueReports.day(m.getOrDefault("sale_date",LocalDate.now().toString())),discount,support,transport,fee,id);}}
 static void prices(Api core,JdbcTemplate db,long id,Map<String,Object> m){boolean sold="OUT".equals(m.get("type"))&&"SALE".equals(m.get("sales_purpose"));for(var line:core.lines(m,"lines"))db.update("UPDATE stock_document_lines SET sale_unit_price=? WHERE document_id=? AND part_id=?",sold?(Boolean.TRUE.equals(m.get("_factory_no_prices"))?Costing.cost(line,"sale_unit_price"):RevenueReports.money(line,"sale_unit_price",false)):null,id,core.num(line,"part_id"));}
 static void post(Api core,JdbcTemplate db,String type,long id,Api.Session actor){if(type.equals("VEHICLE")&&!db.queryForObject("SELECT shipment_purpose FROM vehicle_shipments WHERE id=?",String.class,id).equals("SALE"))return;if(type.equals("PART")){var d=db.queryForList("SELECT type,sales_purpose FROM stock_documents WHERE id=?",id).getFirst();if(!d.get("TYPE").equals("OUT")||!d.get("SALES_PURPOSE").equals("SALE"))return;}var revenue=new RevenueReports(core,db,null);var source=revenue.source(type,id,false);if(type.equals("PART")&&!"SALE".equals(source.get("SALES_PURPOSE")))return;var lines=revenue.groups(type,id);if(lines.stream().anyMatch(l->l.get("unit_price")==null))return;BigDecimal total=lines.stream().map(l->RevenueReports.number(l.get("quantity")).multiply(RevenueReports.number(l.get("unit_price"))).setScale(2,RoundingMode.HALF_UP)).reduce(BigDecimal.ZERO,BigDecimal::add),discount=RevenueReports.number(source.get("DISCOUNT")),support=RevenueReports.number(source.get("SUPPORT")),allocatedDiscount=BigDecimal.ZERO,allocatedSupport=BigDecimal.ZERO;
 for(int i=0;i<lines.size();i++){var row=lines.get(i);BigDecimal gross=RevenueReports.number(row.get("quantity")).multiply(RevenueReports.number(row.get("unit_price"))).setScale(2,RoundingMode.HALF_UP);boolean last=i==lines.size()-1;BigDecimal d=last?discount.subtract(allocatedDiscount):total.signum()==0?BigDecimal.ZERO:discount.multiply(gross).divide(total,2,RoundingMode.DOWN),s=last?support.subtract(allocatedSupport):total.signum()==0?BigDecimal.ZERO:support.multiply(gross).divide(total,2,RoundingMode.DOWN);allocatedDiscount=allocatedDiscount.add(d);allocatedSupport=allocatedSupport.add(s);row.put("discount",d);row.put("support",s);}
 var m=new LinkedHashMap<String,Object>();String channel=Objects.toString(source.get("SALE_CHANNEL"),"STORE");m.put("source_type",type);m.put("source_id",id);m.put("channel",channel);m.put("party_code",Objects.toString(source.get("PARTY_CODE"),"").isBlank()?(channel.equals("STORE")?"KH-":"DL-")+id:source.get("PARTY_CODE"));m.put("party_name",source.get("PARTY_NAME"));m.put("phone",source.get("PHONE"));m.put("province",source.get("PROVINCE"));m.put("sale_date",Objects.toString(source.get("SALE_DATE"),LocalDate.now().toString()));m.put("transport_cost",source.get("TRANSPORT_COST"));m.put("transport_fee",source.get("TRANSPORT_FEE"));m.put("lines",lines);revenue.saveInternal(actor,m);}
}
