package vn.vinhkhang.thuchi;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.servlet.http.HttpServletRequest;
import java.nio.file.*;
import java.time.*;
import java.util.*;
import java.security.SecureRandom;
import java.sql.*;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.transaction.support.TransactionTemplate;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.http.*;

@RestController @RequestMapping("/api")
public class Api {
 final JdbcTemplate db; final TransactionTemplate tx; final ObjectMapper json;
 final BCryptPasswordEncoder encoder=new BCryptPasswordEncoder(12);
 final Map<String,Session> sessions=new HashMap<>(); final Map<String,Attempt> attempts=new HashMap<>();
 final String bridge=System.getenv().getOrDefault("VK_BRIDGE_SECRET",UUID.randomUUID().toString());
 record Session(long user,long expires){} record Attempt(int count,long until){}
 public Api(JdbcTemplate db,PlatformTransactionManager manager,ObjectMapper json)throws Exception {
  this.db=db;this.tx=new TransactionTemplate(manager);this.json=json;
  int version=db.queryForObject("PRAGMA user_version",Integer.class);
  if(version>3)throw new IllegalStateException("Database version newer than app");
  if(version==0) {String sql=new String(new ClassPathResource("schema.sql").getInputStream().readAllBytes(),java.nio.charset.StandardCharsets.UTF_8);
   // SQLite trigger bodies contain semicolons: execute the trigger statements intact.
   StringBuilder stmt=new StringBuilder();boolean trigger=false;
   for(String line:sql.split("\\R")){if(line.startsWith("CREATE TRIGGER")){db.execute(line);continue;}stmt.append(line).append('\n');if(line.endsWith(";")){db.execute(stmt.toString());stmt.setLength(0);}}
  }
  if(version>0)createBackup();
  try(Connection c=db.getDataSource().getConnection()){DatabaseUpgrade.upgrade(c);}
 }
 void local(HttpServletRequest r){if(!bridge.equals(r.getHeader("X-VK-Bridge")))throw new Fail(403,"Kết nối không được cho phép");}
 Map<String,Object> auth(HttpServletRequest r,boolean admin){local(r);String token=r.getHeader("Authorization");Session s=token==null?null:sessions.get(token.replaceFirst("^Bearer ",""));if(s==null||s.expires<System.currentTimeMillis())throw new Fail(401,"Vui lòng đăng nhập lại");var rows=db.queryForList("SELECT id,username,name,role,active FROM users WHERE id=?",s.user);if(rows.isEmpty()||num(rows.get(0),"active")==0)throw new Fail(401,"Tài khoản đã bị khóa");var u=rows.get(0);if(admin&&!"ADMIN".equals(u.get("role")))throw new Fail(403,"Chỉ kế toán Admin được thực hiện");return u;}
 long actor(HttpServletRequest r){return num(auth(r,true),"id");}
 static class Fail extends RuntimeException {final int status;Fail(int s,String m){super(m);status=s;}}
 @ExceptionHandler(Fail.class) ResponseEntity<?> fail(Fail f){return ResponseEntity.status(f.status).body(Map.of("error",f.getMessage()));}
 @ExceptionHandler(Exception.class) ResponseEntity<?> other(Exception e){org.slf4j.LoggerFactory.getLogger(Api.class).error("Operation failed",e);return ResponseEntity.badRequest().body(Map.of("error","Dữ liệu không hợp lệ hoặc thao tác không thực hiện được. Kiểm tra lại các trường và thử lại."));}
 static String str(Map<String,Object>b,String k){Object v=b.get(k);return v==null?"":String.valueOf(v).trim();}
 static long num(Map<String,Object>b,String k){try{Object v=b.get(k);if(v==null||v.toString().isBlank())return 0;return new java.math.BigDecimal(v.toString()).longValueExact();}catch(Exception e){throw new Fail(400,"Số tiền/mã phải là số nguyên");}}
 static String required(Map<String,Object>b,String k){String v=str(b,k);if(v.isEmpty()||v.length()>2000)throw new Fail(400,"Thiếu hoặc quá dài: "+k);return v;}
 static String date(Map<String,Object>b,String k){String s=required(b,k);try{return LocalDate.parse(s).toString();}catch(Exception e){throw new Fail(400,"Ngày không hợp lệ: "+k);}}
 static void amount(long n){if(n<=0||n>1000000000000L)throw new Fail(400,"Số tiền phải nguyên dương, tối đa 1.000 tỷ đồng");}
 static String choice(String s,String...valid){if(!List.of(valid).contains(s))throw new Fail(400,"Loại dữ liệu không hợp lệ");return s;}
 Map<String,Object> one(String table,long id){var rows=db.queryForList("SELECT * FROM "+table+" WHERE id=?",id);if(rows.isEmpty())throw new Fail(404,"Không tìm thấy dữ liệu");return rows.get(0);}
 String serialize(Object o){try{return json.writeValueAsString(o);}catch(Exception e){throw new IllegalStateException(e);}}
 void audit(long actor,String action,String entity,long id,Object before,Object after,String reason){db.update("INSERT INTO audit(actor_id,action,entity,entity_id,before_json,after_json,reason) VALUES(?,?,?,?,?,?,?)",actor==0?null:actor,action,entity,id==0?null:id,before==null?null:serialize(before),after==null?null:serialize(after),reason);}
 long last(){return db.queryForObject("SELECT last_insert_rowid()",Long.class);}
 void throttle(String key){Attempt a=attempts.get(key);if(a!=null&&a.count>=5&&a.until>System.currentTimeMillis())throw new Fail(429,"Thử sai quá nhiều lần. Đợi 15 phút.");}
 void bad(String key){Attempt a=attempts.get(key);int n=a==null||a.until<System.currentTimeMillis()?1:a.count+1;attempts.put(key,new Attempt(n,System.currentTimeMillis()+900000));}
 String recovery(){byte[] b=new byte[24];new SecureRandom().nextBytes(b);return Base64.getUrlEncoder().withoutPadding().encodeToString(b);}
 void password(String s){if(s.length()<1||s.length()>72)throw new Fail(400,"Mật khẩu từ 1 đến 72 ký tự");}
 void revoke(long id){sessions.entrySet().removeIf(e->e.getValue().user==id);}
 @GetMapping("/health") synchronized Map<String,Object> health(HttpServletRequest r){local(r);return Map.of("status","UP","version","1.1.1","initialized",db.queryForObject("SELECT COUNT(*) FROM users",Integer.class)>0);}
 @PostMapping("/auth/register") synchronized Map<String,Object> register(@RequestBody Map<String,Object>b,HttpServletRequest r){local(r);int count=db.queryForObject("SELECT COUNT(*) FROM users",Integer.class);long actor=count==0?0:actor(r);String user=required(b,"username");if(!user.matches("[a-zA-Z0-9_.-]{3,40}"))throw new Fail(400,"Tên đăng nhập từ 3–40 ký tự, không dấu");String p=required(b,"password");password(p);String code=recovery();return tx.execute(t->{db.update("INSERT INTO users(username,name,password_hash,recovery_hash,role) VALUES(?,?,?,?,?)",user,required(b,"name"),encoder.encode(p),encoder.encode(code),count==0?"ADMIN":choice(str(b,"role"),"ADMIN","VIEWER"));long id=last();audit(actor,"REGISTER","users",id,null,Map.of("username",user),"");return Map.of("recoveryCode",code,"username",user);});}
 @PostMapping("/auth/login") synchronized Map<String,Object> login(@RequestBody Map<String,Object>b,HttpServletRequest r){local(r);String user=required(b,"username");String key="login:"+user.toLowerCase();throttle(key);var rows=db.queryForList("SELECT * FROM users WHERE username=?",user);if(rows.isEmpty()||num(rows.get(0),"active")==0||!encoder.matches(str(b,"password"),String.valueOf(rows.get(0).get("password_hash")))){bad(key);throw new Fail(401,"Tên đăng nhập hoặc mật khẩu không đúng");}var u=rows.get(0);attempts.remove(key);String token=recovery();sessions.put(token,new Session(num(u,"id"),System.currentTimeMillis()+28800000));audit(num(u,"id"),"LOGIN","users",num(u,"id"),null,null,"");return Map.of("token",token,"user",Map.of("id",u.get("id"),"name",u.get("name"),"username",u.get("username"),"role",u.get("role")));}
 @GetMapping("/auth/me") synchronized Map<String,Object> me(HttpServletRequest r){return auth(r,false);}
 @PostMapping("/auth/logout") synchronized Map<String,Object> logout(HttpServletRequest r){var u=auth(r,false);sessions.remove(r.getHeader("Authorization").replaceFirst("^Bearer ",""));audit(num(u,"id"),"LOGOUT","users",num(u,"id"),null,null,"");return Map.of("ok",true);}
 @PostMapping("/auth/reset") synchronized Map<String,Object> reset(@RequestBody Map<String,Object>b,HttpServletRequest r){local(r);String key="reset:"+required(b,"username").toLowerCase();throttle(key);var rows=db.queryForList("SELECT * FROM users WHERE username=? AND active=1",str(b,"username"));if(rows.isEmpty()||!encoder.matches(str(b,"recoveryCode"),String.valueOf(rows.get(0).get("recovery_hash")))){bad(key);throw new Fail(400,"Tên đăng nhập hoặc mã khôi phục không đúng");}String p=required(b,"password");password(p);String code=recovery();long id=num(rows.get(0),"id");tx.executeWithoutResult(t->{db.update("UPDATE users SET password_hash=?,recovery_hash=? WHERE id=?",encoder.encode(p),encoder.encode(code),id);audit(id,"PASSWORD_RESET","users",id,null,null,"");});revoke(id);attempts.remove(key);return Map.of("recoveryCode",code);}
 @PostMapping("/auth/password") synchronized Map<String,Object> changePassword(@RequestBody Map<String,Object>b,HttpServletRequest r){var u=auth(r,false);long id=num(u,"id");String key="password:"+id;throttle(key);if(!encoder.matches(str(b,"oldPassword"),String.valueOf(one("users",id).get("password_hash")))){bad(key);throw new Fail(400,"Mật khẩu hiện tại không đúng");}String p=required(b,"password");password(p);String code=recovery();tx.executeWithoutResult(t->{db.update("UPDATE users SET password_hash=?,recovery_hash=? WHERE id=?",encoder.encode(p),encoder.encode(code),id);audit(id,"PASSWORD_CHANGE","users",id,null,null,"");});revoke(id);attempts.remove(key);return Map.of("recoveryCode",code);}
 @GetMapping("/users") synchronized List<Map<String,Object>> users(HttpServletRequest r){actor(r);return db.queryForList("SELECT id,username,name,role,active,created_at FROM users ORDER BY id");}
 @PutMapping("/users/{id}") synchronized Map<String,Object> user(@PathVariable long id,@RequestBody Map<String,Object>b,HttpServletRequest r){long a=actor(r);var old=one("users",id);long active=num(b,"active");if(active!=0&&active!=1)throw new Fail(400,"Trạng thái không hợp lệ");String role=choice(str(b,"role"),"ADMIN","VIEWER");if("ADMIN".equals(old.get("role"))&&num(old,"active")==1&&(active==0||!role.equals("ADMIN"))&&db.queryForObject("SELECT COUNT(*) FROM users WHERE active=1 AND role='ADMIN'",Integer.class)<=1)throw new Fail(400,"Phải giữ ít nhất một Admin hoạt động");return tx.execute(t->{db.update("UPDATE users SET name=?,role=?,active=? WHERE id=?",required(b,"name"),role,active,id);audit(a,"UPDATE","users",id,Map.of("name",old.get("name"),"role",old.get("role"),"active",old.get("active")),Map.of("name",required(b,"name"),"role",role,"active",active),"");revoke(id);return Map.of("ok",true);});}
 @GetMapping("/masters/{table}") synchronized List<Map<String,Object>> masters(@PathVariable String table,HttpServletRequest r){auth(r,false);choice(table,"funds","categories","contacts");return db.queryForList("SELECT * FROM "+table+" WHERE deleted=0 ORDER BY id DESC");}
 @PostMapping("/masters/{table}") synchronized Map<String,Object> createMaster(@PathVariable String table,@RequestBody Map<String,Object>b,HttpServletRequest r){long a=actor(r);return tx.execute(t->saveMaster(table,0,b,a));}
 @PutMapping("/masters/{table}/{id}") synchronized Map<String,Object> editMaster(@PathVariable String table,@PathVariable long id,@RequestBody Map<String,Object>b,HttpServletRequest r){long a=actor(r);return tx.execute(t->saveMaster(table,id,b,a));}
 Map<String,Object> saveMaster(String table,long id,Map<String,Object>b,long a){choice(table,"funds","categories","contacts");var old=id==0?null:one(table,id);if(old!=null&&(num(old,"deleted")!=0||num(old,"version")!=num(b,"version")))throw new Fail(409,"Dữ liệu đã thay đổi. Tải lại màn hình.");String name=required(b,"name"),kind=required(b,"kind"),note=str(b,"note"),customerType=choice(str(b,"customer_type").isEmpty()?"RETAIL":str(b,"customer_type"),"RETAIL","DEALER"),partyType=choice(str(b,"party_type").isEmpty()?(kind.equals("SUPPLIER")?"SUPPLIER":"OTHER"):str(b,"party_type"),"SUPPLIER","CARRIER","LENDER","INVESTOR","OTHER"),address=str(b,"address");if(address.length()>1000)throw new Fail(400,"Địa chỉ quá dài");
  if(table.equals("funds")){String bank=str(b,"bank_name"),account=str(b,"account_number"),holder=str(b,"account_holder");if(bank.length()>100||holder.length()>200||!account.isEmpty()&&!account.matches("[0-9]{3,40}"))throw new Fail(400,"Số tài khoản phải từ 3–40 chữ số; giữ số 0 ở đầu");if(kind.equals("BANK")&&!account.isEmpty()){if(bank.isEmpty())throw new Fail(400,"Nhập tên ngân hàng khi ghi số tài khoản");if(db.queryForObject("SELECT COUNT(*) FROM funds WHERE kind='BANK' AND bank_name=? COLLATE NOCASE AND account_number=? AND id<>? AND deleted=0",Integer.class,bank,account,id)>0)throw new Fail(400,"Tài khoản ngân hàng đã có trong nguồn tiền");}if(!kind.equals("BANK")){bank="";account="";holder="";}
choice(kind,"CASH","BANK","OTHER");long opening=num(b,"opening");if(opening < -1000000000000L || opening > 1000000000000L)throw new Fail(400,"Số dư quá lớn");String d=date(b,"opening_date");if(id>0&&db.queryForObject("SELECT COUNT(*) FROM vouchers WHERE deleted=0 AND (fund_id=? OR to_fund_id=?) AND date<?",Integer.class,id,id,d)>0)throw new Fail(400,"Ngày số dư đầu kỳ nằm sau giao dịch đã ghi");if(id==0)db.update("INSERT INTO funds(name,kind,opening,opening_date,note,bank_name,account_number,account_holder) VALUES(?,?,?,?,?,?,?,?)",name,kind,opening,d,note,bank,account,holder);else db.update("UPDATE funds SET name=?,kind=?,opening=?,opening_date=?,note=?,bank_name=?,account_number=?,account_holder=?,version=version+1 WHERE id=?",name,kind,opening,d,note,bank,account,holder,id);}
  else if(table.equals("categories")){choice(kind,"IN","OUT","BOTH");if(id>0&&!kind.equals("BOTH")&&db.queryForObject("SELECT COUNT(*) FROM vouchers WHERE deleted=0 AND category_id=? AND type=?",Integer.class,id,kind.equals("IN")?"EXPENSE":"RECEIPT")>0)throw new Fail(400,"Danh mục đang dùng cho loại phiếu khác");if(id==0)db.update("INSERT INTO categories(name,kind,note) VALUES(?,?,?)",name,kind,note);else db.update("UPDATE categories SET name=?,kind=?,note=?,version=version+1 WHERE id=?",name,kind,note,id);}
  else {choice(kind,"CUSTOMER","SUPPLIER","EMPLOYEE","OTHER");String attendanceCode=kind.equals("EMPLOYEE")?str(b,"attendance_code"):"";if(attendanceCode.length()>40||!attendanceCode.isEmpty()&&!attendanceCode.matches("[A-Za-z0-9_.-]+"))throw new Fail(400,"Mã chấm công tối đa 40 ký tự, chữ không dấu/số/._-");if(!attendanceCode.isEmpty()&&db.queryForObject("SELECT COUNT(*) FROM contacts WHERE kind='EMPLOYEE' AND attendance_code=? COLLATE NOCASE AND id<>?",Integer.class,attendanceCode,id)>0)throw new Fail(400,"Mã chấm công đã dùng cho nhân viên khác");if(id>0&&!kind.equals("EMPLOYEE")&&db.queryForObject("SELECT COUNT(*) FROM attendance WHERE employee_id=?",Integer.class,id)>0)throw new Fail(400,"Nhân viên đã có lịch sử chấm công, không đổi loại");if(id==0)db.update("INSERT INTO contacts(name,kind,phone,note,attendance_code,customer_type,party_type,address) VALUES(?,?,?,?,?,?,?,?)",name,kind,str(b,"phone"),note,attendanceCode,customerType,partyType,address);else db.update("UPDATE contacts SET name=?,kind=?,phone=?,note=?,attendance_code=?,customer_type=?,party_type=?,address=?,version=version+1 WHERE id=?",name,kind,str(b,"phone"),note,attendanceCode,customerType,partyType,address,id);}
  if(id==0)id=last();audit(a,old==null?"CREATE":"UPDATE",table,id,old,one(table,id),str(b,"reason"));return one(table,id);
 }
 @DeleteMapping("/masters/{table}/{id}") synchronized Map<String,Object> deleteMaster(@PathVariable String table,@PathVariable long id,@RequestBody Map<String,Object>b,HttpServletRequest r){long a=actor(r);choice(table,"funds","categories","contacts");return tx.execute(t->{var old=one(table,id);required(b,"reason");if(num(old,"version")!=num(b,"version")||num(old,"deleted")!=0)throw new Fail(409,"Dữ liệu đã thay đổi");String ref=table.equals("funds")?"fund_id=? OR to_fund_id=?":table.equals("categories")?"category_id=?":"contact_id=?";int used=table.equals("funds")?db.queryForObject("SELECT COUNT(*) FROM vouchers WHERE "+ref,Integer.class,id,id):db.queryForObject("SELECT COUNT(*) FROM vouchers WHERE "+ref,Integer.class,id);if(table.equals("contacts"))used+=db.queryForObject("SELECT COUNT(*) FROM obligations WHERE contact_id=?",Integer.class,id);if(table.equals("contacts"))used+=db.queryForObject("SELECT COUNT(*) FROM attendance WHERE employee_id=?",Integer.class,id);if(used>0)throw new Fail(400,"Dữ liệu đã được dùng trong chứng từ, không thể xóa");db.update("UPDATE "+table+" SET deleted=1,version=version+1 WHERE id=?",id);audit(a,"DELETE",table,id,old,one(table,id),str(b,"reason"));return Map.of("ok",true);});}
 void available(String table,long id){if(id<=0||num(one(table,id),"deleted")!=0)throw new Fail(400,"Chọn dữ liệu đang hoạt động: "+table);}
 long outstanding(long id,long exclude){var o=one("obligations",id);String kinds=o.get("kind").equals("PAYABLE")?"type='EXPENSE'": "type='RECEIPT'";long paid=db.queryForObject("SELECT COALESCE(SUM(amount),0) FROM vouchers WHERE deleted=0 AND purpose NOT IN ('LOAN_INTEREST','LOAN_RECEIVE') AND obligation_id=? AND id<>? AND "+kinds,Long.class,id,exclude);long cleared=db.queryForObject("SELECT COALESCE(SUM(amount),0) FROM clearings WHERE obligation_id=?",Long.class,id);return num(o,"amount")-paid-cleared;}
 @GetMapping("/obligations") synchronized List<Map<String,Object>> obligations(HttpServletRequest r){auth(r,false);var rows=db.queryForList("SELECT o.*,c.name contact_name FROM obligations o JOIN contacts c ON c.id=o.contact_id WHERE o.deleted=0 AND o.kind<>'RECEIVABLE' ORDER BY o.date DESC,o.id DESC");for(var o:rows){long id=num(o,"id");o.put("outstanding",outstanding(id,0));o.put("loan_received",db.queryForObject("SELECT COALESCE(SUM(amount),0) FROM vouchers WHERE deleted=0 AND obligation_id=? AND purpose='LOAN_RECEIVE'",Long.class,id));o.put("interest_paid",db.queryForObject("SELECT COALESCE(SUM(amount),0) FROM vouchers WHERE deleted=0 AND obligation_id=? AND purpose='LOAN_INTEREST'",Long.class,id));o.put("issued",db.queryForObject("SELECT COALESCE(SUM(amount),0) FROM vouchers WHERE deleted=0 AND obligation_id=? AND purpose='ADVANCE_ISSUE'",Long.class,id));}return rows;}
 @PostMapping("/obligations") synchronized Map<String,Object> createObligation(@RequestBody Map<String,Object>b,HttpServletRequest r){long a=actor(r);return tx.execute(t->saveObligation(0,b,a));}
 @PutMapping("/obligations/{id}") synchronized Map<String,Object> editObligation(@PathVariable long id,@RequestBody Map<String,Object>b,HttpServletRequest r){long a=actor(r);return tx.execute(t->saveObligation(id,b,a));}
 Map<String,Object> saveObligation(long id,Map<String,Object>b,long a){String kind=choice(str(b,"kind"),"PAYABLE","ADVANCE"),d=date(b,"date"),due=str(b,"due_date");if(!due.isEmpty()){date(b,"due_date");if(due.compareTo(d)<0)throw new Fail(400,"Hạn thanh toán trước ngày ghi nhận");}String debtGroup=choice(str(b,"debt_group").isEmpty()?"SUPPLIER":str(b,"debt_group"),"SUPPLIER","CARRIER","LOAN","OTHER");long n=num(b,"amount"),contact=num(b,"contact_id");amount(n);available("contacts",contact);if(kind.equals("PAYABLE")&&str(one("contacts",contact),"kind").equals("CUSTOMER"))throw new Fail(400,"Chọn bên phải trả, không dùng công nợ khách hàng");var old=id==0?null:one("obligations",id);if(old!=null){if(num(old,"deleted")!=0||num(old,"version")!=num(b,"version"))throw new Fail(409,"Dữ liệu đã thay đổi");if(!old.get("kind").equals(kind)||num(old,"contact_id")!=contact)throw new Fail(400,"Không đổi loại/đối tác của khoản nợ. Tạo khoản mới.");if(!str(old,"debt_group").equals(debtGroup)&&(str(old,"debt_group").equals("LOAN")||debtGroup.equals("LOAN"))&&db.queryForObject("SELECT COUNT(*) FROM vouchers WHERE obligation_id=?",Integer.class,id)>0)throw new Fail(400,"Khoản vay đã có phiếu, không đổi nhóm vay vốn");required(b,"reason");long received=db.queryForObject("SELECT COALESCE(SUM(amount),0) FROM vouchers WHERE deleted=0 AND obligation_id=? AND purpose='LOAN_RECEIVE'",Long.class,id);if(n<received)throw new Fail(400,"Nợ gốc nhỏ hơn số tiền vay đã ghi nhận");long paid=num(old,"amount")-outstanding(id,0);long issued=db.queryForObject("SELECT COALESCE(SUM(amount),0) FROM vouchers WHERE deleted=0 AND obligation_id=? AND purpose='ADVANCE_ISSUE'",Long.class,id);if(n<paid||n<issued)throw new Fail(400,"Số tiền nhỏ hơn số đã thanh toán/đã cấp");if(db.queryForObject("SELECT COUNT(*) FROM vouchers WHERE deleted=0 AND obligation_id=? AND date<?",Integer.class,id,d)>0||db.queryForObject("SELECT COUNT(*) FROM clearings WHERE obligation_id=? AND date<?",Integer.class,id,d)>0)throw new Fail(400,"Ngày ghi nhận sau ngày thanh toán/quyết toán");}
  if(id==0){db.update("INSERT INTO obligations(code,kind,contact_id,description,amount,date,due_date,debt_group) VALUES(?,?,?,?,?,?,?,?)","CN-"+UUID.randomUUID().toString().substring(0,8).toUpperCase(),kind,contact,required(b,"description"),n,d,due.isEmpty()?null:due,debtGroup);id=last();}else db.update("UPDATE obligations SET description=?,amount=?,date=?,due_date=?,debt_group=?,version=version+1 WHERE id=?",required(b,"description"),n,d,due.isEmpty()?null:due,debtGroup,id);audit(a,old==null?"CREATE":"UPDATE","obligations",id,old,one("obligations",id),str(b,"reason"));return one("obligations",id);
 }
 @DeleteMapping("/obligations/{id}") synchronized Map<String,Object> deleteObligation(@PathVariable long id,@RequestBody Map<String,Object>b,HttpServletRequest r){long a=actor(r);return tx.execute(t->{var old=one("obligations",id);required(b,"reason");if(num(old,"deleted")!=0||num(old,"version")!=num(b,"version"))throw new Fail(409,"Dữ liệu đã thay đổi");if(db.queryForObject("SELECT COUNT(*) FROM vouchers WHERE obligation_id=?",Integer.class,id)>0||db.queryForObject("SELECT COUNT(*) FROM clearings WHERE obligation_id=?",Integer.class,id)>0)throw new Fail(400,"Khoản nợ đã có chứng từ liên kết");db.update("UPDATE obligations SET deleted=1,version=version+1 WHERE id=?",id);audit(a,"DELETE","obligations",id,old,one("obligations",id),str(b,"reason"));return Map.of("ok",true);});}
 @PostMapping("/obligations/{id}/clear") synchronized Map<String,Object> clear(@PathVariable long id,@RequestBody Map<String,Object>b,HttpServletRequest r){long a=actor(r);return tx.execute(t->{available("obligations",id);var o=one("obligations",id);if(!o.get("kind").equals("ADVANCE"))throw new Fail(400,"Chỉ quyết toán tạm ứng");long n=num(b,"amount");amount(n);String d=date(b,"date");if(d.compareTo(str(o,"date"))<0)throw new Fail(400,"Ngày quyết toán trước ngày tạm ứng");long issued=db.queryForObject("SELECT COALESCE(SUM(amount),0) FROM vouchers WHERE deleted=0 AND obligation_id=? AND purpose='ADVANCE_ISSUE' AND date<=?",Long.class,id,d);long returned=num(o,"amount")-outstanding(id,0);if(n>outstanding(id,0)||n+returned>issued)throw new Fail(400,"Quyết toán vượt số còn lại/đã cấp");db.update("INSERT INTO clearings(obligation_id,amount,date,note,created_by) VALUES(?,?,?,?,?)",id,n,d,required(b,"note"),a);audit(a,"CLEAR_ADVANCE","clearings",last(),null,b,"");return Map.of("ok",true);});}
 static String month(String s){try{if(!s.matches("[0-9]{4}-[0-9]{2}"))throw new Exception();return YearMonth.parse(s).toString();}catch(Exception e){throw new Fail(400,"Tháng không hợp lệ");}}
 void attendanceOpen(String m){if(db.queryForObject("SELECT COUNT(*) FROM attendance_months WHERE month=? AND locked=1",Integer.class,m)>0)throw new Fail(409,"Tháng đã khóa. Admin cần mở khóa và ghi lý do trước khi sửa.");}
 @GetMapping("/attendance/{month}") synchronized Map<String,Object> attendance(@PathVariable String month,HttpServletRequest r){auth(r,false);String m=month(month);var locks=db.queryForList("SELECT * FROM attendance_months WHERE month=?",m);return Map.of("month",m,"lock",locks.isEmpty()?Map.of("locked",0,"version",0):locks.get(0),"entries",db.queryForList("SELECT * FROM attendance WHERE substr(date,1,7)=? AND deleted=0 ORDER BY date,employee_id",m),"voided",db.queryForList("SELECT employee_id,date FROM attendance WHERE substr(date,1,7)=? AND deleted=1",m));}
 @PostMapping("/attendance") synchronized Map<String,Object> saveAttendance(@RequestBody Map<String,Object>b,HttpServletRequest r){long a=actor(r);String d=date(b,"date"),m=month(d.substring(0,7));attendanceOpen(m);long employee=num(b,"employee_id");available("contacts",employee);if(!str(one("contacts",employee),"kind").equals("EMPLOYEE"))throw new Fail(400,"Chọn nhân viên để chấm công");String status=choice(str(b,"status"),"WORK","HALF","PAID_LEAVE","UNPAID_LEAVE","OFF");long overtime=num(b,"overtime_minutes");if(overtime<0||overtime>960||overtime%15!=0)throw new Fail(400,"Tăng ca từ 0 đến 16 giờ, theo bước 15 phút");if(overtime>0&&!List.of("WORK","HALF").contains(status))throw new Fail(400,"Chỉ ghi tăng ca vào ngày có đi làm");String note=str(b,"note");if(note.length()>2000)throw new Fail(400,"Ghi chú quá dài");return tx.execute(t->{var rows=db.queryForList("SELECT * FROM attendance WHERE employee_id=? AND date=?",employee,d);var old=rows.isEmpty()?null:rows.get(0);long id=old==null?0:num(old,"id");if(old!=null&&num(old,"deleted")==0&&num(b,"version")!=num(old,"version"))throw new Fail(409,"Công đã thay đổi. Tải lại bảng công.");if((old==null||num(old,"deleted")==1)&&num(b,"version")!=0)throw new Fail(409,"Công đã thay đổi. Tải lại bảng công.");if(old!=null)required(b,"reason");if(old==null){db.update("INSERT INTO attendance(employee_id,date,status,overtime_minutes,note,created_by,updated_by) VALUES(?,?,?,?,?,?,?)",employee,d,status,overtime,note,a,a);id=last();}else db.update("UPDATE attendance SET status=?,overtime_minutes=?,note=?,deleted=0,version=version+1,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=?",status,overtime,note,a,id);var saved=one("attendance",id);audit(a,old==null?"ATTENDANCE_CREATE":"ATTENDANCE_UPDATE","attendance",id,old,saved,str(b,"reason"));return saved;});}
 @DeleteMapping("/attendance/{id}") synchronized Map<String,Object> deleteAttendance(@PathVariable long id,@RequestBody Map<String,Object>b,HttpServletRequest r){long a=actor(r);return tx.execute(t->{var old=one("attendance",id);attendanceOpen(str(old,"date").substring(0,7));if(num(old,"deleted")!=0||num(old,"version")!=num(b,"version"))throw new Fail(409,"Công đã thay đổi. Tải lại bảng công.");required(b,"reason");db.update("UPDATE attendance SET deleted=1,version=version+1,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=?",a,id);audit(a,"ATTENDANCE_VOID","attendance",id,old,one("attendance",id),str(b,"reason"));return Map.of("ok",true);});}
 @PostMapping("/attendance/month") synchronized Map<String,Object> lockAttendance(@RequestBody Map<String,Object>b,HttpServletRequest r){long a=actor(r);String m=month(required(b,"month"));long locked=num(b,"locked");if(locked!=0&&locked!=1)throw new Fail(400,"Trạng thái không hợp lệ");required(b,"reason");return tx.execute(t->{var rows=db.queryForList("SELECT * FROM attendance_months WHERE month=?",m);var old=rows.isEmpty()?null:rows.get(0);if(num(b,"version")!=(old==null?0:num(old,"version")))throw new Fail(409,"Trạng thái tháng đã thay đổi. Tải lại bảng công.");if(old==null)db.update("INSERT INTO attendance_months(month,locked,updated_by) VALUES(?,?,?)",m,locked,a);else db.update("UPDATE attendance_months SET locked=?,version=version+1,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE month=?",locked,a,m);var saved=db.queryForMap("SELECT * FROM attendance_months WHERE month=?",m);audit(a,locked==1?"ATTENDANCE_LOCK":"ATTENDANCE_UNLOCK","attendance_months",0,old,saved,str(b,"reason"));return saved;});}

 @GetMapping("/vouchers") synchronized List<Map<String,Object>> vouchers(HttpServletRequest r){auth(r,false);return db.queryForList("SELECT v.*,f.name fund_name,g.name to_fund_name,c.name contact_name,k.name category_name FROM vouchers v JOIN funds f ON f.id=v.fund_id LEFT JOIN funds g ON g.id=v.to_fund_id LEFT JOIN contacts c ON c.id=v.contact_id LEFT JOIN categories k ON k.id=v.category_id ORDER BY v.date DESC,v.id DESC");}
 @PostMapping("/vouchers") synchronized Map<String,Object> createVoucher(@RequestBody Map<String,Object>b,HttpServletRequest r){long a=actor(r);return tx.execute(t->saveVoucher(0,b,a));}
 @PutMapping("/vouchers/{id}") synchronized Map<String,Object> editVoucher(@PathVariable long id,@RequestBody Map<String,Object>b,HttpServletRequest r){long a=actor(r);return tx.execute(t->saveVoucher(id,b,a));}
 Map<String,Object> saveVoucher(long id,Map<String,Object>b,long a){var old=id==0?null:one("vouchers",id);if(old!=null&&(num(old,"deleted")!=0||num(old,"version")!=num(b,"version")))throw new Fail(409,"Phiếu đã thay đổi. Tải lại màn hình.");if(old!=null)required(b,"reason");String type=choice(str(b,"type"),"RECEIPT","EXPENSE","TRANSFER"),d=date(b,"date"),desc=required(b,"description"),purpose=str(b,"purpose");String receiptGroup=type.equals("RECEIPT")?choice(str(b,"receipt_group").isEmpty()?"OTHER":str(b,"receipt_group"),"DEALER","RETAIL","CAPITAL","BORROWING","OTHER"):"";long n=num(b,"amount"),fee=num(b,"fee"),fund=num(b,"fund_id"),to=num(b,"to_fund_id"),category=num(b,"category_id"),contact=num(b,"contact_id"),ob=num(b,"obligation_id");amount(n);if(fee<0||fee>1000000000000L)throw new Fail(400,"Phí không hợp lệ");available("funds",fund);if(d.compareTo(str(one("funds",fund),"opening_date"))<0)throw new Fail(400,"Ngày phiếu trước số dư đầu kỳ nguồn tiền");if(type.equals("TRANSFER")){if(fund==to)throw new Fail(400,"Nguồn chuyển và nhận phải khác nhau");available("funds",to);if(ob>0||!purpose.isEmpty())throw new Fail(400,"Chuyển quỹ không thanh toán công nợ");if(d.compareTo(str(one("funds",to),"opening_date"))<0)throw new Fail(400,"Ngày phiếu trước số dư đầu kỳ nguồn nhận");}else if(to>0||fee!=0)throw new Fail(400,"Chỉ chuyển quỹ có nguồn nhận và phí");if(category>0){available("categories",category);String ck=str(one("categories",category),"kind");if(!ck.equals("BOTH")&&!ck.equals(type.equals("RECEIPT")?"IN":"OUT"))throw new Fail(400,"Nhóm thu/chi không khớp loại phiếu");}if(contact>0)available("contacts",contact);
  if(ob>0){available("obligations",ob);var o=one("obligations",ob);if(contact!=num(o,"contact_id"))throw new Fail(400,"Đối tác không khớp công nợ");if(d.compareTo(str(o,"date"))<0)throw new Fail(400,"Thanh toán trước ngày ghi nhận công nợ");String kind=str(o,"kind");if(kind.equals("ADVANCE")){if(type.equals("EXPENSE")){choice(purpose,"ADVANCE_ISSUE");long issued=db.queryForObject("SELECT COALESCE(SUM(amount),0) FROM vouchers WHERE deleted=0 AND obligation_id=? AND purpose='ADVANCE_ISSUE' AND id<>?",Long.class,ob,id);if(issued+n>num(o,"amount"))throw new Fail(400,"Cấp ứng vượt số đề nghị");}else{choice(purpose,"ADVANCE_RETURN");if(n>outstanding(ob,id))throw new Fail(400,"Hoàn ứng vượt số còn lại");long issued=db.queryForObject("SELECT COALESCE(SUM(amount),0) FROM vouchers WHERE deleted=0 AND obligation_id=? AND purpose='ADVANCE_ISSUE' AND date<=? AND id<>?",Long.class,ob,d,id);long used=num(o,"amount")-outstanding(ob,id);if(n+used>issued)throw new Fail(400,"Hoàn ứng vượt số đã cấp");}}else if(kind.equals("PAYABLE")&&str(o,"debt_group").equals("LOAN")){if(type.equals("RECEIPT")){choice(purpose,"LOAN_RECEIVE");receiptGroup="BORROWING";long received=db.queryForObject("SELECT COALESCE(SUM(amount),0) FROM vouchers WHERE deleted=0 AND obligation_id=? AND purpose='LOAN_RECEIVE' AND id<>?",Long.class,ob,id);if(received+n>num(o,"amount"))throw new Fail(400,"Tiền vay nhận vượt nợ gốc đã xác nhận");}else{choice(purpose,"LOAN_PRINCIPAL","LOAN_INTEREST");if(purpose.equals("LOAN_PRINCIPAL")&&n>outstanding(ob,id))throw new Fail(400,"Trả gốc vượt nợ gốc còn lại");}}
else{if(kind.equals("RECEIVABLE")&&(old==null||num(old,"obligation_id")!=ob))throw new Fail(400,"Không tạo liên kết công nợ khách hàng mới");if(!purpose.isEmpty())throw new Fail(400,"Mục đích không phù hợp khoản nợ");if(!type.equals(kind.equals("PAYABLE")?"EXPENSE":"RECEIPT"))throw new Fail(400,"Loại phiếu không khớp công nợ");if(n>outstanding(ob,id))throw new Fail(400,"Thanh toán vượt công nợ còn lại");}}
  else if(!purpose.isEmpty())throw new Fail(400,"Chọn khoản tạm ứng để liên kết");
  if(id==0){String prefix=type.equals("RECEIPT")?"PT":type.equals("EXPENSE")?"PC":"CQ";long next=db.queryForObject("SELECT COALESCE(MAX(id),0)+1 FROM vouchers",Long.class);db.update("INSERT INTO vouchers(code,type,date,description,amount,fee,fund_id,to_fund_id,category_id,contact_id,obligation_id,purpose,source_key,source_ref,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",prefix+"-"+String.format("%06d",next),type,d,desc,n,fee,fund,to==0?null:to,category==0?null:category,contact==0?null:contact,ob==0?null:ob,purpose,null,str(b,"source_ref"),a);id=last();}else db.update("UPDATE vouchers SET type=?,date=?,description=?,amount=?,fee=?,fund_id=?,to_fund_id=?,category_id=?,contact_id=?,obligation_id=?,purpose=?,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=?",type,d,desc,n,fee,fund,to==0?null:to,category==0?null:category,contact==0?null:contact,ob==0?null:ob,purpose,id);
  db.update("UPDATE vouchers SET receipt_group=? WHERE id=?",receiptGroup,id);validateAdvances();audit(a,old==null?"CREATE":"UPDATE","vouchers",id,old,one("vouchers",id),str(b,"reason"));return one("vouchers",id);
 }
 void validateAdvances(){for(var o:db.queryForList("SELECT * FROM obligations WHERE deleted=0 AND kind='ADVANCE'")){long id=num(o,"id");long issued=db.queryForObject("SELECT COALESCE(SUM(amount),0) FROM vouchers WHERE deleted=0 AND obligation_id=? AND purpose='ADVANCE_ISSUE'",Long.class,id);long used=num(o,"amount")-outstanding(id,0);if(used>issued||issued>num(o,"amount"))throw new Fail(400,"Thao tác làm số hoàn/quyết toán vượt tạm ứng đã cấp");for(var event:db.queryForList("SELECT date,amount FROM vouchers WHERE deleted=0 AND obligation_id=? AND purpose='ADVANCE_RETURN' UNION ALL SELECT date,amount FROM clearings WHERE obligation_id=?",id,id)){String d=str(event,"date");long issuedAt=db.queryForObject("SELECT COALESCE(SUM(amount),0) FROM vouchers WHERE deleted=0 AND obligation_id=? AND purpose='ADVANCE_ISSUE' AND date<=?",Long.class,id,d);long usedAt=db.queryForObject("SELECT COALESCE(SUM(amount),0) FROM vouchers WHERE deleted=0 AND obligation_id=? AND purpose='ADVANCE_RETURN' AND date<=?",Long.class,id,d)+db.queryForObject("SELECT COALESCE(SUM(amount),0) FROM clearings WHERE obligation_id=? AND date<=?",Long.class,id,d);if(usedAt>issuedAt)throw new Fail(400,"Hoàn/quyết toán trước ngày cấp ứng hoặc vượt số đã cấp");}}}
 @DeleteMapping("/vouchers/{id}") synchronized Map<String,Object> deleteVoucher(@PathVariable long id,@RequestBody Map<String,Object>b,HttpServletRequest r){long a=actor(r);return tx.execute(t->{var old=one("vouchers",id);if(num(old,"deleted")!=0||num(old,"version")!=num(b,"version"))throw new Fail(409,"Phiếu đã thay đổi");required(b,"reason");db.update("UPDATE vouchers SET deleted=1,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=?",id);validateAdvances();audit(a,"VOID","vouchers",id,old,one("vouchers",id),str(b,"reason"));return Map.of("ok",true);});}
 @GetMapping("/report") synchronized Map<String,Object> report(@RequestParam String from,@RequestParam String to,HttpServletRequest r){auth(r,false);LocalDate.parse(from);LocalDate.parse(to);if(from.compareTo(to)>0)throw new Fail(400,"Khoảng ngày không hợp lệ");var funds=db.queryForList("SELECT * FROM funds WHERE deleted=0");for(var f:funds){long id=num(f,"id");String opening=str(f,"opening_date");long base=opening.compareTo(to)<=0?num(f,"opening"):0;f.put("balance",base+movement(id,opening,to));f.put("start",opening.compareTo(from)<0?num(f,"opening")+movement(id,opening,LocalDate.parse(from).minusDays(1).toString()):0);f.put("opening_in_period",opening.compareTo(from)>=0&&opening.compareTo(to)<=0?num(f,"opening"):0);}
  var sums=db.queryForMap("SELECT COALESCE(SUM(CASE WHEN type='RECEIPT' THEN amount ELSE 0 END),0) income,COALESCE(SUM(CASE WHEN type='EXPENSE' THEN amount WHEN type='TRANSFER' THEN fee ELSE 0 END),0) expense FROM vouchers WHERE deleted=0 AND date BETWEEN ? AND ?",from,to);
  var monthly=db.queryForList("SELECT substr(date,1,7) month,SUM(CASE WHEN type='RECEIPT' THEN amount ELSE 0 END) income,SUM(CASE WHEN type='EXPENSE' THEN amount WHEN type='TRANSFER' THEN fee ELSE 0 END) expense FROM vouchers WHERE deleted=0 AND date BETWEEN ? AND ? GROUP BY substr(date,1,7) ORDER BY month",from,to);
  var groups=db.queryForList("SELECT COALESCE(k.name,'Chưa phân loại') name,SUM(CASE WHEN v.type='EXPENSE' THEN v.amount WHEN v.type='TRANSFER' THEN v.fee ELSE 0 END) amount FROM vouchers v LEFT JOIN categories k ON k.id=v.category_id WHERE v.deleted=0 AND v.date BETWEEN ? AND ? GROUP BY k.name HAVING amount>0 ORDER BY amount DESC",from,to);
  return Map.of("funds",funds,"totals",sums,"monthly",monthly,"groups",groups,"obligations",obligations(r),"from",from,"to",to);
 }
 long movement(long id,String from,String to){return db.queryForObject("SELECT COALESCE(SUM(CASE WHEN fund_id=? THEN CASE WHEN type='RECEIPT' THEN amount ELSE -amount-fee END ELSE 0 END + CASE WHEN to_fund_id=? THEN amount ELSE 0 END),0) FROM vouchers WHERE deleted=0 AND date BETWEEN ? AND ?",Long.class,id,id,from,to);}
 Map<String,Object> evidenceMetadata(long id){return db.queryForMap("SELECT id,entity,entity_id,name,mime,bytes,sha256,caption,deleted,version,created_by,created_at FROM evidence WHERE id=?",id);}
 @GetMapping("/evidence/{entity}/{id}") synchronized List<Map<String,Object>> evidenceList(@PathVariable String entity,@PathVariable long id,HttpServletRequest r){auth(r,false);choice(entity,"vouchers","obligations");one(entity,id);return db.queryForList("SELECT id,name,mime,bytes,sha256,caption,deleted,version,created_at FROM evidence WHERE entity=? AND entity_id=? ORDER BY id DESC",entity,id);}
 @GetMapping("/evidence/file/{id}") synchronized Map<String,Object> evidenceFile(@PathVariable long id,HttpServletRequest r){auth(r,false);var meta=evidenceMetadata(id);byte[] content=db.queryForObject("SELECT content FROM evidence WHERE id=?",byte[].class,id);var result=new HashMap<String,Object>(meta);result.put("base64",Base64.getEncoder().encodeToString(content));return result;}
 @PostMapping("/evidence/{entity}/{id}") synchronized Map<String,Object> addEvidence(@PathVariable String entity,@PathVariable long id,@RequestParam MultipartFile file,@RequestParam(defaultValue="") String caption,HttpServletRequest r)throws Exception {long a=actor(r);choice(entity,"vouchers","obligations");available(entity,id);if(file.isEmpty()||file.getSize()>8388608||caption.length()>2000)throw new Fail(400,"Mỗi ảnh/PDF tối đa 8 MB, ghi chú tối đa 2.000 ký tự");byte[] bytes=file.getBytes();String mime="";if(bytes.length>8&&bytes[0]==(byte)137&&bytes[1]==80&&bytes[2]==78&&bytes[3]==71&&bytes[4]==13&&bytes[5]==10&&bytes[6]==26&&bytes[7]==10)mime="image/png";else if(bytes.length>3&&bytes[0]==(byte)255&&bytes[1]==(byte)216&&bytes[2]==(byte)255)mime="image/jpeg";else if(bytes.length>5&&new String(bytes,0,5,java.nio.charset.StandardCharsets.US_ASCII).equals("%PDF-"))mime="application/pdf";if(mime.isEmpty())throw new Fail(400,"Chỉ nhận ảnh PNG/JPEG hoặc PDF hợp lệ");if(!mime.equals("application/pdf")){try(var input=new java.io.ByteArrayInputStream(bytes);var image=javax.imageio.ImageIO.createImageInputStream(input)){var readers=javax.imageio.ImageIO.getImageReaders(image);if(!readers.hasNext())throw new Fail(400,"Ảnh không đọc được");var reader=readers.next();try{reader.setInput(image);if((long)reader.getWidth(0)*reader.getHeight(0)>40000000L)throw new Fail(400,"Ảnh quá lớn; chọn ảnh dưới 40 megapixel");}finally{reader.dispose();}}}
 String hash=HexFormat.of().formatHex(java.security.MessageDigest.getInstance("SHA-256").digest(bytes));if(db.queryForObject("SELECT COUNT(*) FROM evidence WHERE entity=? AND entity_id=? AND sha256=? AND deleted=0",Integer.class,entity,id,hash)>0)throw new Fail(409,"File này đã đính kèm");if(db.queryForObject("SELECT COUNT(*) FROM evidence WHERE entity=? AND entity_id=? AND deleted=0",Integer.class,entity,id)>=20)throw new Fail(400,"Mỗi chứng từ tối đa 20 file");if(db.queryForObject("SELECT COALESCE(SUM(bytes),0) FROM evidence",Long.class)+bytes.length>268435456L)throw new Fail(400,"Ảnh chứng từ đạt giới hạn 256 MB; chọn ảnh đã thu nhỏ");String raw=String.valueOf(file.getOriginalFilename()).replace('\\','/');String name=raw.substring(raw.lastIndexOf('/')+1).replaceAll("[\\p{Cntrl}]","");if(name.length()>150)name=name.substring(0,150);if(name.isBlank())name="chung-tu";final String fn=name,mt=mime;return tx.execute(t->{db.update("INSERT INTO evidence(entity,entity_id,name,mime,bytes,sha256,content,caption,created_by) VALUES(?,?,?,?,?,?,?,?,?)",entity,id,fn,mt,bytes.length,hash,bytes,caption,a);long key=last();var meta=evidenceMetadata(key);audit(a,"EVIDENCE_ADD","evidence",key,null,meta,"");return meta;});}
 @PutMapping("/evidence/{id}") synchronized Map<String,Object> captionEvidence(@PathVariable long id,@RequestBody Map<String,Object>b,HttpServletRequest r){long a=actor(r);return tx.execute(t->{var old=evidenceMetadata(id);available(str(old,"entity"),num(old,"entity_id"));if(num(old,"deleted")!=0||num(old,"version")!=num(b,"version"))throw new Fail(409,"Bằng chứng đã thay đổi");required(b,"reason");String caption=str(b,"caption");if(caption.length()>2000)throw new Fail(400,"Ghi chú quá dài");db.update("UPDATE evidence SET caption=?,version=version+1 WHERE id=?",caption,id);var meta=evidenceMetadata(id);audit(a,"EVIDENCE_CAPTION","evidence",id,old,meta,str(b,"reason"));return meta;});}
 @DeleteMapping("/evidence/{id}") synchronized Map<String,Object> removeEvidence(@PathVariable long id,@RequestBody Map<String,Object>b,HttpServletRequest r){long a=actor(r);return tx.execute(t->{var old=evidenceMetadata(id);available(str(old,"entity"),num(old,"entity_id"));if(num(old,"deleted")!=0||num(old,"version")!=num(b,"version"))throw new Fail(409,"Bằng chứng đã thay đổi");required(b,"reason");db.update("UPDATE evidence SET deleted=1,version=version+1 WHERE id=?",id);audit(a,"EVIDENCE_REMOVE","evidence",id,old,evidenceMetadata(id),str(b,"reason"));return Map.of("ok",true);});}

 @GetMapping("/audit") synchronized List<Map<String,Object>> logs(HttpServletRequest r){auth(r,false);return db.queryForList("SELECT a.*,COALESCE(u.name,'Thiết lập ban đầu') actor_name FROM audit a LEFT JOIN users u ON u.id=a.actor_id ORDER BY a.id DESC");}
 List<Map<String,Object>> loadImportPreview()throws Exception {Path p=Application.DATA.resolve("import-preview.json");return Files.exists(p)?json.readValue(Files.readAllBytes(p),new TypeReference<>(){}):new ArrayList<>();}
 @PostMapping("/import/upload") synchronized Map<String,Object> uploadExcel(@RequestParam MultipartFile file,HttpServletRequest r)throws Exception {long a=actor(r);if(file.isEmpty()||file.getSize()>10*1024*1024||!String.valueOf(file.getOriginalFilename()).toLowerCase().endsWith(".xlsx"))throw new Fail(400,"Chọn file .xlsx không quá 10 MB");List<Map<String,Object>> rows;try(var stream=file.getInputStream()){rows=ExcelImporter.read(stream);}catch(Exception e){throw new Fail(400,"Không đọc được Excel. Kiểm tra cấu trúc ngày, diễn giải, thu, chi, tồn.");}if(rows.isEmpty())throw new Fail(400,"Không tìm thấy bảng thu chi công ty phù hợp");Path target=Application.DATA.resolve("import-preview.json"),temp=Application.DATA.resolve("import-preview.tmp");Files.write(temp,json.writeValueAsBytes(rows));Files.move(temp,target,StandardCopyOption.REPLACE_EXISTING);audit(a,"EXCEL_PREVIEW","import",0,null,Map.of("rows",rows.size()),"");return Map.of("count",rows.size());}
 @GetMapping("/import/preview") synchronized List<Map<String,Object>> preview(HttpServletRequest r)throws Exception {actor(r);List<Map<String,Object>> rows=loadImportPreview();for(var row:rows)row.put("imported",db.queryForObject("SELECT COUNT(*) FROM vouchers WHERE source_key=?",Integer.class,row.get("id"))>0);return rows;}
 @PostMapping("/import/commit") synchronized Map<String,Object> importRows(@RequestBody List<Map<String,Object>>b,HttpServletRequest r)throws Exception {long a=actor(r);if(b.isEmpty()||b.size()>500)throw new Fail(400,"Chọn từ 1 đến 500 dòng");List<Map<String,Object>> source=loadImportPreview();return tx.execute(t->{for(var row:b){var original=source.stream().filter(x->str(x,"id").equals(str(row,"sourceId"))).findFirst().orElseThrow(()->new Fail(400,"Không có dòng nguồn"));List<?> issues=(List<?>)original.get("issues");if(issues.contains("BOTH_IN_AND_OUT")||issues.contains("FORMULA_NO_CACHE")||issues.contains("NO_AMOUNT"))throw new Fail(400,"Dòng có hai chiều/thiếu số tiền cần tách và nhập thủ công");if(db.queryForObject("SELECT COUNT(*) FROM vouchers WHERE source_key=?",Integer.class,original.get("id"))>0)throw new Fail(409,"Dòng đã nhập trước đó");if(num(row,"amount")!=num(original,"amount"))throw new Fail(400,"Số tiền không khớp nguồn Excel");choice(str(row,"type"),"RECEIPT","EXPENSE");var data=new HashMap<String,Object>(row);data.put("description",original.get("description"));data.put("source_ref",original.get("sheet")+"!"+original.get("range"));var saved=saveVoucher(0,data,a);db.update("UPDATE vouchers SET source_key=? WHERE id=?",original.get("id"),saved.get("id"));audit(a,"IMPORT_SOURCE","vouchers",num(saved,"id"),null,Map.of("source",original),"");}return Map.of("count",b.size());});}
 @PostMapping("/backup") synchronized Map<String,Object> backup(HttpServletRequest r)throws Exception {long a=actor(r);Path p=createBackup();audit(a,"BACKUP","database",0,null,Map.of("file",p.getFileName().toString()),"");return Map.of("file",p.getFileName().toString(),"bytes",Files.size(p));}
 Path createBackup()throws Exception {Path dir=Application.DATA.resolve("backups");Files.createDirectories(dir);Path p=dir.resolve("thuchi-"+Instant.now().toEpochMilli()+"-"+UUID.randomUUID().toString().substring(0,6)+".sqlite");db.execute("VACUUM INTO '"+p.toString().replace("'","''")+"'");return p;}
 @GetMapping("/backups") synchronized List<Map<String,Object>> backups(HttpServletRequest r)throws Exception {actor(r);Path dir=Application.DATA.resolve("backups");if(!Files.exists(dir))return List.of();try(var files=Files.list(dir)){return files.filter(p->p.getFileName().toString().endsWith(".sqlite")).sorted(Comparator.reverseOrder()).map(p->{try{return Map.<String,Object>of("file",p.getFileName().toString(),"bytes",Files.size(p));}catch(Exception e){throw new RuntimeException(e);}}).toList();}}
 @GetMapping("/backups/{name}") synchronized ResponseEntity<byte[]> download(@PathVariable String name,HttpServletRequest r)throws Exception {actor(r);if(!name.matches("thuchi-[0-9]+-[a-f0-9]{6}\\.sqlite"))throw new Fail(400,"Tên sao lưu không hợp lệ");Path p=Application.DATA.resolve("backups").resolve(name);return ResponseEntity.ok().contentType(MediaType.APPLICATION_OCTET_STREAM).body(Files.readAllBytes(p));}
 @PostMapping(value="/restore",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) synchronized Map<String,Object> restore(@RequestParam("file")MultipartFile file,@RequestParam("password")String password,HttpServletRequest r)throws Exception {long a=actor(r);String key="restore:"+a;throttle(key);if(!encoder.matches(password,str(one("users",a),"password_hash"))){bad(key);throw new Fail(400,"Mật khẩu không đúng");}Path temp=Application.DATA.resolve("restore-"+UUID.randomUUID()+".sqlite");file.transferTo(temp);try{validateRestore(temp);try(Connection c=DriverManager.getConnection("jdbc:sqlite:"+temp)){DatabaseUpgrade.upgrade(c);}validateRestore(temp);Path safety=createBackup();Path current=Application.DATA.resolve("thuchi.sqlite");try{Files.move(temp,current,StandardCopyOption.REPLACE_EXISTING);}catch(Exception e){Files.copy(safety,current,StandardCopyOption.REPLACE_EXISTING);throw e;}sessions.clear();audit(0,"RESTORE","database",0,null,Map.of("safetyBackup",safety.getFileName().toString()),"Khôi phục dữ liệu. Phiên đăng nhập đã thu hồi.");attempts.remove(key);return Map.of("ok",true,"safetyBackup",safety.getFileName().toString());}finally{Files.deleteIfExists(temp);}}
 void validateRestore(Path p)throws Exception {var config=new org.sqlite.SQLiteConfig();config.setReadOnly(true);try(Connection c=DriverManager.getConnection("jdbc:sqlite:"+p,config.toProperties());Statement s=c.createStatement()){try(ResultSet rs=s.executeQuery("PRAGMA integrity_check")){if(!rs.next()||!rs.getString(1).equals("ok"))throw new Fail(400,"Sao lưu không toàn vẹn");}try(ResultSet rs=s.executeQuery("PRAGMA user_version")){if(!rs.next()||!List.of(1,2,3).contains(rs.getInt(1)))throw new Fail(400,"Phiên bản sao lưu không phù hợp");}int schema;try(var rs=s.executeQuery("PRAGMA user_version")){if(!rs.next())throw new Fail(400,"Thiếu phiên bản dữ liệu");schema=rs.getInt(1);}if(schema>=2){for(String q:List.of("SELECT bank_name,account_number,account_holder FROM funds LIMIT 0","SELECT attendance_code FROM contacts LIMIT 0","SELECT id,employee_id,date,status,overtime_minutes,note,source,device_record_key,created_by,updated_by,deleted,version,updated_at FROM attendance LIMIT 0","SELECT month,locked,version,updated_by,updated_at FROM attendance_months LIMIT 0"))try(var rs=s.executeQuery(q)){} }
if(schema==3){for(String q:List.of("SELECT customer_type,party_type,address FROM contacts LIMIT 0","SELECT debt_group FROM obligations LIMIT 0","SELECT receipt_group FROM vouchers LIMIT 0","SELECT id,entity,entity_id,name,mime,bytes,sha256,content,caption,deleted,version,created_by,created_at FROM evidence LIMIT 0"))try(var rs=s.executeQuery(q)){}try(var rs=s.executeQuery("SELECT COUNT(*) FROM evidence e WHERE (e.entity='vouchers' AND NOT EXISTS(SELECT 1 FROM vouchers WHERE id=e.entity_id)) OR (e.entity='obligations' AND NOT EXISTS(SELECT 1 FROM obligations WHERE id=e.entity_id)) OR length(e.content)<>e.bytes")){if(!rs.next()||rs.getInt(1)>0)throw new Fail(400,"Sao lưu lỗi bằng chứng");}try(var rs=s.executeQuery("SELECT COUNT(*) FROM sqlite_master WHERE type='trigger' AND name IN ('evidence_no_delete','evidence_content_immutable')")){if(!rs.next()||rs.getInt(1)!=2)throw new Fail(400,"Sao lưu thiếu bảo vệ bằng chứng");}}
var columns=Map.of("users","id,username,name,password_hash,recovery_hash,role,active,created_at","funds","id,name,kind,opening,opening_date,note,deleted,version","categories","id,name,kind,note,deleted,version","contacts","id,name,kind,phone,note,deleted,version","obligations","id,code,kind,contact_id,description,amount,date,due_date,deleted,version","vouchers","id,code,type,date,description,amount,fee,fund_id,to_fund_id,category_id,contact_id,obligation_id,purpose,source_key,source_ref,deleted,version,created_by,updated_at","clearings","id,obligation_id,amount,date,note,created_by","audit","id,actor_id,action,entity,entity_id,before_json,after_json,reason,at");for(var entry:columns.entrySet()){try(ResultSet rs=s.executeQuery("SELECT "+entry.getValue()+" FROM "+entry.getKey()+" LIMIT 0")){} }try(ResultSet rs=s.executeQuery("PRAGMA foreign_key_check")){if(rs.next())throw new Fail(400,"Sao lưu lỗi liên kết dữ liệu");}try(ResultSet rs=s.executeQuery("SELECT COUNT(*) FROM users WHERE active=1 AND role='ADMIN'")){if(!rs.next()||rs.getInt(1)<1)throw new Fail(400,"Sao lưu phải có Admin hoạt động");}try(ResultSet rs=s.executeQuery("SELECT COUNT(*) FROM sqlite_master WHERE type='trigger' AND name IN ('audit_no_update','audit_no_delete')")){if(!rs.next()||rs.getInt(1)!=2)throw new Fail(400,"Sao lưu thiếu bảo vệ nhật ký");}}}
}
