package vn.vinhkhang.thuchi;
import java.util.*;
import org.springframework.web.bind.annotation.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;
@RestController @RequestMapping("/api/database-reset")
public class DatabaseReset {
 private final Map<Long,long[]> failures=new HashMap<>();
 private void verifyPassword(long user,String password,String hash){long now=System.currentTimeMillis();long[] attempt=failures.get(user);if(attempt!=null&&attempt[0]>=5&&now<attempt[1])throw problem(429,"Nhập sai mật khẩu nhiều lần. Anh thử lại sau 5 phút.");if(!new org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder().matches(password,hash)){long count=attempt==null||now>=attempt[1]?1:attempt[0]+1;failures.put(user,new long[]{count,now+300000});throw problem(400,"Mật khẩu Admin không đúng");}failures.remove(user);}
 private final Api core;private final JdbcTemplate db;private final TransactionTemplate tx;
 
 public DatabaseReset(Api core,JdbcTemplate db,PlatformTransactionManager manager){this.core=core;this.db=db;tx=new TransactionTemplate(manager);group("finance","Phiếu thu, phiếu chi, chuyển quỹ","vouchers");group("debt","Công nợ và tạm ứng lương","clearings,supplier_adjustments,obligations");group("funds","Nguồn tiền và số dư đầu kỳ","funds");group("contacts","Khách hàng, đối tác, nhân viên, người góp vốn","contacts");group("categories","Danh mục thu chi","categories");group("attendance","Chấm công và khóa tháng","attendance,attendance_months");group("sync","Kết nối và đối chiếu app Kho","warehouse_links,warehouse_suppliers,warehouse_sources");group("evidence","Ảnh và PDF bằng chứng","evidence");group("users","Tài khoản và mã khôi phục","users");group("audit","Nhật ký hoạt động","audit");}
 private Api.Fail problem(int status,String message){return new Api.Fail(status,message);}
 @ExceptionHandler(Api.Fail.class) public org.springframework.http.ResponseEntity<?> fail(Api.Fail e){return org.springframework.http.ResponseEntity.status(e.status).body(Map.of("error",e.getMessage()));}
 
 private final LinkedHashMap<String,List<String>> groups=new LinkedHashMap<>();
 private final LinkedHashMap<String,String> labels=new LinkedHashMap<>();
 private void group(String key,String label,String tables){groups.put(key,List.of(tables.split(",")));labels.put(key,label);}
 private Set<String> all(){Set<String>s=new LinkedHashSet<>();groups.values().forEach(s::addAll);return s;}
 private Map<String,Set<String>> dependencies(){return db.execute((org.springframework.jdbc.core.ConnectionCallback<Map<String,Set<String>>>)c->{var out=new LinkedHashMap<String,Set<String>>();for(String child:all()){var parents=new HashSet<String>();try(var stmt=c.createStatement();var rs=stmt.executeQuery("PRAGMA foreign_key_list("+child+")")){while(rs.next()){String p=rs.getString("table");if(!p.equals(child)&&all().contains(p))parents.add(p);}} out.put(child,parents);}return out;});}
 private Set<String> plan(Map<String,Object>b){Object raw=b.get("groups");if(!(raw instanceof List<?> list)||list.isEmpty())throw problem(400,"Chọn ít nhất một mục cần xóa");var out=new LinkedHashSet<String>();for(Object key:list){var tables=groups.get(key.toString());if(tables==null)throw problem(400,"Mục xóa không hợp lệ");out.addAll(tables);}var deps=dependencies();boolean changed;do{int size=out.size();for(var e:deps.entrySet())if(e.getValue().stream().anyMatch(out::contains))out.add(e.getKey());if(out.contains("vouchers")||out.contains("obligations")){out.add("evidence");out.add("audit");}if(out.contains("supplier_adjustments")||out.contains("obligations"))out.addAll(groups.get("sync")); changed=out.size()!=size;}while(changed);return out;}
 private List<String> order(Set<String> tables){var deps=dependencies();var left=new LinkedHashSet<>(tables);var ordered=new ArrayList<String>();while(!left.isEmpty()){String next=left.stream().filter(parent->left.stream().noneMatch(child->!child.equals(parent)&&deps.get(child).contains(parent))).findFirst().orElseThrow(()->problem(400,"Không thể xác định thứ tự xóa dữ liệu liên quan"));ordered.add(next);left.remove(next);}return ordered;}
 private String primaryOrder(String table){return db.execute((org.springframework.jdbc.core.ConnectionCallback<String>)c->{var columns=new TreeMap<Integer,String>();try(var rs=c.getMetaData().getPrimaryKeys(null,null,table)){while(rs.next())columns.put(rs.getInt("KEY_SEQ"),rs.getString("COLUMN_NAME"));}return columns.isEmpty()?"":" ORDER BY "+String.join(",",columns.values());});}
 private String fingerprint(Set<String> tables){try{var digest=java.security.MessageDigest.getInstance("SHA-256");for(String table:new TreeSet<>(tables)){digest.update(table.getBytes(java.nio.charset.StandardCharsets.UTF_8));db.query("SELECT * FROM "+table+primaryOrder(table),(org.springframework.jdbc.core.RowCallbackHandler)rs->{try{var row=new java.io.ByteArrayOutputStream();var data=new java.io.DataOutputStream(row);for(int i=1;i<=rs.getMetaData().getColumnCount();i++){Object value=rs.getObject(i);byte[] bytes=value==null?new byte[0]:value instanceof byte[] a?a:rs.getString(i).getBytes(java.nio.charset.StandardCharsets.UTF_8);data.writeBoolean(value!=null);data.writeInt(bytes.length);data.write(bytes);}digest.update(row.toByteArray());}catch(java.io.IOException e){throw new IllegalStateException(e);}});}return java.util.HexFormat.of().formatHex(digest.digest());}catch(java.security.NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
 private Map<String,Object> describe(Set<String> tables){var rows=new ArrayList<Map<String,Object>>();for(var e:groups.entrySet()){long count=0;var included=new ArrayList<String>();for(String table:e.getValue())if(tables.contains(table)){count+=db.queryForObject("SELECT COUNT(*) FROM "+table,Long.class);included.add(table);}if(!included.isEmpty())rows.add(Map.of("label",labels.get(e.getKey()),"count",count,"tables",included));}return Map.of("affected",rows,"fingerprint",fingerprint(tables),"accounts",tables.contains("users"));}

 @GetMapping public synchronized Object catalog(jakarta.servlet.http.HttpServletRequest request){core.actor(request);return groups.entrySet().stream().map(e->Map.of("key",e.getKey(),"label",labels.get(e.getKey()))).toList();}
 @PostMapping("/preview") public synchronized Object preview(jakarta.servlet.http.HttpServletRequest request,@RequestBody Map<String,Object>body){core.actor(request);return describe(plan(body));}
 @PostMapping("/execute") public synchronized Object execute(jakarta.servlet.http.HttpServletRequest request,@RequestBody Map<String,Object>body)throws Exception{long actor=core.actor(request);String hash=db.queryForObject("SELECT password_hash FROM users WHERE id=?",String.class,actor);
 verifyPassword(actor,Objects.toString(body.get("password"),""),hash);
 if(Objects.toString(body.get("reason"),"").trim().isEmpty()||Objects.toString(body.get("reason"),"").length()>400)throw problem(400,"Nhập lý do xóa, tối đa 400 ký tự");
 if(!"XOA DU LIEU".equals(body.get("confirmation")))throw problem(400,"Nhập XOA DU LIEU để xác nhận");
 var tables=plan(body);if(!fingerprint(tables).equals(body.get("fingerprint")))throw problem(409,"Dữ liệu đã thay đổi. Anh xem lại danh sách trước khi xóa.");var backup=core.createBackup();if(java.nio.file.Files.size(backup)==0)throw new java.io.IOException();tx.executeWithoutResult(t->{db.execute("PRAGMA secure_delete=ON");db.update("UPDATE deletion_control SET enabled=1 WHERE id=1");try{for(String table:order(tables))db.update("DELETE FROM "+table);}finally{db.update("UPDATE deletion_control SET enabled=0 WHERE id=1");}core.audit(tables.contains("users")?0:actor,"RESET_SELECTED_DATA","database",0,null,Map.of("groups",body.get("groups")),Objects.toString(body.get("reason"),"Xóa dữ liệu đã chọn"));});if(tables.contains("users")){core.sessions.clear();core.attempts.clear();}return Map.of("ok",true,"backup",backup.toString(),"accounts",tables.contains("users"));
 }
}
