package vn.vinhkhang.thuchi;
import org.springframework.web.bind.annotation.*;import jakarta.servlet.http.HttpServletRequest;
import java.util.*;import java.nio.file.*;import java.time.*;
@RestController @RequestMapping("/api")
public class Extensions {
 final Api api;Extensions(Api api){this.api=api;} @ExceptionHandler(Api.Fail.class) org.springframework.http.ResponseEntity<?> fail(Api.Fail f){return api.fail(f);} @ExceptionHandler(Exception.class) org.springframework.http.ResponseEntity<?> other(Exception e){return api.other(e);}
 static final List<String> TABLES=List.of("vouchers","obligations","funds","contacts","categories","attendance","clearings","evidence");
 @GetMapping("/trash") synchronized List<Map<String,Object>> trash(HttpServletRequest r){api.auth(r,false);var rows=new ArrayList<Map<String,Object>>();for(String table:TABLES){for(var row:api.db.queryForList("SELECT "+(table.equals("evidence")?"id,entity,entity_id,name,mime,bytes,caption,deleted,version,created_at":"*")+" FROM "+table+" WHERE deleted=1 ORDER BY id DESC")){row.remove("content");row.put("table",table);var dates=api.db.queryForList("SELECT at FROM audit WHERE entity=? AND entity_id=? AND action IN ('DELETE','VOID','ATTENDANCE_VOID','EVIDENCE_REMOVE') ORDER BY id DESC LIMIT 1",table,row.get("id"));row.put("deleted_at",dates.isEmpty()?"":dates.getFirst().get("at"));rows.add(row);}}return rows;}
 @GetMapping("/clearings") synchronized List<Map<String,Object>> clearings(HttpServletRequest r){api.auth(r,false);return api.db.queryForList("SELECT * FROM clearings WHERE deleted=0 ORDER BY date DESC,id DESC");}
 @DeleteMapping("/clearings/{id}") synchronized Map<String,Object> deleteClearing(@PathVariable long id,@RequestBody Map<String,Object>b,HttpServletRequest r){long actor=api.actor(r);return api.tx.execute(tx->{var row=api.one("clearings",id);if(Api.num(row,"deleted")!=0||Api.num(row,"version")!=Api.num(b,"version"))throw new Api.Fail(409,"Khoản khấu trừ đã thay đổi");String reason=Api.required(b,"reason");api.db.update("UPDATE clearings SET deleted=1,version=version+1 WHERE id=?",id);api.audit(actor,"DELETE","clearings",id,row,api.one("clearings",id),reason);return Map.of("ok",true);});}
 List<Map<String,Object>> items(Map<String,Object>b){Object raw=b.get("items");if(!(raw instanceof List<?> list)||list.isEmpty()||list.size()>200)throw new Api.Fail(400,"Chọn từ 1 đến 200 mục");var out=new ArrayList<Map<String,Object>>();var seen=new HashSet<String>();for(Object o:list){if(!(o instanceof Map<?,?> m))throw new Api.Fail(400,"Mục không hợp lệ");String table=Objects.toString(m.get("table"),"");if(!TABLES.contains(table))throw new Api.Fail(400,"Loại không hợp lệ");long id=Long.parseLong(m.get("id").toString());if(!seen.add(table+":"+id))throw new Api.Fail(400,"Mục bị trùng");var row=api.one(table,id);if(Api.num(row,"deleted")!=1||Api.num(row,"version")!=Long.parseLong(m.get("version").toString()))throw new Api.Fail(409,"Mục đã thay đổi. Làm mới danh sách.");row.put("table",table);out.add(row);}return out;}
 @PostMapping("/trash/restore") synchronized Map<String,Object> restore(@RequestBody Map<String,Object>b,HttpServletRequest r){long actor=api.actor(r);String reason=Api.required(b,"reason");return api.tx.execute(tx->{var rows=items(b);rows.sort(Comparator.comparingInt(x->List.of("funds","contacts","categories","obligations","vouchers","attendance","clearings","evidence").indexOf(x.get("table"))));for(var row:rows){String table=row.get("table").toString();long id=Api.num(row,"id");row.put("reason",reason);
 if(table.equals("attendance")){api.saveAttendance(row,r);continue;}if(table.equals("clearings")){api.available("obligations",Api.num(row,"obligation_id"));}
 if(table.equals("evidence")){api.available(row.get("entity").toString(),Api.num(row,"entity_id"));if(api.db.queryForObject("SELECT COUNT(*) FROM evidence WHERE entity=? AND entity_id=? AND deleted=0",Integer.class,row.get("entity"),row.get("entity_id"))>=20)throw new Api.Fail(400,"Chứng từ đã có 20 bằng chứng");}
 api.db.update("UPDATE "+table+" SET deleted=0 WHERE id=?",id);
 if(table.equals("vouchers"))api.saveVoucher(id,row,actor);else if(table.equals("obligations"))api.saveObligation(id,row,actor);else if(List.of("funds","contacts","categories").contains(table))api.saveMaster(table,id,row,actor);else api.db.update("UPDATE "+table+" SET version=version+1 WHERE id=?",id);
 api.audit(actor,"RESTORE_ITEM",table,id,null,Map.of("id",id),reason);
 }api.validateAdvances();return Map.of("ok",true,"count",rows.size());});}
 @PostMapping("/trash/purge") synchronized Map<String,Object> purge(@RequestBody Map<String,Object>b,HttpServletRequest r){long actor=api.actor(r);String reason=Api.required(b,"reason");if(!Boolean.TRUE.equals(b.get("confirmed")))throw new Api.Fail(400,"Cần xác nhận xóa hẳn");return api.tx.execute(tx->{var rows=items(b);rows.sort(Comparator.comparingInt(x->List.of("evidence","vouchers","attendance","clearings","obligations","funds","categories","contacts").indexOf(x.get("table"))));api.db.execute("PRAGMA secure_delete=ON");api.db.update("UPDATE deletion_control SET enabled=1 WHERE id=1");try{for(var row:rows){String table=row.get("table").toString();long id=Api.num(row,"id");int refs=0;
 if(table.equals("obligations"))refs=api.db.queryForObject("SELECT COUNT(*) FROM vouchers WHERE obligation_id=?",Integer.class,id)+api.db.queryForObject("SELECT COUNT(*) FROM clearings WHERE obligation_id=?",Integer.class,id);
 if(table.equals("funds"))refs=api.db.queryForObject("SELECT COUNT(*) FROM vouchers WHERE fund_id=? OR to_fund_id=?",Integer.class,id,id);
 if(table.equals("categories"))refs=api.db.queryForObject("SELECT COUNT(*) FROM vouchers WHERE category_id=?",Integer.class,id);
 if(table.equals("contacts"))refs=api.db.queryForObject("SELECT COUNT(*) FROM vouchers WHERE contact_id=?",Integer.class,id)+api.db.queryForObject("SELECT COUNT(*) FROM obligations WHERE contact_id=?",Integer.class,id)+api.db.queryForObject("SELECT COUNT(*) FROM attendance WHERE employee_id=?",Integer.class,id);
 if(refs>0)throw new Api.Fail(400,"Mục "+Objects.toString(row.get("code"),Objects.toString(row.get("name"),String.valueOf(id)))+" còn chứng từ liên kết. Xử lý/xóa hẳn chứng từ liên kết trước.");
 if(table.equals("vouchers")||table.equals("obligations")){var evidence=api.db.queryForList("SELECT id FROM evidence WHERE entity=? AND entity_id=?",table,id);for(var e:evidence)api.db.update("DELETE FROM audit WHERE entity='evidence' AND entity_id=?",e.get("id"));api.db.update("DELETE FROM evidence WHERE entity=? AND entity_id=?",table,id);}
 if(table.equals("obligations"))api.db.update("UPDATE warehouse_links SET obligation_id=NULL,state='PURGED',snapshot_json='{}' WHERE obligation_id=?",id);
 if(table.equals("contacts"))api.db.update("DELETE FROM warehouse_suppliers WHERE contact_id=?",id);api.db.update("DELETE FROM audit WHERE entity=? AND entity_id=?",table,id);api.db.update("DELETE FROM "+table+" WHERE id=?",id);api.audit(actor,"PURGE",table,id,null,Map.of("id",id),reason);
 }}finally{api.db.update("UPDATE deletion_control SET enabled=0 WHERE id=1");}api.validateAdvances();return Map.of("ok",true,"count",rows.size());});}
 Map<String,Object> read(Path p)throws Exception {if(!Files.isRegularFile(p)||Files.size(p)>50*1024*1024)throw new Api.Fail(400,"Không tìm thấy dữ liệu kết nối kho hợp lệ");var v=api.json.readValue(Files.readAllBytes(p),new com.fasterxml.jackson.core.type.TypeReference<Map<String,Object>>(){});if(!"VK-WAREHOUSE-FINANCE-1".equals(v.get("format")))throw new Api.Fail(400,"Chọn file finance-sync.json do app Kho tạo");String source=Api.required(v,"source_id");try{UUID.fromString(source);}catch(Exception e){throw new Api.Fail(400,"Mã nguồn kho không hợp lệ");}if(!(v.get("documents") instanceof List<?>))throw new Api.Fail(400,"Dữ liệu kho thiếu phiếu nhập");return v;}
 @GetMapping("/warehouse/status") synchronized Map<String,Object> warehouseStatus(HttpServletRequest r){api.actor(r);var sources=api.db.queryForList("SELECT * FROM warehouse_sources");var issues=api.db.queryForList("SELECT document_id,state,obligation_id,snapshot_json FROM warehouse_links WHERE state<>'SYNCED'");return Map.of("sources",sources,"issues",issues);}
 @PostMapping("/warehouse/connect") synchronized Map<String,Object> connect(@RequestBody Map<String,Object>b,HttpServletRequest r)throws Exception {long actor=api.actor(r);Path p=Path.of(Api.required(b,"path")).toAbsolutePath().normalize();var snapshot=read(p);String source=Api.str(snapshot,"source_id");return api.tx.execute(tx->{api.db.update("INSERT INTO warehouse_sources(id,path,last_sync) VALUES(?,?,'') ON CONFLICT(id) DO UPDATE SET path=excluded.path",source,p.toString());api.audit(actor,"CONNECT_WAREHOUSE","warehouse",0,null,Map.of("source",source),"");return Map.of("source",source,"path",p.toString(),"documents",((List<?>)snapshot.get("documents")).size());});}
 @PostMapping("/warehouse/sync") synchronized Map<String,Object> sync(@RequestBody Map<String,Object>b,HttpServletRequest r)throws Exception {long actor=api.actor(r);String source=Api.required(b,"source");var config=api.db.queryForList("SELECT * FROM warehouse_sources WHERE id=?",source);if(config.isEmpty())throw new Api.Fail(400,"Kết nối app Kho trước");var snapshot=read(Path.of(config.getFirst().get("path").toString()));if(!source.equals(snapshot.get("source_id")))throw new Api.Fail(409,"Nguồn kho đã thay đổi. Kết nối lại để kiểm tra.");return api.tx.execute(tx->{int created=0,unchanged=0,issues=0,skipped=0;var seen=new HashSet<String>();for(Object object:(List<?>)snapshot.get("documents")){@SuppressWarnings("unchecked") var d=(Map<String,Object>)object;String doc=Api.required(d,"id");if(!seen.add(doc))throw new Api.Fail(400,"Phiếu kho bị trùng");String text;try{text=api.json.writeValueAsString(d);}catch(Exception e){throw new Api.Fail(400,"Dữ liệu kho không hợp lệ");}var links=api.db.queryForList("SELECT * FROM warehouse_links WHERE source_id=? AND document_id=?",source,doc);boolean posted="POSTED".equals(d.get("status"))&&!Boolean.TRUE.equals(d.get("deleted"));
 if(!links.isEmpty()){var link=links.getFirst();if(link.get("state").equals("PURGED")){unchanged++;continue;}if(!posted||!text.equals(link.get("snapshot_json"))){api.db.update("UPDATE warehouse_links SET state=? WHERE source_id=? AND document_id=?",posted?"CHANGED":"CANCELLED",source,doc);issues++;}else{api.db.update("UPDATE warehouse_links SET state='SYNCED' WHERE source_id=? AND document_id=?",source,doc);unchanged++;}continue;}
 long amount=Api.num(d,"amount");if(!posted||!Boolean.TRUE.equals(d.get("priced"))||amount<=0||Api.str(d,"supplier_id").isEmpty()||Api.str(d,"supplier_name").isEmpty()){skipped++;continue;}Api.amount(amount);String supplier=Api.required(d,"supplier_id");long contact;var contacts=api.db.queryForList("SELECT contact_id FROM warehouse_suppliers WHERE source_id=? AND supplier_id=?",source,supplier);
 if(contacts.isEmpty()){var matching=api.db.queryForList("SELECT id FROM contacts WHERE kind='SUPPLIER' AND party_type='SUPPLIER' AND deleted=0 AND name=? COLLATE NOCASE",Api.str(d,"supplier_name"));if(matching.size()==1)contact=((Number)matching.getFirst().get("id")).longValue();else contact=Api.num(api.saveMaster("contacts",0,Map.of("kind","SUPPLIER","party_type","SUPPLIER","name",Api.required(d,"supplier_name"),"phone",Api.str(d,"phone"),"address",Api.str(d,"address"),"note","Đồng bộ từ kho · "+Api.str(d,"supplier_code")),actor),"id");api.db.update("INSERT INTO warehouse_suppliers VALUES(?,?,?)",source,supplier,contact);}else{contact=((Number)contacts.getFirst().get("contact_id")).longValue();api.available("contacts",contact);}
 var obligation=api.saveObligation(0,Map.of("kind","PAYABLE","debt_group","SUPPLIER","contact_id",contact,"amount",amount,"date",Api.required(d,"date"),"description","Nhập linh kiện từ kho · "+Api.required(d,"code")+" · "+Api.str(d,"note")),actor);api.db.update("INSERT INTO warehouse_links(source_id,document_id,obligation_id,supplier_id,snapshot_json) VALUES(?,?,?,?,?)",source,doc,obligation.get("id"),supplier,text);created++;
 }for(var link:api.db.queryForList("SELECT document_id FROM warehouse_links WHERE source_id=? AND state<>'PURGED'",source))if(!seen.contains(link.get("document_id").toString())){api.db.update("UPDATE warehouse_links SET state='MISSING' WHERE source_id=? AND document_id=?",source,link.get("document_id"));issues++;}
 api.db.update("UPDATE warehouse_sources SET last_sync=? WHERE id=?",Instant.now().toString(),source);Map<String,Object> summary=Map.of("created",created,"unchanged",unchanged,"issues",issues,"skipped",skipped,"generated_at",Api.str(snapshot,"generated_at"));api.audit(actor,"SYNC_WAREHOUSE","warehouse",0,null,summary,"");return summary;});}
 @GetMapping("/warehouse/documents") synchronized List<Map<String,Object>> warehouseDocuments(HttpServletRequest r){api.auth(r,false);return api.db.queryForList("SELECT * FROM warehouse_links ORDER BY rowid DESC");}
}
