import {MonthInput,fmtDate} from './Dates.jsx';
import React,{useEffect,useRef,useState} from 'react';
const states={WORK:'Đi làm',HALF:'Nửa ngày',PAID_LEAVE:'Nghỉ phép',UNPAID_LEAVE:'Nghỉ không lương',OFF:'Nghỉ'};
const marks={WORK:'X',HALF:'½',PAID_LEAVE:'P',UNPAID_LEAVE:'KL',OFF:'N'};
const initialMonth=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit'}).format(new Date()).slice(0,7);
export default function Attendance({api,employees,admin,exportRows}){
 const [month,setMonth]=useState(initialMonth),[data,setData]=useState({entries:[],lock:{locked:0,version:0}}),[search,setSearch]=useState(''),[editor,setEditor]=useState(null),[lockForm,setLockForm]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');const generation=useRef(0);
 async function load(m=month){const n=++generation.current;try{const result=await api('/attendance/'+m);if(n===generation.current){setData(result);setError('');}}catch(e){if(n===generation.current)setError(e.message);}}
 useEffect(()=>{setEditor(null);setLockForm(null);setData({entries:[],lock:{locked:0,version:0}});if(/^\d{4}-\d{2}$/.test(month))load(month);return()=>{generation.current++;};},[month]);
 const days=/^\d{4}-\d{2}$/.test(month)?new Date(Number(month.slice(0,4)),Number(month.slice(5)),0).getDate():0;
 const visible=employees.filter(e=>(e.name+' '+e.attendance_code).toLocaleLowerCase('vi').includes(search.toLocaleLowerCase('vi')));
 const entry=(id,d)=>data.entries.find(e=>e.employee_id===id&&e.date===d);
 const totals=id=>data.entries.filter(e=>e.employee_id===id).reduce((s,e)=>({work:s.work+(e.status==='WORK'?1:e.status==='HALF'?.5:0),leave:s.leave+(e.status==='PAID_LEAVE'?1:0),unpaid:s.unpaid+(e.status==='UNPAID_LEAVE'?1:0),ot:s.ot+e.overtime_minutes/60,count:s.count+1}),{work:0,leave:0,unpaid:0,ot:0,count:0});
 function open(e,d){const saved=entry(e.id,d);setError('');setEditor({...saved,employee_id:e.id,name:e.name,date:d,status:saved?.status||'WORK',hours:(saved?.overtime_minutes||0)/60,note:saved?.note||'',reason:'',has_history:!!data.voided?.some(v=>v.employee_id===e.id&&v.date===d),version:saved?.version||0});}
 async function run(fn){setBusy(true);setError('');try{await fn();await load();setMessage('Đã lưu bảng công');}catch(e){setError(e.message);}finally{setBusy(false);}}
 const exportMonth=()=>run(()=>exportRows([['Nhân viên','Mã chấm công',...Array.from({length:days},(_,i)=>String(i+1)),'Công đi làm','Ngày phép','Nghỉ không lương','Tăng ca (giờ)','Ngày đã chấm'],...visible.map(e=>{const t=totals(e.id);return [e.name,e.attendance_code,...Array.from({length:days},(_,i)=>{const r=entry(e.id,month+'-'+String(i+1).padStart(2,'0'));return r?states[r.status]+(r.overtime_minutes?' + '+r.overtime_minutes/60+'h TC':''):'';}),t.work,t.leave,t.unpaid,t.ot,t.count];})],'cham-cong-'+month+'.csv'));
 const change=(k,v)=>setEditor(e=>({...e,[k]:v}));
 return <><div className="notice"><strong>Chấm công thủ công</strong><p>Chọn ô ngày để ghi công. X: đi làm · ½: nửa ngày · P: nghỉ phép · KL: nghỉ không lương · N: nghỉ. Ô trống là chưa chấm. Công và phép được tổng hợp riêng; bảng công chưa làm giảm nguồn tiền.</p></div><div className="toolbar"><MonthInput aria-label="Tháng chấm công" value={month} disabled={busy} onChange={setMonth}/><input aria-label="Tìm nhân viên" placeholder="Tìm tên hoặc mã chấm công…" value={search} onChange={e=>setSearch(e.target.value)}/><button disabled={busy} onClick={()=>run(()=>load())}>Làm mới bảng công</button><button disabled={busy||!days} onClick={exportMonth}>Xuất bảng công CSV</button>{admin&&<button disabled={busy||!days} onClick={()=>{setError('');setLockForm({locked:data.lock.locked?0:1,reason:''});}}>{data.lock.locked?'Mở khóa tháng':'Chốt và khóa tháng'}</button>}<span className={'badge '+(data.lock.locked?'gray':'blue')}>{data.lock.locked?'Đã khóa':'Đang nhập công'}</span></div>{error&&<p className="error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}<section className="card flush"><div className="table-wrap attendance-wrap"><table className="attendance-table"><thead><tr><th>Nhân viên</th>{Array.from({length:days},(_,i)=><th key={i}>{i+1}</th>)}<th>Công</th><th>Phép</th><th>KL</th><th>Tăng ca (h)</th><th>Đã chấm</th></tr></thead><tbody>{visible.map(e=>{const t=totals(e.id);return <tr key={e.id}><th>{e.name}<small>{e.attendance_code||'Chưa có mã chấm công'}</small></th>{Array.from({length:days},(_,i)=>{const date=month+'-'+String(i+1).padStart(2,'0'),r=entry(e.id,date);return <td key={date}><button className={'attendance-cell '+(r?.status||'')} aria-label={'Chấm công '+e.name+' '+date} title={r?states[r.status]+(r.note?' · '+r.note:''): 'Chưa chấm'} disabled={!admin||!!data.lock.locked||busy} onClick={()=>open(e,date)}>{r?marks[r.status]:'·'}{r?.overtime_minutes>0&&<small>+{r.overtime_minutes/60}h</small>}</button></td>;})}<td><b>{t.work}</b></td><td>{t.leave}</td><td>{t.unpaid}</td><td>{t.ot}</td><td>{t.count}/{days}</td></tr>;})}</tbody></table>{!visible.length&&<div className="empty"><h3>Chưa có nhân viên phù hợp</h3><p>Thêm nhân viên và mã chấm công tại mục Nhân viên.</p></div>}</div></section><p className="footnote">Mã chấm công dùng để ghép dữ liệu máy chấm công sau này. Hiện tại công được ghi thủ công, tăng ca theo bước 15 phút. Xuất CSV mở được bằng Excel.</p>
 {editor&&<div className="overlay"><section className="modal" role="dialog" aria-label="Ghi công"><header><h2>{editor.name} · {fmtDate(editor.date)}</h2><button disabled={busy} onClick={()=>setEditor(null)} aria-label="Đóng">×</button></header><form onSubmit={e=>{e.preventDefault();run(async()=>{await api('/attendance','POST',{...editor,overtime_minutes:Number(editor.hours)*60});setEditor(null);});}}><div className="form-grid"><label className="field"><span>Trạng thái công</span><select value={editor.status} onChange={e=>change('status',e.target.value)}>{Object.entries(states).map(([s,t])=><option key={s} value={s}>{t}</option>)}</select></label><label className="field"><span>Tăng ca (giờ)</span><input type="number" min="0" max="16" step="0.25" required value={editor.hours} onChange={e=>change('hours',e.target.value)}/></label></div><label className="field"><span>Ghi chú công</span><textarea value={editor.note} onChange={e=>change('note',e.target.value)}/></label><label className="field"><span>Lý do sửa / xóa công{editor.id||editor.has_history?' *':''}</span><textarea required={!!editor.id||editor.has_history} value={editor.reason} onChange={e=>change('reason',e.target.value)}/></label>{error&&<p className="error" role="alert">{error}</p>}<footer><button type="button" disabled={busy} onClick={()=>setEditor(null)}>Hủy</button>{editor.id&&<button type="button" className="danger" disabled={busy||!editor.reason.trim()} onClick={()=>run(async()=>{await api('/attendance/'+editor.id,'DELETE',{version:editor.version,reason:editor.reason});setEditor(null);})}>Xóa công</button>}<button className="primary" disabled={busy}>Lưu công</button></footer></form></section></div>}
 {lockForm&&<div className="overlay"><section className="modal" role="dialog" aria-label="Khóa bảng công"><header><h2>{lockForm.locked?'Chốt và khóa':'Mở khóa'} {fmtDate(month)}</h2></header><form onSubmit={e=>{e.preventDefault();run(async()=>{await api('/attendance/month','POST',{...lockForm,month,version:data.lock.version});setLockForm(null);});}}><p>{lockForm.locked?'Tháng đã khóa sẽ không cho thêm, sửa hoặc xóa công. Kiểm tra các ô chưa chấm trước khi chốt.':'Mở khóa cho phép sửa công; lý do và người thực hiện được ghi nhật ký.'}</p><label className="field"><span>Lý do chốt / mở khóa</span><textarea required value={lockForm.reason} onChange={e=>setLockForm({...lockForm,reason:e.target.value})}/></label>{error&&<p className="error">{error}</p>}<footer><button type="button" disabled={busy} onClick={()=>setLockForm(null)}>Hủy</button><button className="primary" disabled={busy}>Xác nhận</button></footer></form></section></div>}
 </>;
}
