import React,{useState,useEffect,useRef} from 'react';
import {createPortal} from 'react-dom';
export const fmtDate=v=>!v?'—':/^\d{4}-\d{2}-\d{2}$/.test(v)?v.slice(8)+'/'+v.slice(5,7)+'/'+v.slice(0,4):/^\d{4}-\d{2}$/.test(v)?'Tháng '+Number(v.slice(5))+'/'+v.slice(0,4):v;
export const fmtTime=v=>v?new Intl.DateTimeFormat('vi-VN',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date(v.endsWith('Z')?v:v.replace(' ','T')+'Z')):'—';
export function DateInput({value='',onChange,required=false,...props}){
 const [draft,setDraft]=useState(value?fmtDate(value):''),[open,setOpen]=useState(false),[month,setMonth]=useState(value?.slice(0,7)||new Date().toISOString().slice(0,7)),[pos,setPos]=useState({});const ref=useRef();
 useEffect(()=>{setDraft(value?fmtDate(value):'');ref.current?.setCustomValidity('');},[value]);
 useEffect(()=>{if(!open)return;const close=e=>{if(!e.target.closest('.vn-calendar')&&!e.target.closest('.date-control'))setOpen(false);};document.addEventListener('mousedown',close);const key=e=>{if(e.key==='Escape')setOpen(false);};document.addEventListener('keydown',key);return()=>{document.removeEventListener('mousedown',close);document.removeEventListener('keydown',key);};},[open]);
 function text(e){let s=e.target.value;setDraft(s);let m=/^(\d{2})\/(\d{2})\/(\d{4})$/.exec(s),iso=m?m[3]+'-'+m[2]+'-'+m[1]:'';let d=new Date(iso+'T12:00:00Z');let valid=m&&!isNaN(d)&&d.toISOString().slice(0,10)===iso&&Number(m[3])>=1900&&Number(m[3])<=2200;ref.current.setCustomValidity(!s&&!required||valid?'':'Nhập ngày hợp lệ theo ngày/tháng/năm');if(valid||!s)onChange(valid?iso:'');}
 const choose=iso=>{onChange(iso);setDraft(iso?fmtDate(iso):'');ref.current.setCustomValidity('');setOpen(false);};let [y,m]=month.split('-').map(Number),days=new Date(y,m,0).getDate(),offset=(new Date(y,m-1,1).getDay()+6)%7;
 function shift(n){let d=new Date(y,m-1+n,1);setMonth(d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0'));}
 return <span className="date-control"><input {...props} ref={ref} type="text" inputMode="numeric" placeholder="dd/mm/yyyy" required={required} value={draft} onChange={text}/><button type="button" aria-label={'Mở lịch '+(props['aria-label']||props.name||'')} onClick={()=>{let r=ref.current.getBoundingClientRect();setPos({left:Math.min(r.left,window.innerWidth-310),top:r.bottom+6>window.innerHeight-350?Math.max(5,r.top-350):r.bottom+6});setMonth(value?.slice(0,7)||new Date().toISOString().slice(0,7));setOpen(!open);}}>▦</button>{open&&createPortal(<div className="vn-calendar" role="dialog" aria-label="Chọn ngày" style={pos}><header><button type="button" onClick={()=>shift(-1)} aria-label="Tháng trước">‹</button><strong>{fmtDate(month)}</strong><button type="button" onClick={()=>shift(1)} aria-label="Tháng sau">›</button></header><div className="calendar-days">{['T2','T3','T4','T5','T6','T7','CN'].map(d=><b key={d}>{d}</b>)}{Array.from({length:offset},(_,i)=><span key={'s'+i}/>)}{Array.from({length:days},(_,i)=>{let iso=month+'-'+String(i+1).padStart(2,'0');return <button type="button" key={iso} className={value===iso?'primary':''} onClick={()=>choose(iso)} aria-label={fmtDate(iso)}>{i+1}</button>;})}</div><footer><button type="button" onClick={()=>choose(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()))}>Hôm nay</button>{!required&&<button type="button" onClick={()=>choose('')}>Bỏ ngày</button>}</footer></div>,document.body)}</span>;
}
export function MonthInput({value,onChange,...props}){return <span className="month-control"><select {...props} value={value.slice(5)} onChange={e=>onChange(value.slice(0,4)+'-'+e.target.value)}>{Array.from({length:12},(_,i)=><option key={i} value={String(i+1).padStart(2,'0')}>Tháng {i+1}</option>)}</select><input aria-label="Năm chấm công" type="number" min="1900" max="2200" value={value.slice(0,4)} onChange={e=>{if(/^\d{4}$/.test(e.target.value))onChange(e.target.value+value.slice(4));}}/></span>;}
