import Attendance from './Attendance.jsx';
import React,{useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';import './style.css';
const money=n=>new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND',maximumFractionDigits:0}).format(n||0);
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const labels={RECEIPT:'Phiếu thu',EXPENSE:'Phiếu chi',TRANSFER:'Chuyển quỹ',RECEIVABLE:'Phải thu',PAYABLE:'Phải trả',ADVANCE:'Tạm ứng',CASH:'Tiền mặt',BANK:'Ngân hàng',OTHER:'Khác',IN:'Thu',OUT:'Chi',BOTH:'Thu và chi',CUSTOMER:'Khách hàng',SUPPLIER:'Nhà cung cấp',EMPLOYEE:'Nhân viên',ADMIN:'Kế toán / Admin',VIEWER:'Chỉ xem',ADVANCE_ISSUE:'Cấp ứng',ADVANCE_RETURN:'Hoàn ứng'};
const menus=[['dashboard','◫','Tổng quan'],['receipt','↓','Phiếu thu'],['expense','↑','Phiếu chi'],['transfer','⇄','Chuyển quỹ'],['receivable','▣','Công nợ phải thu'],['payable','▣','Công nợ phải trả'],['advance','₫','Tạm ứng'],['customer','♙','Khách hàng'],['supplier','▤','Nhà cung cấp'],['employee','♙','Nhân viên'],['attendance','▦','Chấm công'],['categories','☷','Danh mục'],['funds','▥','Nguồn tiền'],['reports','▧','Báo cáo'],['import','⇩','Nhập Excel'],['users','♧','Người dùng'],['audit','◷','Nhật ký hoạt động'],['settings','⚙','Cài đặt']];
const types={receipt:'RECEIPT',expense:'EXPENSE',transfer:'TRANSFER',receivable:'RECEIVABLE',payable:'PAYABLE',advance:'ADVANCE',customer:'CUSTOMER',supplier:'SUPPLIER',employee:'EMPLOYEE'};
let currentToken='';
async function api(route,method='GET',body=null){if(!window.vk)throw Error('Mở ứng dụng Windows để kết nối dữ liệu');return window.vk.api('/api'+route,method,body,currentToken);}
function Field({label,name,type='text',value,onChange,options,required=false,help}){return <label className="field"><span>{label}{required&&<b> *</b>}</span>{options?<select name={name} value={value??''} onChange={e=>onChange(name,e.target.value)} required={required}>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:type==='textarea'?<textarea name={name} value={value??''} onChange={e=>onChange(name,e.target.value)} required={required}/>:<input name={name} type={type} value={value??''} onChange={e=>onChange(name,e.target.value)} required={required} step={type==='number'?'1':undefined} maxLength={type==='password'?72:undefined}/>} {help&&<small>{help}</small>}</label>}
function Modal({title,children,onClose}){return <div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><section className="modal" role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button className="icon" onClick={onClose} aria-label="Đóng">×</button></header>{children}</section></div>}
function Empty({text='Chưa có dữ liệu',detail='Thêm mới để bắt đầu quản lý.'}){return <div className="empty"><span>▤</span><h3>{text}</h3><p>{detail}</p></div>}
function Badge({children,kind=''}){return <span className={'badge '+kind}>{children}</span>}
function App(){
 const [user,setUser]=useState(null),[initialized,setInitialized]=useState(null),[mode,setMode]=useState('login'),[authForm,setAuthForm]=useState({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[recovery,setRecovery]=useState('');
 const [page,setPage]=useState('dashboard'),[search,setSearch]=useState(''),[from,setFrom]=useState(today().slice(0,7)+'-01'),[to,setTo]=useState(today()),[fundFilter,setFundFilter]=useState(''),[status,setStatus]=useState('active'),[kindFilter,setKindFilter]=useState('');
 const [data,setData]=useState({vouchers:[],funds:[],contacts:[],categories:[],obligations:[],users:[],audit:[],backups:[],imports:[]}),[report,setReport]=useState(null),[modal,setModal]=useState(null),[form,setForm]=useState({}),[modalError,setModalError]=useState(''),[toast,setToast]=useState(''),[selected,setSelected]=useState({}),[sheet,setSheet]=useState(''),[update,setUpdate]=useState({status:'unconfigured',message:'Chưa cấu hình nơi phát hành cập nhật'}),[updateUrl,setUpdateUrl]=useState('');
 const admin=user?.role==='ADMIN';const title=menus.find(m=>m[0]===page)?.[2]||page;
 useEffect(()=>{api('/health').then(x=>{setInitialized(x.initialized);if(!x.initialized)setMode('register');}).catch(e=>setError(e.message));return window.vk?.onUpdate(setUpdate);},[]);
 useEffect(()=>{if(to&&from&&user)loadReport().catch(e=>setToast(e.message));},[from,to,user]);
 useEffect(()=>{if(!toast)return;let t=setTimeout(()=>setToast(''),6000);return()=>clearTimeout(t);},[toast]);
 async function loadReport(){setReport(await api('/report?from='+from+'&to='+to));}
 async function refresh(u=user){if(!u)return;const isAdmin=u.role==='ADMIN';let paths=['/vouchers','/masters/funds','/masters/contacts','/masters/categories','/obligations','/audit',...(isAdmin?['/users','/backups','/import/preview']:[])];let values=await Promise.all(paths.map(p=>api(p)));setData({vouchers:values[0],funds:values[1],contacts:values[2],categories:values[3],obligations:values[4],audit:values[5],users:values[6]||[],backups:values[7]||[],imports:values[8]||[]});setReport(await api('/report?from='+from+'&to='+to));if(window.vk){let s=await window.vk.updates('status',currentToken);setUpdate(s);setUpdateUrl(s.githubUrl||'');}}
 function change(name,value){setForm(f=>{let next={...f,[name]:value};if(name==='type'){next.to_fund_id='';next.obligation_id='';next.purpose='';next.category_id='';next.fee=0;}if(name==='obligation_id'){let o=data.obligations.find(x=>x.id==value);next.purpose=o?.kind==='ADVANCE'?(f.type==='EXPENSE'?'ADVANCE_ISSUE':'ADVANCE_RETURN'):'';if(o)next.contact_id=o.contact_id;}return next;});}function authChange(name,value){setAuthForm(f=>({...f,[name]:value}));}
 function show(spec,values={}){setModalError('');setForm(values);setModal(spec);}
 function loggedOut(){currentToken='';setUser(null);setReport(null);setData({vouchers:[],funds:[],contacts:[],categories:[],obligations:[],users:[],audit:[],backups:[],imports:[]});setAuthForm({});setMode('login');setInitialized(true);}
 async function submitAuth(e){e.preventDefault();setBusy(true);setError('');try{if(mode==='login'){let x=await api('/auth/login','POST',authForm);currentToken=x.token;setUser(x.user);setAuthForm({});await refresh(x.user);}else{let x=await api(mode==='register'?'/auth/register':'/auth/reset','POST',authForm);setRecovery(x.recoveryCode);setMode('login');setInitialized(true);setAuthForm({});}}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function action(fn){setBusy(true);try{await fn();}catch(e){setToast(e.message);}finally{setBusy(false);}}
 async function logout(){await action(async()=>{try{await api('/auth/logout','POST');}finally{loggedOut();}});}
 function nav(p){setPage(p);setSearch('');setFundFilter('');setStatus('active');setKindFilter('');}
 const options=(values,blank='Chọn...')=>[{value:'',label:blank},...values.map(x=>({value:x.id,label:x.kind==='BANK'?fundName(x):x.name||x.description}))];
 const fundName=f=>f.name+(f.kind==='BANK'&&f.account_number?' · '+(f.bank_name||'Ngân hàng')+' · STK '+f.account_number:'');
 const choices=values=>values.map(x=>({value:x,label:labels[x]}));
 function newVoucher(type,ob=null,purpose=''){show({kind:'voucher',title:'Thêm '+labels[type].toLowerCase()}, {type,date:today(),amount:'',fee:0,fund_id:data.funds.length===1?data.funds[0].id:'',to_fund_id:'',contact_id:ob?.contact_id||'',category_id:'',obligation_id:ob?.id||'',purpose,description:ob?labels[purpose||type]+' · '+ob.description:''});}
 function newMaster(table,kind){show({kind:'master',table,title:'Thêm '+title.toLowerCase()},{name:'',kind:kind||'BOTH',opening:0,opening_date:today(),note:'',phone:''});}
 function newObligation(kind){show({kind:'obligation',title:'Thêm '+labels[kind].toLowerCase()},{kind,date:today(),due_date:'',amount:'',contact_id:'',description:''});}
 function edit(row,kind,table){show({kind,table,id:row.id,title:'Sửa '+(row.code||row.name)}, {...row,reason:''});}
 function remove(row,kind,table){show({kind:'delete',target:kind,table,id:row.id,title:kind==='voucher'?'Hủy phiếu '+row.code:'Xóa '+(row.code||row.name)}, {version:row.version,reason:''});}
 async function submitModal(e){e.preventDefault();setBusy(true);setModalError('');try{let m=modal;
  if(m.kind==='voucher')await api('/vouchers'+(m.id?'/'+m.id:''),m.id?'PUT':'POST',form);
  else if(m.kind==='master')await api('/masters/'+m.table+(m.id?'/'+m.id:''),m.id?'PUT':'POST',form);
  else if(m.kind==='obligation')await api('/obligations'+(m.id?'/'+m.id:''),m.id?'PUT':'POST',form);
  else if(m.kind==='delete'){let route=m.target==='voucher'?'/vouchers/':m.target==='obligation'?'/obligations/':'/masters/'+m.table+'/';await api(route+m.id,'DELETE',form);}
  else if(m.kind==='clear')await api('/obligations/'+m.id+'/clear','POST',form);
  else if(m.kind==='user'){if(m.id){await api('/users/'+m.id,'PUT',form);if(m.id===user.id){setModal(null);loggedOut();return;}}else{let x=await api('/auth/register','POST',form);setRecovery(x.recoveryCode);}}
  else if(m.kind==='password'){let x=await api('/auth/password','POST',form);setRecovery(x.recoveryCode);setModal(null);loggedOut();return;}
  else if(m.kind==='restore'){let x=await window.vk.restore(form.password,currentToken);if(x.canceled)return;setModal(null);loggedOut();setToast('Đã khôi phục. Đăng nhập bằng tài khoản trong bản sao lưu.');return;}
  else if(m.kind==='import'){let rows=Object.values(selected);await api('/import/commit','POST',rows.map(x=>({sourceId:x.id,date:x.date,type:x.type,amount:x.amount,fund_id:x.fund_id})));setSelected({});}
  setModal(null);await refresh();setToast('Đã lưu thay đổi');
 }catch(e){setModalError(e.message);}finally{setBusy(false);}}
 async function exportRows(rows,name){const escape=v=>{let s=String(v??'');if(/^[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};let text=rows.map(row=>row.map(escape).join(',')).join('\r\n');let result=await window.vk.exportCSV(name,text);if(!result.canceled)setToast('Đã xuất báo cáo: '+result.file);}
 const filtered=rows=>rows.filter(r=>JSON.stringify(r).toLocaleLowerCase('vi').includes(search.toLocaleLowerCase('vi'))).filter(r=>!kindFilter||r.kind===kindFilter);
 const voucherRows=filtered(data.vouchers.filter(r=>r.type===types[page]&&r.date>=from&&r.date<=to&&(!fundFilter||r.fund_id==fundFilter||r.to_fund_id==fundFilter)&&(status==='all'||r.deleted===(status==='void'?1:0))));
 const obligationRows=filtered(data.obligations.filter(r=>r.kind===types[page]&&(status==='all'||(status==='paid'?r.outstanding===0:r.outstanding>0))));
 const mastersTable=['customer','supplier','employee'].includes(page)?'contacts':page;
 const masterRows=filtered((data[mastersTable]||[]).filter(r=>!types[page]||r.kind===types[page]));
 const sum=(rows,key)=>rows.reduce((s,r)=>s+Number(r[key]||0),0);
 const totalBalance=sum(report?.funds||[],'balance'),inc=report?.totals?.income||0,exp=report?.totals?.expense||0;
 const debts=report?.obligations||[];const totalDebt=kind=>sum(debts.filter(d=>d.kind===kind),'outstanding');
 function toolbar(add,dateFilter=false,extra=null){return <div className="toolbar"><div className="search"><span>⌕</span><input aria-label="Tìm kiếm" placeholder="Tìm mã, nội dung, đối tác..." value={search} onChange={e=>setSearch(e.target.value)}/></div>{dateFilter&&<><input aria-label="Từ ngày" type="date" value={from} onChange={e=>setFrom(e.target.value)}/><span>đến</span><input aria-label="Đến ngày" type="date" value={to} onChange={e=>setTo(e.target.value)}/></>}{extra}{admin&&add&&<button className="primary" onClick={add}>+ Thêm mới</button>}</div>}
 const field=(label,name,type='text',opts,required=false,help)=> <Field key={name} label={label} name={name} type={type} value={form[name]} onChange={change} options={opts} required={required} help={help}/>;
 function modalFields(){let k=modal?.kind;if(k==='delete')return <><p className="notice">{modal.target==='voucher'?'Phiếu sẽ ngừng tính vào số dư và báo cáo. Bản gốc, các lần sửa và lý do hủy vẫn được lưu trong nhật ký.':'Thông tin đã có chứng từ liên kết sẽ không được xóa.'}</p>{field('Lý do','reason','textarea',null,true)}</>;
  if(k==='password')return <>{field('Mật khẩu hiện tại','oldPassword','password',null,true)}{field('Mật khẩu mới','password','password',null,true,'Từ 10–72 ký tự. Sau khi đổi cần đăng nhập lại.')}</>;
  if(k==='restore')return <><p className="notice">Khôi phục thay thế dữ liệu hiện tại bằng bản sao đã chọn. App tự lưu một bản an toàn trước khi thay thế và đăng xuất tất cả tài khoản.</p>{field('Mật khẩu Admin hiện tại','password','password',null,true)}</>;
  if(k==='clear')return <><p className="notice">Ghi nhận chi phí đã có chứng từ từ tiền tạm ứng. Không trừ quỹ lần nữa. Biên nhận quyết toán được lưu trong nhật ký.</p>{field('Ngày quyết toán','date','date',null,true)}{field('Số tiền quyết toán (đ)','amount','number',null,true)}{field('Chứng từ và nội dung quyết toán','note','textarea',null,true)}</>;
  if(k==='import')return <><p>Ghi {Object.keys(selected).length} dòng đã chọn vào sổ. Mỗi dòng phải đúng ngày và nguồn tiền.</p><p className="notice">Xác nhận nguồn tiền và số dư đầu kỳ trước. Không nhập lại các bảng lương, tiền ăn hoặc khoản đã ghi riêng.</p></>;
  if(k==='user')return <><div className="form-grid">{!modal.id&&field('Tên đăng nhập','username','text',null,true)}{field('Họ tên','name','text',null,true)}{field('Vai trò','role','text',choices(['ADMIN','VIEWER']),true)}{modal.id?field('Trạng thái','active','text',[{value:1,label:'Hoạt động'},{value:0,label:'Khóa tài khoản'}],true):field('Mật khẩu ban đầu','password','password',null,true,'Từ 10–72 ký tự')}</div>{!modal.id&&<p className="notice">Lưu mã khôi phục để bàn giao riêng cho người dùng.</p>}</>;
  if(k==='master')return <><div className="form-grid">{field('Tên','name','text',null,true)}{field('Loại','kind','text',choices(modal.table==='funds'?['CASH','BANK','OTHER']:modal.table==='categories'?['IN','OUT','BOTH']:['CUSTOMER','SUPPLIER','EMPLOYEE','OTHER']),true)}{modal.table==='funds'&&<>{field('Số dư đầu kỳ (đ)','opening','number',null,true)}{field('Ngày bắt đầu theo dõi','opening_date','date',null,true)}</>}{modal.table==='funds'&&form.kind==='BANK'&&<>{field('Tên ngân hàng','bank_name')}{field('Số tài khoản ngân hàng','account_number','text',null,false,'Giữ nguyên số 0 đầu tài khoản')}{field('Tên chủ tài khoản','account_holder')}</>}{modal.table==='contacts'&&field('Điện thoại','phone')}{modal.table==='contacts'&&form.kind==='EMPLOYEE'&&field('Mã chấm công','attendance_code','text',null,false,'Mã duy nhất để ghép dữ liệu máy chấm công sau này')}</div>{field('Ghi chú','note','textarea')}{modal.table==='funds'&&<p className="notice">Số dư đầu kỳ là số tiền tại đầu ngày bắt đầu theo dõi, trước các phiếu ngày đó. Phiếu trước ngày này sẽ bị chặn. Chỉnh số dư sẽ được lưu lịch sử.</p>}</>;
  if(k==='obligation')return <><div className="form-grid">{field('Loại','kind','text',choices(['RECEIVABLE','PAYABLE','ADVANCE']),true)}{field('Đối tác / nhân viên','contact_id','text',options(data.contacts),true)}{field('Ngày ghi nhận','date','date',null,true)}{field('Hạn thanh toán','due_date','date')}{field(form.kind==='ADVANCE'?'Số tiền đề nghị tạm ứng (đ)':'Số tiền công nợ (đ)','amount','number',null,true)}</div>{field('Nội dung / chứng từ gốc','description','textarea',null,true)}{modal.id&&field('Lý do sửa','reason','textarea')}{form.kind==='ADVANCE'&&<p className="notice">Tạo khoản tạm ứng chưa làm giảm quỹ. Sau khi lưu, chọn Cấp ứng để ghi phiếu chi. Hoàn ứng là phiếu thu, quyết toán không ghi chi lần nữa.</p>}</>;
  if(k==='voucher'){let obs=data.obligations.filter(o=>form.type==='RECEIPT'?['RECEIVABLE','ADVANCE'].includes(o.kind):form.type==='EXPENSE'?['PAYABLE','ADVANCE'].includes(o.kind):false);let ob=obs.find(o=>o.id==form.obligation_id);return <><div className="form-grid">{field('Loại phiếu','type','text',choices(['RECEIPT','EXPENSE','TRANSFER']),true)}{field('Ngày hạch toán','date','date',null,true)}{field(form.type==='TRANSFER'?'Nguồn chuyển':'Nguồn tiền','fund_id','text',options(data.funds),true)}{form.type==='TRANSFER'&&field('Nguồn nhận','to_fund_id','text',options(data.funds.filter(x=>x.id!=form.fund_id)),true)}{field('Số tiền (đ)','amount','number',null,true)}{form.type==='TRANSFER'&&field('Phí chuyển (đ)','fee','number',null,true)}{field('Nhóm thu / chi','category_id','text',options(data.categories.filter(c=>c.kind==='BOTH'||c.kind===(form.type==='RECEIPT'?'IN':'OUT')),'Chưa phân loại'))}{field('Đối tác / nhân viên','contact_id','text',options(data.contacts,'Không liên kết'))}{form.type!=='TRANSFER'&&field('Công nợ / tạm ứng liên kết','obligation_id','text',[{value:'',label:'Không liên kết'},...obs.map(o=>({value:o.id,label:o.code+' · '+o.description+' · '+money(o.outstanding)}))])}{ob?.kind==='ADVANCE'&&field('Nghiệp vụ tạm ứng','purpose','text',choices([form.type==='EXPENSE'?'ADVANCE_ISSUE':'ADVANCE_RETURN']),true)}</div>{field('Nội dung','description','textarea',null,true)}{field('Tham chiếu chứng từ','source_ref')}{modal.id&&field('Lý do sửa','reason','textarea',null,true)}<p className="notice">Lưu phiếu sẽ ghi nhận ngay vào số dư. Chọn đúng đối tác khi liên kết công nợ. Không ghi trùng khoản chuyển nội bộ vào thu và chi.</p></>;}
 }
 function voucherTable(rows,actions=true){return <div className="table-wrap"><table><thead><tr><th>Mã phiếu</th><th>Ngày</th><th>Nội dung</th><th>Nguồn tiền</th><th>Đối tác</th><th className="right">Số tiền</th><th>Trạng thái</th>{actions&&admin&&<th>Thao tác</th>}</tr></thead><tbody>{rows.map(v=><tr key={v.id} className={v.deleted?'void':''}><td><strong className="code">{v.code}</strong></td><td className="nowrap">{v.date}</td><td className="desc">{v.description}<small>{v.category_name||'Chưa phân loại'}{v.source_ref&&' · '+v.source_ref}</small></td><td>{fundName(data.funds.find(f=>f.id===v.fund_id)||{name:v.fund_name})}{v.to_fund_name&&<small>→ {fundName(data.funds.find(f=>f.id===v.to_fund_id)||{name:v.to_fund_name})}</small>}</td><td>{v.contact_name||'—'}</td><td className={'right nowrap '+(v.type==='RECEIPT'?'positive':v.type==='EXPENSE'?'negative':'')}>{money(v.amount)}{v.fee>0&&<small>Phí {money(v.fee)}</small>}</td><td><Badge kind={v.deleted?'gray':v.type==='RECEIPT'?'green':'blue'}>{v.deleted?'Đã hủy':'Đã ghi sổ'}</Badge></td>{actions&&admin&&<td className="nowrap">{!v.deleted&&<><button className="text-btn" onClick={()=>edit(v,'voucher')}>Sửa</button><button className="text-btn danger" onClick={()=>remove(v,'voucher')}>Xóa</button></>}</td>}</tr>)}</tbody></table>{!rows.length&&<Empty/>}</div>;}
 function trend(){let rows=report?.monthly||[];if(!rows.length)return <Empty text="Chưa có giao dịch trong kỳ" detail="Biểu đồ sẽ xuất hiện khi kế toán ghi nhận phiếu."/>;let max=Math.max(...rows.flatMap(x=>[x.income,x.expense]),1);return <div className="chart"><div className="chart-legend"><i className="dot green"/> Thu <i className="dot red"/> Chi <small>Đơn vị: triệu đồng</small></div><div className="bars">{rows.map(x=><div className="bar-group" key={x.month}><div className="bar-pair"><div className="bar income" style={{height:Math.max(3,x.income/max*145)}} title={money(x.income)}><small>{new Intl.NumberFormat('vi-VN',{maximumFractionDigits:1}).format(x.income/1000000)}</small></div><div className="bar expense" style={{height:Math.max(3,x.expense/max*145)}} title={money(x.expense)}><small>{new Intl.NumberFormat('vi-VN',{maximumFractionDigits:1}).format(x.expense/1000000)}</small></div></div><label>{x.month}</label></div>)}</div></div>;}
 function recoveryModal(){return recovery&&<Modal title="Lưu mã khôi phục tài khoản" onClose={()=>{}}><p>Giữ mã này ở nơi riêng. App chỉ hiển thị một lần. Khi quên mật khẩu, dùng mã để đặt lại mà không cần Internet.</p><code className="recovery">{recovery}</code><p className="notice">Mỗi lần đổi hoặc đặt lại mật khẩu sẽ cấp mã mới và vô hiệu mã cũ.</p><footer><button className="primary" onClick={()=>setRecovery('')}>Tôi đã lưu mã</button></footer></Modal>;}
 if(!user)return <div className="login-page"><aside className="login-brand"><img src="./logo.jpg"/><div><p>VĨNH KHANG</p><h1>Rõ từng khoản thu.<br/>Vững từng quyết định.</h1><span>Quản lý thu chi, nguồn tiền và công nợ<br/>trong một ứng dụng.</span></div><small>THU CHI VĨNH KHANG · V1.0.2</small></aside><main className="login-main"><form onSubmit={submitAuth}><div className="eyebrow">QUẢN LÝ TÀI CHÍNH NỘI BỘ</div><h2>{mode==='register'?'Thiết lập kế toán Admin':mode==='reset'?'Quên mật khẩu':'Chào anh, mời đăng nhập'}</h2><p>{mode==='register'?'Tạo tài khoản đầu tiên để bắt đầu sử dụng.':mode==='reset'?'Dùng mã khôi phục đã lưu khi tạo tài khoản.':'Theo dõi nguồn tiền và công việc kế toán hôm nay.'}</p>{mode==='register'&&<Field label="Họ tên" name="name" value={authForm.name} onChange={authChange} required/>}<Field label="Tên đăng nhập" name="username" value={authForm.username} onChange={authChange} required/>{mode==='reset'&&<Field label="Mã khôi phục" name="recoveryCode" value={authForm.recoveryCode} onChange={authChange} required/>}<Field label={mode==='reset'?'Mật khẩu mới':'Mật khẩu'} name="password" type="password" value={authForm.password} onChange={authChange} required help={mode!=='login'?'Từ 10 đến 72 ký tự':undefined}/>{error&&<p className="error" role="alert">{error}</p>}<button className="primary wide" disabled={busy||initialized===null}>{busy?'Đang xử lý...':mode==='register'?'Tạo tài khoản':mode==='reset'?'Đặt lại mật khẩu':'Đăng nhập'}</button><button type="button" className="text-btn" onClick={()=>{setMode(mode==='reset'?'login':'reset');setError('');}}>{mode==='reset'?'Quay lại đăng nhập':'Quên mật khẩu?'}</button>{initialized===false&&mode!=='register'&&<button type="button" className="text-btn" onClick={()=>setMode('register')}>Đăng ký tài khoản đầu tiên</button>}<small className="login-note">Tài khoản tiếp theo được Admin đăng ký trong mục Người dùng.</small></form></main>{recoveryModal()}{toast&&<div className="toast" role="status">{toast}</div>}</div>;
 return <div className="app"><aside className="sidebar"><div className="brand"><img src="./logo.jpg"/><div><strong>VĨNH KHANG</strong><small>Quản lý thu chi</small></div></div><div className="nav-label">KHÔNG GIAN KẾ TOÁN</div><nav>{menus.filter(m=>admin||!['users','import','settings'].includes(m[0])).map(([id,icon,name])=><button key={id} className={page===id?'active':''} onClick={()=>nav(id)}><span>{icon}</span>{name}{id==='advance'&&totalDebt('ADVANCE')>0&&<i/>}</button>)}</nav><div className="sidebar-bottom"><span className="live-dot"/> Dữ liệu trên máy này <small>Phiên bản 1.0.2</small></div></aside><div className="workspace"><header className="topbar"><div><span>Vĩnh Khang</span><b>/</b><strong>{title}</strong></div><div className="account"><div className="avatar">{user.name.slice(0,1).toUpperCase()}</div><div><strong>{user.name}</strong><small>{labels[user.role]}</small></div><button className="text-btn" onClick={()=>show({kind:'password',title:'Đổi mật khẩu'})}>Đổi mật khẩu</button><button className="text-btn" onClick={logout}>Đăng xuất</button></div></header><main className="content">{admin&&['available','downloaded'].includes(update.status)&&page!=='settings'&&<div className="notice">Có phiên bản mới {update.version}. <button onClick={()=>nav('settings')}>Cập nhật app</button></div>}<div className="page-heading"><div><div className="eyebrow">TÀI CHÍNH VĨNH KHANG</div><h1>{title}</h1><p>{page==='dashboard'?'Nguồn tiền, dòng tiền và các khoản cần theo dõi.':page==='audit'?'Lưu lại người thực hiện, dữ liệu trước và sau mỗi thay đổi.':page==='import'?'Đối soát Excel trước khi ghi nhận vào sổ.':'Quản lý và tra cứu dữ liệu kế toán.'}</p></div><div className="heading-actions"><button onClick={()=>action(()=>refresh())} disabled={busy}>↻ Làm mới</button>{page==='dashboard'&&admin&&<><button onClick={()=>newVoucher('EXPENSE')}>↑ Ghi chi</button><button className="primary" onClick={()=>newVoucher('RECEIPT')}>↓ Ghi thu</button></>}</div></div>
 {page==='dashboard'&&<><div className="period"><span>Kỳ báo cáo</span><input aria-label="Từ ngày" type="date" value={from} onChange={e=>setFrom(e.target.value)}/><span>—</span><input aria-label="Đến ngày" type="date" value={to} onChange={e=>setTo(e.target.value)}/><small>Công nợ: hiện tại</small></div><div className="kpis"><div className="kpi balance"><span>TỔNG TIỀN ĐẾN {to}</span><strong>{money(totalBalance)}</strong><small>{data.funds.length} nguồn tiền đang theo dõi</small></div><div className="kpi"><span>THU TRONG KỲ <i className="positive">↓</i></span><strong className="positive">{money(inc)}</strong><small>Phiếu thu đã ghi sổ</small></div><div className="kpi"><span>CHI TRONG KỲ <i className="negative">↑</i></span><strong className="negative">{money(exp)}</strong><small>Gồm phí chuyển quỹ</small></div><div className="kpi"><span>DÒNG TIỀN THUẦN</span><strong>{money(inc-exp)}</strong><small>Thu trừ chi trong kỳ</small></div></div><div className="dashboard-grid"><section className="card"><div className="card-heading"><h3>Dòng tiền theo tháng</h3><Badge kind="blue">{from.slice(0,7)} → {to.slice(0,7)}</Badge></div>{trend()}</section><section className="card"><div className="card-heading"><h3>Tiền đang ở đâu?</h3><button className="text-btn" onClick={()=>nav('funds')}>Xem nguồn tiền →</button></div>{report?.funds?.length?report.funds.map(f=><div className="fund-line" key={f.id}><div className="fund-symbol">{f.kind==='BANK'?'▥':'₫'}</div><div><strong>{fundName(f)}</strong><small>{labels[f.kind]}</small></div><b className={f.balance<0?'negative':''}>{money(f.balance)}</b></div>):<Empty text="Chưa thiết lập nguồn tiền" detail="Thêm quỹ tiền mặt hoặc tài khoản ngân hàng."/>}</section></div><div className="debt-cards">{[['RECEIVABLE','Công nợ phải thu','receivable'],['PAYABLE','Công nợ phải trả','payable'],['ADVANCE','Tạm ứng còn lại','advance']].map(([kind,label,p])=><button key={kind} onClick={()=>nav(p)}><span>{label}</span><strong>{money(totalDebt(kind))}</strong><small>{debts.filter(x=>x.kind===kind&&x.outstanding>0).length} khoản đang theo dõi →</small></button>)}</div><section className="card"><div className="card-heading"><h3>Giao dịch gần đây trong kỳ</h3><small>{from} — {to}</small></div>{voucherTable(data.vouchers.filter(v=>!v.deleted&&v.date>=from&&v.date<=to).slice(0,7))}</section>{!data.funds.length&&<div className="setup-note"><strong>Bắt đầu sử dụng</strong><p>1. Thêm nguồn tiền và số dư đầu kỳ. &nbsp; 2. Thêm đối tác, danh mục. &nbsp; 3. Ghi phiếu hoặc đối soát Excel.</p><button onClick={()=>nav('funds')}>Thiết lập nguồn tiền →</button></div>}</>}
 {['receipt','expense','transfer'].includes(page)&&<>{toolbar(()=>newVoucher(types[page]),true,<><select aria-label="Lọc nguồn tiền" value={fundFilter} onChange={e=>setFundFilter(e.target.value)}><option value="">Tất cả nguồn tiền</option>{data.funds.map(f=><option key={f.id} value={f.id}>{fundName(f)}</option>)}</select><select aria-label="Lọc trạng thái" value={status} onChange={e=>setStatus(e.target.value)}><option value="active">Đã ghi sổ</option><option value="void">Đã hủy</option><option value="all">Tất cả</option></select></>)}<div className="list-summary"><span>{voucherRows.length} phiếu</span><b>{money(sum(voucherRows.filter(v=>!v.deleted),'amount'))}</b><button className="text-btn" onClick={()=>action(()=>exportRows([['Mã','Ngày','Loại','Nội dung','Nguồn','Nguồn nhận','Số tiền','Phí','Đối tác','Trạng thái'],...voucherRows.map(v=>[v.code,v.date,labels[v.type],v.description,v.fund_name,v.to_fund_name,v.amount,v.fee,v.contact_name,v.deleted?'Đã hủy':'Đã ghi sổ'])],'phieu-'+page+'.csv'))}>Xuất CSV</button></div><section className="card flush">{voucherTable(voucherRows)}</section></>}
 {['receivable','payable','advance'].includes(page)&&<>{toolbar(()=>newObligation(types[page]),false,<select aria-label="Lọc công nợ" value={status} onChange={e=>setStatus(e.target.value)}><option value="active">Còn dư</option><option value="paid">Đã thanh toán</option><option value="all">Tất cả</option></select>)}<div className="list-summary"><span>{obligationRows.length} khoản</span><b>Còn lại: {money(sum(obligationRows,'outstanding'))}</b></div><section className="card flush"><div className="table-wrap"><table><thead><tr><th>Mã / nội dung</th><th>Đối tác</th><th>Ngày / hạn</th><th className="right">Gốc</th>{page==='advance'&&<th className="right">Đã cấp</th>}<th className="right">Còn lại</th><th>Trạng thái</th>{admin&&<th>Thao tác</th>}</tr></thead><tbody>{obligationRows.map(o=><tr key={o.id}><td><strong className="code">{o.code}</strong><small>{o.description}</small></td><td>{o.contact_name}</td><td>{o.date}<small>{o.due_date||'Chưa có hạn'}</small></td><td className="right nowrap">{money(o.amount)}</td>{page==='advance'&&<td className="right nowrap">{money(o.issued)}</td>}<td className="right nowrap"><b>{money(o.outstanding)}</b></td><td><Badge kind={o.outstanding===0?'green':o.due_date&&o.due_date<today()?'red':'blue'}>{o.outstanding===0?'Đã tất toán':o.due_date&&o.due_date<today()?'Quá hạn':'Còn dư'}</Badge></td>{admin&&<td><div className="row-actions">{o.kind==='ADVANCE'?<>{o.issued<o.amount&&<button onClick={()=>newVoucher('EXPENSE',o,'ADVANCE_ISSUE')}>Cấp ứng</button>}{o.outstanding>0&&o.issued>o.amount-o.outstanding&&<><button onClick={()=>newVoucher('RECEIPT',o,'ADVANCE_RETURN')}>Hoàn ứng</button><button onClick={()=>show({kind:'clear',id:o.id,title:'Quyết toán '+o.code},{date:today(),amount:'',note:''})}>Quyết toán</button></>}</>:o.outstanding>0&&<button onClick={()=>newVoucher(o.kind==='PAYABLE'?'EXPENSE':'RECEIPT',o)}>Thanh toán</button>}<button className="text-btn" onClick={()=>edit(o,'obligation')}>Sửa</button><button className="text-btn danger" onClick={()=>remove(o,'obligation')}>Xóa</button></div></td>}</tr>)}</tbody></table>{!obligationRows.length&&<Empty/>}</div></section><p className="footnote">Công nợ tính từ số tiền gốc trừ phiếu thanh toán liên kết còn hiệu lực. Tạm ứng chưa cấp tiền vẫn được theo dõi theo số đề nghị.</p></>}
 {['customer','supplier','employee','categories','funds'].includes(page)&&<>{toolbar(()=>newMaster(mastersTable,types[page]||(page==='funds'?'BANK':'BOTH')),false,<select aria-label="Lọc loại" value={kindFilter} onChange={e=>setKindFilter(e.target.value)}><option value="">Tất cả loại</option>{(page==='funds'?['CASH','BANK','OTHER']:page==='categories'?['IN','OUT','BOTH']:[]).map(k=><option key={k} value={k}>{labels[k]}</option>)}</select>)}<section className="card flush"><div className="table-wrap"><table><thead><tr><th>Tên</th><th>Loại</th>{page==='funds'?<><th>Ngày bắt đầu</th><th className="right">Số dư đầu kỳ</th><th className="right">Số dư đến {to}</th></>:mastersTable==='contacts'?<th>Điện thoại</th>:null}<th>Ghi chú</th>{admin&&<th>Thao tác</th>}</tr></thead><tbody>{masterRows.map(r=><tr key={r.id}><td><strong>{r.name}</strong>{page==='funds'&&r.kind==='BANK'&&<small>{r.bank_name||'Ngân hàng'} · STK {r.account_number||'Chưa ghi'}<br/>{r.account_holder}</small>}{page==='employee'&&<small>Mã chấm công: {r.attendance_code||'Chưa ghi'}</small>}</td><td><Badge kind="blue">{labels[r.kind]}</Badge></td>{page==='funds'?<><td>{r.opening_date}</td><td className="right nowrap">{money(r.opening)}</td><td className="right nowrap"><b>{money(report?.funds?.find(f=>f.id===r.id)?.balance)}</b></td></>:mastersTable==='contacts'?<td>{r.phone||'—'}</td>:null}<td>{r.note||'—'}</td>{admin&&<td className="nowrap"><button className="text-btn" onClick={()=>edit(r,'master',mastersTable)}>Sửa</button><button className="text-btn danger" onClick={()=>remove(r,'master',mastersTable)}>Xóa</button></td>}</tr>)}</tbody></table>{!masterRows.length&&<Empty/>}</div></section></>}
 {page==='attendance'&&<Attendance api={api} employees={data.contacts.filter(c=>c.kind==='EMPLOYEE')} admin={admin} exportRows={exportRows}/>}
 {page==='reports'&&<>{toolbar(null,true)}<div className="kpis"><div className="kpi"><span>THU</span><strong className="positive">{money(inc)}</strong></div><div className="kpi"><span>CHI VÀ PHÍ CHUYỂN</span><strong className="negative">{money(exp)}</strong></div><div className="kpi"><span>CHÊNH LỆCH THU CHI</span><strong>{money(inc-exp)}</strong></div><div className="kpi"><span>SỐ DƯ CUỐI KỲ</span><strong>{money(totalBalance)}</strong></div></div><section className="card"><div className="card-heading"><h3>Sổ nguồn tiền</h3><button onClick={()=>action(()=>exportRows([['Nguồn tiền','Đầu kỳ','Số dư đầu kỳ thêm trong khoảng','Cuối kỳ'],...(report?.funds||[]).map(f=>[f.name,f.start,f.opening_in_period,f.balance])],'so-nguon-tien.csv'))}>Xuất CSV</button></div><table><thead><tr><th>Nguồn tiền</th><th className="right">Đầu kỳ</th><th className="right">Số dư mở trong kỳ</th><th className="right">Cuối kỳ</th></tr></thead><tbody>{filtered(report?.funds||[]).map(f=><tr key={f.id}><td>{f.name}</td><td className="right">{money(f.start)}</td><td className="right">{money(f.opening_in_period)}</td><td className="right"><b>{money(f.balance)}</b></td></tr>)}</tbody></table></section><div className="dashboard-grid"><section className="card"><div className="card-heading"><h3>Chi theo danh mục</h3><button className="text-btn" onClick={()=>action(()=>exportRows([['Danh mục','Số tiền'],...(report?.groups||[]).map(g=>[g.name,g.amount])],'chi-theo-danh-muc.csv'))}>Xuất CSV</button></div>{report?.groups?.map(g=><div className="fund-line" key={g.name}><strong>{g.name}</strong><b>{money(g.amount)}</b></div>)}{!report?.groups?.length&&<Empty/>}</section><section className="card"><div className="card-heading"><h3>Công nợ hiện tại</h3><button className="text-btn" onClick={()=>action(()=>exportRows([['Mã','Loại','Đối tác','Nội dung','Gốc','Còn lại','Hạn'],...debts.map(o=>[o.code,labels[o.kind],o.contact_name,o.description,o.amount,o.outstanding,o.due_date])],'cong-no.csv'))}>Xuất CSV</button></div>{['RECEIVABLE','PAYABLE','ADVANCE'].map(k=><div className="fund-line" key={k}><strong>{labels[k]}</strong><b>{money(totalDebt(k))}</b></div>)}</section></div><p className="footnote">Chênh lệch thu chi là dòng tiền, chưa thể hiện lợi nhuận kế toán. Chuyển quỹ nội bộ không cộng vào tổng thu/chi; phí chuyển được tính vào chi. Báo cáo công nợ là số dư hiện tại.</p></>}
 {page==='users'&&<>{toolbar(()=>show({kind:'user',title:'Đăng ký người dùng'},{username:'',name:'',role:'VIEWER',password:''}),false,<select aria-label="Lọc vai trò" value={kindFilter} onChange={e=>setKindFilter(e.target.value)}><option value="">Tất cả vai trò</option><option value="ADMIN">Admin</option><option value="VIEWER">Chỉ xem</option></select>)}<section className="card flush"><table><thead><tr><th>Tên đăng nhập</th><th>Họ tên</th><th>Vai trò</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{data.users.filter(u=>JSON.stringify(u).toLowerCase().includes(search.toLowerCase())&&(!kindFilter||u.role===kindFilter)).map(u=><tr key={u.id}><td>{u.username}</td><td>{u.name}</td><td>{labels[u.role]}</td><td><Badge kind={u.active?'green':'gray'}>{u.active?'Hoạt động':'Đã khóa'}</Badge></td><td><button className="text-btn" onClick={()=>edit(u,'user')}>Sửa / Khóa</button></td></tr>)}</tbody></table></section><p className="footnote">Khóa tài khoản thay cho xóa để giữ tên người thực hiện trong lịch sử. Luôn giữ ít nhất một Admin hoạt động.</p></>}
 {page==='audit'&&<>{toolbar(null,false,<select aria-label="Lọc loại nhật ký" value={kindFilter} onChange={e=>setKindFilter(e.target.value)}><option value="">Tất cả nghiệp vụ</option>{[...new Set(data.audit.map(x=>x.entity))].map(k=><option key={k} value={k}>{k}</option>)}</select>)}<section className="card flush"><table><thead><tr><th>Thời gian (UTC)</th><th>Người thực hiện</th><th>Thao tác</th><th>Đối tượng</th><th>Lý do</th><th>Chi tiết</th></tr></thead><tbody>{data.audit.filter(a=>JSON.stringify(a).toLowerCase().includes(search.toLowerCase())&&(!kindFilter||a.entity===kindFilter)).map(a=><tr key={a.id}><td className="nowrap">{a.at}</td><td>{a.actor_name}</td><td><Badge kind="blue">{a.action}</Badge></td><td>{a.entity} #{a.entity_id||'—'}</td><td>{a.reason||'—'}</td><td><button className="text-btn" onClick={()=>show({kind:'audit',title:'Lịch sử #'+a.id},a)}>Xem</button></td></tr>)}</tbody></table></section></>}
 {page==='settings'&&<div className="settings-grid"><section className="card"><div className="card-heading"><h3>Sao lưu và chuyển máy</h3><Badge kind="blue">SQLite cục bộ</Badge></div><p>Tạo bản sao lưu, lưu ra file và mang sang máy mới để khôi phục. Dữ liệu trên các máy chạy riêng biệt.</p><div className="row-actions"><button className="primary" disabled={busy} onClick={()=>action(async()=>{let x=await api('/backup','POST');await refresh();setToast('Đã tạo '+x.file);})}>Tạo sao lưu</button><button onClick={()=>show({kind:'restore',title:'Khôi phục dữ liệu'},{password:''})}>Khôi phục từ file</button></div><div className="backup-list">{data.backups.slice(0,12).map(b=><div key={b.file}><div><strong>{b.file}</strong><small>{Math.round(b.bytes/1024)} KB</small></div><button onClick={()=>action(async()=>{let r=await window.vk.saveBackup(b.file,currentToken);if(!r.canceled)setToast('Đã lưu '+r.file);})}>Lưu file</button></div>)}</div><small>Dữ liệu mặc định: D:\Codex\Projects\VinhKhangThuChiData. Có sao lưu trước mỗi lần mở app, khôi phục và cập nhật.</small></section><section className="card"><div className="card-heading"><h3>Cập nhật phiên bản</h3><Badge kind="blue">V1.0.2</Badge></div><p>App tải và cài phiên bản mới từ kênh phát hành của công ty. Tự sao lưu trước khi cài.</p><label className="field"><span>Kho phát hành GitHub</span><input value={updateUrl} onChange={e=>setUpdateUrl(e.target.value)} placeholder="https://github.com/DoanHuy002/ThuChiVK"/></label><button onClick={()=>action(async()=>setUpdate(await window.vk.updates('configure',currentToken,updateUrl)))}>Lưu kênh cập nhật</button><p className="notice">{update.message || (update.status==='available'?'Có phiên bản mới '+update.version:update.status==='downloading'?'Đang tải '+update.percent+'%':update.status==='checking'?'Đang kiểm tra phiên bản…':'Đã kết nối GitHub ThuChiVK')}</p><div className="row-actions"><button onClick={()=>action(async()=>setUpdate(await window.vk.updates('check',currentToken)))}>Kiểm tra phiên bản</button>{update.status==='available'&&<button className="primary" onClick={()=>action(()=>window.vk.updates('download',currentToken))}>Tải bản mới</button>}{update.status==='downloaded'&&<button className="primary" onClick={()=>action(()=>window.vk.updates('install',currentToken))}>Sao lưu và cài đặt</button>}</div><small>Tự kiểm tra khi mở app và mỗi 4 giờ. Máy chỉ cần có Internet để nhận bản mới.</small></section></div>}
 {page==='import'&&<><div className="notice"><strong>Nhập sổ thu chi Excel trên máy</strong><p>{data.imports.length} dòng chờ đối soát. Chỉ đọc bảng thu chi có cột ngày, diễn giải, thu, chi và tồn; bỏ các bảng phụ không có số dư. Dòng có cả thu và chi cần tách thủ công. Chưa tự phân loại công nợ hoặc đối tác.</p><button className="primary" disabled={busy} onClick={()=>action(async()=>{let r=await window.vk.importExcel(currentToken);if(!r.canceled){setSelected({});setSheet('');await refresh();setToast('Đã đọc '+r.count+' dòng Excel');}})}>Chọn file Excel</button></div>{toolbar(null,false,<><select aria-label="Lọc sheet" value={sheet} onChange={e=>setSheet(e.target.value)}><option value="">Tất cả sheet</option>{[...new Set(data.imports.map(x=>x.sheet))].map(s=><option key={s}>{s}</option>)}</select><button className="primary" disabled={!Object.keys(selected).length||busy} onClick={()=>show({kind:'import',title:'Xác nhận nhập dữ liệu'})}>Nhập {Object.keys(selected).length} dòng đã chọn</button></>)}<section className="card flush"><div className="table-wrap"><table><thead><tr><th>Chọn</th><th>Nguồn</th><th>Ngày</th><th>Nội dung</th><th>Loại</th><th className="right">Số tiền</th><th>Nguồn tiền</th><th>Đối soát</th></tr></thead><tbody>{data.imports.filter(x=>(!sheet||x.sheet===sheet)&&JSON.stringify(x).toLowerCase().includes(search.toLowerCase())).map(x=>{let s=selected[x.id]||x;let blocked=x.imported||x.issues.some(e=>['BOTH_IN_AND_OUT','FORMULA_NO_CACHE','NO_AMOUNT'].includes(e));const patch=(key,value)=>setSelected(v=>({...v,[x.id]:{...s,[key]:value}}));return <tr key={x.id}><td><input aria-label={'Chọn dòng '+x.id} type="checkbox" checked={!!selected[x.id]} disabled={blocked} onChange={e=>setSelected(v=>{let n={...v};if(e.target.checked)n[x.id]={...x,fund_id:''};else delete n[x.id];return n;})}/></td><td><small>{x.sheet}<br/>{x.range}</small></td><td>{selected[x.id]?<input aria-label={'Ngày dòng '+x.id} type="date" value={s.date} onChange={e=>patch('date',e.target.value)}/>:x.date||<span className="negative">Thiếu ngày</span>}</td><td className="desc">{x.description}</td><td>{selected[x.id]?<select aria-label={'Loại dòng '+x.id} value={s.type} onChange={e=>patch('type',e.target.value)}><option value="RECEIPT">Thu</option><option value="EXPENSE">Chi</option></select>:labels[x.type]}</td><td className="right nowrap">{money(x.amount)}</td><td>{selected[x.id]?<select aria-label={'Quỹ dòng '+x.id} value={s.fund_id||''} onChange={e=>patch('fund_id',e.target.value)}><option value="">Chọn quỹ</option>{data.funds.map(f=><option key={f.id} value={f.id}>{fundName(f)}</option>)}</select>:<small>Gợi ý {labels[x.suggestedFund]}</small>}</td><td><Badge kind={x.imported?'green':x.issues.length?'red':'blue'}>{x.imported?'Đã nhập':x.issues.includes('BOTH_IN_AND_OUT')?'Có cả thu và chi':x.issues.length?'Cần kiểm tra':'Chờ đối soát'}</Badge></td></tr>;})}</tbody></table></div></section></>}
 </main><footer className="app-footer"><span>Vĩnh Khang Thu Chi</span><span>Ngày làm việc {today()} · Giữ lịch sử mọi thay đổi</span></footer></div>
 {modal&&<Modal title={modal.title} onClose={()=>!busy&&setModal(null)}>{modal.kind==='audit'?<div><h4>Trước thay đổi</h4><pre>{JSON.stringify(JSON.parse(form.before_json||'null'),null,2)}</pre><h4>Sau thay đổi</h4><pre>{JSON.stringify(JSON.parse(form.after_json||'null'),null,2)}</pre><p>Lý do: {form.reason||'—'}</p></div>:<form onSubmit={submitModal}>{modalFields()}{modalError&&<p className="error" role="alert">{modalError}</p>}<footer><button type="button" disabled={busy} onClick={()=>setModal(null)}>Hủy</button><button className={modal.kind==='delete'?'danger-fill':'primary'} disabled={busy}>{busy?'Đang lưu...':modal.kind==='delete'?'Xác nhận xóa':modal.kind==='restore'?'Chọn file và khôi phục':modal.kind==='import'?'Xác nhận ghi sổ':'Lưu thay đổi'}</button></footer></form>}</Modal>}{recoveryModal()}{toast&&<div className="toast" role="status">{toast}</div>}
 </div>;
}
createRoot(document.getElementById('root')).render(<App/>);
