import React,{useEffect,useState} from 'react';import {fmtDate} from './Dates.jsx';
export default function SalaryHistory({api,obligation,admin,onChanged}){
 const [rows,setRows]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[deleting,setDeleting]=useState(null),[reason,setReason]=useState('');
 const load=async()=>setRows((await api('/clearings')).filter(r=>r.obligation_id===obligation.id));useEffect(()=>{load().catch(e=>setError(e.message));},[obligation.id]);

 useEffect(()=>{const fn=()=>{if(!busy&&!deleting)load().catch(e=>setError(e.message));};window.addEventListener('vk-data-refresh',fn);return()=>window.removeEventListener('vk-data-refresh',fn);});
 async function remove(e){e.preventDefault();setBusy(true);setError('');try{await api('/clearings/'+deleting.id,'DELETE',{version:deleting.version,reason});setDeleting(null);setReason('');await load();await onChanged();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <><h3>Khấu trừ vào lương · {obligation.code}</h3><p>Xóa khoản khấu trừ nhập nhầm sẽ tăng lại ứng lương còn phải trừ, không thay đổi số dư nguồn tiền.</p>{error&&<p className="error">{error}</p>}<table><thead><tr><th>Ngày</th><th>Số tiền</th><th>Bảng lương / ghi chú</th><th>Thao tác</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{fmtDate(r.date)}</td><td>{Number(r.amount).toLocaleString('vi-VN')} đ</td><td>{r.note}</td><td>{admin&&<button className="danger" onClick={()=>setDeleting(r)}>Xóa khấu trừ</button>}</td></tr>)}</tbody></table>{!rows.length&&<p>Chưa có khoản khấu trừ.</p>}{deleting&&<form onSubmit={remove}><label className="field">Lý do xóa<textarea required value={reason} onChange={e=>setReason(e.target.value)}/></label><button type="button" disabled={busy} onClick={()=>setDeleting(null)}>Hủy</button><button className="danger-fill" disabled={busy}>Xác nhận xóa khấu trừ</button></form>}</>;
}
