import React,{useState,useEffect} from 'react';import {fmtDate,fmtTime} from './Dates.jsx';
const money=n=>Number(n||0).toLocaleString('vi-VN')+' đ';
const states={SYNCED:'Đã đồng bộ',CHANGED:'Phiếu kho đã sửa — cần đối chiếu',CANCELLED:'Phiếu kho đã hủy — cần đối chiếu',MISSING:'Phiếu không còn ở kho — cần đối chiếu',PURGED:'Đã xóa hẳn ở Thu Chi'};
export default function Warehouse({api,token,onChanged}){
 const [data,setData]=useState({sources:[],issues:[]}),[documents,setDocuments]=useState([]),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(){setData(await api('/warehouse/status'));setDocuments(await api('/warehouse/documents'));}useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 async function run(fn){setBusy(true);setError('');try{await fn();await load();await onChanged();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section className="card"><h3>Kết nối app Kho</h3><p>Lấy phiếu nhập linh kiện đã ghi sổ để tạo công nợ nhà cung cấp. Không tự tạo phiếu chi; tiền chỉ giảm khi anh ghi thanh toán.</p><button className="primary" disabled={busy} onClick={()=>run(async()=>{const file=await window.vk.pickWarehouse(token);if(file.canceled)return;const connected=await api('/warehouse/connect','POST',{path:file.path});setMessage('Đã kết nối nguồn kho. Bấm Đồng bộ từ kho để ghi công nợ.');})}>Kết nối app Kho</button>{error&&<p className="error" role="alert">{error}</p>}{message&&<p className="notice" role="status">{message}</p>}{data.sources.map(s=><div className="notice" key={s.id}><strong>Đã kết nối</strong><small>{s.path}</small><p>Đồng bộ gần nhất: {s.last_sync?fmtTime(s.last_sync):'Chưa đồng bộ'}</p><button disabled={busy} onClick={()=>run(async()=>{const x=await api('/warehouse/sync','POST',{source:s.id});setMessage(`Đã tạo ${x.created} khoản nợ; ${x.unchanged} phiếu đã có; ${x.issues} phiếu cần đối chiếu; bỏ qua ${x.skipped} phiếu nháp/thiếu nhà cung cấp hoặc giá. Dữ liệu kho cập nhật: ${fmtTime(x.generated_at)}`);})}>Đồng bộ từ kho</button></div>)}<div className="table-wrap"><table><thead><tr><th>Phiếu nhập / ngày</th><th>Nhà cung cấp / linh kiện</th><th>Tổng tiền</th><th>Đối chiếu</th></tr></thead><tbody>{documents.map(d=>{const s=JSON.parse(d.snapshot_json);return <tr key={d.source_id+':'+d.document_id}><td><strong>{s.code||("Phiếu kho #"+d.document_id)}</strong><small>{fmtDate(s.date)}</small></td><td>{s.supplier_name}{s.items?.map((i,n)=><small key={n}>{i.code} · {i.name} · {i.quantity} {i.unit} × {money(i.unit_cost)}</small>)}</td><td>{money(s.amount)}</td><td>{states[d.state]}</td></tr>;})}</tbody></table></div><p className="footnote">Mở app Kho để cập nhật dữ liệu kết nối. Phiếu nháp, phiếu không có nhà cung cấp hoặc chưa có giá sẽ chưa tạo nợ. Phiếu sửa/hủy sau đồng bộ cần đối chiếu khoản nợ và các phiếu thanh toán trước khi chỉnh ở Thu Chi.</p></section>;
}
