const fs=require('fs'),path=require('path'),https=require('https'),crypto=require('crypto'),os=require('os'),{spawn}=require('child_process');
const privateIP=ip=>/^(10\.|192\.168\.|127\.)/.test(ip)||(/^172\.(\d+)\./.test(ip)&&+ip.split('.')[1]>=16&&+ip.split('.')[1]<=31);
function address(value){const u=new URL(value);if(u.protocol!=='https:'||!privateIP(u.hostname)||u.username||u.password||u.pathname!=='/'||u.search||u.hash)throw Error('Chọn địa chỉ IP nội bộ của máy chủ');return u.origin;}
function decode(code,product){try{if(!code.startsWith('VK1.'))throw Error();const c=JSON.parse(Buffer.from(code.slice(4),'base64url'));c.url=address(c.url);if(c.product!==product||! /^[a-f0-9]{64}$/.test(c.key)||! /^[a-f0-9]{64}$/.test(c.fingerprint))throw Error();return c;}catch{throw Error('Mã kết nối không đúng app hoặc không hợp lệ');}}
class Lan {
 constructor({folder,product,version,port,keytool,backend,headers,authorize,maintenance,restart}){Object.assign(this,{folder,product,version,port,keytool,backend,headers,authorize,maintenance,restart});this.file=path.join(folder,'lan-connection.json');this.config=fs.existsSync(this.file)?JSON.parse(fs.readFileSync(this.file,'utf8')):{mode:'local'};if(!['local','host','client'].includes(this.config.mode))throw Error('Cấu hình máy chủ không hợp lệ');if(this.config.mode==='client')decode(this.config.code,product);this.tail=Promise.resolve();}
 get client(){return this.config.mode==='client';}
 async certificate(){fs.mkdirSync(this.folder,{recursive:true});const pfx=path.join(this.folder,'lan-certificate.p12');if(!fs.existsSync(pfx)){const pass=crypto.randomBytes(24).toString('hex');await new Promise((resolve,reject)=>{const p=spawn(this.keytool(),['-genkeypair','-alias','vinhkhang','-keyalg','RSA','-keysize','2048','-validity','3650','-dname','CN=VinhKhang LAN','-storetype','PKCS12','-keystore',pfx,'-storepass:env','VK_CERT_PASSWORD'],{windowsHide:true,env:{...process.env,VK_CERT_PASSWORD:pass},stdio:'ignore'});p.on('error',reject);p.on('exit',c=>c===0?resolve():reject(Error('Không tạo được mã bảo vệ kết nối')));});this.config.pass=pass;this.save();}return {pfx:fs.readFileSync(pfx),passphrase:this.config.pass};}
 save(){fs.mkdirSync(this.folder,{recursive:true});const temp=this.file+'.tmp';fs.writeFileSync(temp,JSON.stringify(this.config,null,2));fs.renameSync(temp,this.file);}
 async start(){if(this.config.mode!=='host')return;this.config.key ||=crypto.randomBytes(32).toString('hex');const cert=await this.certificate();this.server=https.createServer(cert,(req,res)=>this.accept(req,res));this.server.headersTimeout=15000;this.server.requestTimeout=60000;await new Promise((resolve,reject)=>{this.server.once('error',reject);this.server.listen(this.port,'0.0.0.0',resolve)});this.server.on('error',()=>{});this.config.fingerprint=crypto.createHash('sha256').update(this.server._sharedCreds.context.getCertificate()).digest('hex');this.save();}
 status(){const addresses=Object.values(os.networkInterfaces()).flat().filter(x=>x&&x.family==='IPv4'&&!x.internal&&privateIP(x.address)).map(x=>'https://'+x.address+':'+this.port);return {mode:this.config.mode,product:this.product,version:this.version,addresses,connected:this.connected??null,url:this.client?decode(this.config.code,this.product).url:null};}
 async accept(req,res){const fail=(s,m)=>{res.writeHead(s,{'Content-Type':'application/json'});res.end(JSON.stringify({message:m,error:m}));};const ip=(req.socket.remoteAddress||'').replace(/^::ffff:/,'');const key=String(req.headers['x-vk-lan-key']||'');if(!privateIP(ip)||req.headers.origin||! /^[a-f0-9]{64}$/.test(key)||!crypto.timingSafeEqual(Buffer.from(key),Buffer.from(this.config.key)))return fail(403,'Mã kết nối không đúng');if(req.url==='/lan/health'&&req.method==='GET'){res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify({product:this.product,version:this.version}));return;}
 if(req.headers['x-vk-lan-version']!==this.version||req.headers['x-vk-lan-product']!==this.product)return fail(409,'Hai máy cần dùng cùng phiên bản app. Cập nhật rồi thử lại.');
 if(!/^\/api\/[a-zA-Z0-9/_.-]+(?:\?[a-zA-Z0-9%=&,_.-]+)?$/.test(req.url)||!['GET','POST','PUT','DELETE'].includes(req.method))return fail(400,'Yêu cầu không hợp lệ');if((req.method!=='GET'&&/^\/api\/(setup(\/|$)|restore($|\/)|data-reset|reset-transactions)/.test(req.url))||this.product==='thuchi'&&req.url==='/api/auth/register'&&!req.headers.authorization)return fail(403,'Thiết lập và khôi phục dữ liệu thực hiện trên máy chủ');if(this.maintenance())return fail(503,'Máy chủ đang bảo trì, anh thử lại sau');
 let bytes=0,chunks=[];try{for await(const c of req){bytes+=c.length;if(bytes>170*1024*1024){fail(413,'Dữ liệu quá lớn');req.destroy();return;}chunks.push(c);}const operation=async()=>{if(res.destroyed)return;if(this.maintenance()){fail(503,"Máy chủ đang bảo trì, anh thử lại sau");return;}try{const r=await fetch(this.backend()+req.url,{method:req.method,headers:{...this.headers(),...(req.headers.authorization?{Authorization:req.headers.authorization}:{}),...(req.headers['content-type']?{'Content-Type':req.headers['content-type']}:{})},body:bytes?Buffer.concat(chunks):undefined,signal:AbortSignal.timeout(60000)});res.writeHead(r.status,{'Content-Type':r.headers.get('content-type')||'application/json','Cache-Control':'no-store'});for await(const c of r.body){if(res.destroyed)break;res.write(c);}res.end();}catch{if(!res.headersSent)fail(503,'Không kết nối được dịch vụ dữ liệu trên máy chủ');else res.destroy();}};this.tail=this.tail.then(operation,operation);await this.tail;}catch{if(!res.headersSent)fail(400,'Kết nối bị gián đoạn');}}
 async fetch(url,options={}){if(!this.client)return fetch(url,{...options,signal:options.signal||AbortSignal.timeout(60000)});const c=decode(this.config.code,this.product);const route=new URL(url).pathname+new URL(url).search;if(options.body instanceof FormData){const packet=new Request(url,options);options={...options,headers:Object.fromEntries(packet.headers),body:Buffer.from(await packet.arrayBuffer())};}return this.remote(c,route,options);}
 remote(c,route,options={}){return new Promise((resolve,reject)=>{let finished=false;const req=https.request(c.url+route,{method:options.method||'GET',rejectUnauthorized:false,agent:false,headers:{...(options.headers||{}),'X-VK-Lan-Key':c.key,'X-VK-Lan-Version':this.version,'X-VK-Lan-Product':this.product}},res=>{const chunks=[];let n=0;res.on('data',b=>{n+=b.length;if(n>512*1024*1024)req.destroy(Error('Dữ liệu quá lớn'));else chunks.push(b)});res.on('error',reject);res.on('end',()=>{finished=true;this.connected=true;resolve(new Response(Buffer.concat(chunks),{status:res.statusCode,headers:res.headers}));});});req.setTimeout(route.includes('health')||route.includes('setup/status')?5000:60000,()=>req.destroy(Error('Máy chủ không trả lời')));req.on('socket',s=>s.once('secureConnect',()=>{const fingerprint=crypto.createHash('sha256').update(s.getPeerCertificate().raw||Buffer.alloc(0)).digest('hex');if(fingerprint!==c.fingerprint){req.destroy(Error('Mã bảo vệ máy chủ đã thay đổi. Lấy lại mã kết nối từ máy bàn.'));return;}req.end(options.body);}));req.on('error',e=>{if(!finished){this.connected=false;reject(Error(e.message.startsWith('Mã bảo vệ')?e.message:'Không kết nối được máy chủ. Kiểm tra Wi-Fi và mở app trên máy bàn. Thao tác có thể đã được ghi; kiểm tra lại trước khi nhập lại.'));}});});}
 async test(code){const c=decode(code,this.product),r=await this.remote(c,'/lan/health');if(!r.ok)throw Error('Mã kết nối bị từ chối');const h=await r.json();if(h.product!==this.product||h.version!==this.version)throw Error('Hai máy cần dùng cùng phiên bản app. Cập nhật app rồi kết nối lại.');return {ok:true,url:c.url};}
 async handle(b){if(b.action==='status')return this.status();if(b.action==='test')return this.test(b.code);if(b.action==='code'){if(this.config.mode!=='host')throw Error('Máy này chưa bật máy chủ');await this.authorize(b.token);const url=address(b.url);if(!this.status().addresses.includes(url))throw Error('Chọn địa chỉ máy chủ đang hiển thị');return 'VK1.'+Buffer.from(JSON.stringify({url,key:this.config.key,fingerprint:this.config.fingerprint,product:this.product})).toString('base64url');}if(b.action==='configure'){if(!['local','host','client'].includes(b.mode))throw Error('Chế độ không hợp lệ');if(b.mode==='client'){await this.test(b.code);}else if(b.mode==='host'){if(this.client)throw Error('Trở về dữ liệu riêng rồi đăng nhập Admin để bật máy chủ');await this.authorize(b.token);}else if(this.config.mode==='host')await this.authorize(b.token);this.config={...this.config,mode:b.mode,...(b.mode==='client'?{code:b.code}:{})};this.save();this.restart();return {restarting:true};}throw Error('Thao tác không hợp lệ');}
 async idle(){await this.tail;}
 close(){this.server?.close();this.server?.closeAllConnections();}
}
module.exports={Lan,decode,privateIP};
