const {app,BrowserWindow,ipcMain,dialog}=require('electron');
const {spawn}=require('child_process');const fs=require('fs'),path=require('path'),crypto=require('crypto'),net=require('net');
const {autoUpdater}=require('electron-updater');
app.setName('VinhKhangThuChi');
let win,child,base,closing=false,maintenance=false;const secret=crypto.randomBytes(32).toString('hex');
const root=path.join(__dirname,'..');const data=process.env.VK_DATA_DIR||'D:/Codex/Projects/VinhKhangThuChiData';
let state={},active=0,updates,installToken='';
if(fs.existsSync('D:/')||process.env.VK_DATA_DIR){fs.mkdirSync(path.join(data,'profile'),{recursive:true});app.setPath('userData',path.join(data,'profile'));app.setPath('sessionData',path.join(data,'profile'));}
const lock=app.requestSingleInstanceLock();if(!lock)app.quit();
app.on('second-instance',()=>{win?.show();win?.focus();});
function checkSender(e){if(!win||e.sender.id!==win.webContents.id)throw Error('Không được cho phép');}
async function api(route,method='GET',body,token='') {
 if(maintenance)throw Error('App đang chuẩn bị cập nhật');
 if(!/^\/api\/[a-z0-9/-]+(?:\?from=\d{4}-\d{2}-\d{2}&to=\d{4}-\d{2}-\d{2})?$/.test(route)||!['GET','POST','PUT','DELETE'].includes(method))throw Error('Yêu cầu không hợp lệ');
 active++;try{const r=await fetch(base+route,{method,headers:{'Content-Type':'application/json','X-VK-Bridge':secret,Authorization:'Bearer '+token},body:body==null?undefined:JSON.stringify(body)});const b=await r.json();if(!r.ok)throw Error(b.error||'Không thực hiện được');return b;}finally{active--;}
}
async function authorize(token){let u=await api('/api/auth/me','GET',null,token);if(u.role!=='ADMIN')throw Error('Chỉ Admin được thực hiện');return u;}
function notify(s){state=s;if(win&&!win.isDestroyed())win.webContents.send('update-state',s);}
function port(){return new Promise((res,rej)=>{let s=net.createServer();s.on('error',rej);s.listen(0,'127.0.0.1',()=>{let p=s.address().port;s.close(()=>res(p));});});}
async function boot(){
 if(!fs.existsSync('D:/')&&!process.env.VK_DATA_DIR)throw Error('Không có ổ D. Chưa chọn nơi lưu dữ liệu.');
 fs.mkdirSync(data,{recursive:true});app.setPath('userData',path.join(data,'profile'));fs.mkdirSync(app.getPath('userData'),{recursive:true});
 let p=await port();base='http://127.0.0.1:'+p;
 const java=app.isPackaged?path.join(process.resourcesPath,'runtime/bin/java.exe'):path.join(root,'runtime/bin/java.exe');
 const jar=app.isPackaged?path.join(process.resourcesPath,'backend.jar'):path.join(root,'backend/target/thuchi-1.1.3.jar');
 let log=fs.openSync(path.join(data,'backend.log'),'a');
 fs.mkdirSync(path.join(data,'sockets'),{recursive:true});child=spawn(java,['-Djdk.net.unixdomain.tmpdir='+path.join(data,'sockets'),'-jar',jar],{windowsHide:true,env:{...process.env,VK_DATA_DIR:data,VK_PORT:String(p),VK_BRIDGE_SECRET:secret,VK_DESKTOP:'true'},stdio:['pipe',log,log]});fs.closeSync(log);
 let err;child.on('error',e=>err=e);
 for(let i=0;i<120;i++){if(err||child.exitCode!==null)break;try{let h=await api('/api/health');if(h.status==='UP')return;}catch{}await new Promise(r=>setTimeout(r,250));}
 throw Error('Không khởi động được dịch vụ dữ liệu. Xem backend.log trong thư mục dữ liệu.');
}
async function stop(force=true){if(!child||child.exitCode!==null)return;await new Promise((resolve,reject)=>{let t=setTimeout(()=>{if(force){child.kill();resolve();}else reject(Error("Chưa đóng được dịch vụ dữ liệu"));},8000);child.once('exit',()=>{clearTimeout(t);resolve();});child.stdin.end();});}
ipcMain.handle('api',(e,b)=>{checkSender(e);return api(b.route,b.method,b.body,b.token);});
ipcMain.handle('export-csv',async(e,{name,text})=>{checkSender(e);if(typeof text!=='string'||text.length>10000000)throw Error('Báo cáo quá lớn');if(!fs.existsSync('D:/'))throw Error('Không có ổ D');fs.mkdirSync('D:/Codex/Downloads',{recursive:true});let p=await dialog.showSaveDialog(win,{title:'Xuất báo cáo',defaultPath:path.join('D:/Codex/Downloads',path.basename(name)),filters:[{name:'CSV',extensions:['csv']}]});if(p.canceled)return {canceled:true};fs.writeFileSync(p.filePath,'\ufeff'+text,'utf8');return {file:p.filePath};});
ipcMain.handle('save-backup',async(e,{name,token})=>{checkSender(e);await authorize(token);if(!/^thuchi-[0-9]+-[a-f0-9]{6}\.sqlite$/.test(name))throw Error('Tên không hợp lệ');if(!fs.existsSync('D:/'))throw Error('Không có ổ D');fs.mkdirSync('D:/Codex/Downloads',{recursive:true});let p=await dialog.showSaveDialog(win,{title:'Lưu bản sao để chuyển máy',defaultPath:path.join('D:/Codex/Downloads',name),filters:[{name:'Vĩnh Khang Backup',extensions:['sqlite']}]});if(p.canceled)return {canceled:true};let r=await fetch(base+'/api/backups/'+name,{headers:{'X-VK-Bridge':secret,Authorization:'Bearer '+token}});if(!r.ok)throw Error('Không đọc được bản sao lưu');fs.writeFileSync(p.filePath,Buffer.from(await r.arrayBuffer()));return {file:p.filePath};});
ipcMain.handle('restore',async(e,{password,token})=>{checkSender(e);await authorize(token);let p=await dialog.showOpenDialog(win,{title:'Chọn bản sao lưu Thu Chi Vĩnh Khang',defaultPath:'D:/Codex/Downloads',properties:['openFile'],filters:[{name:'Vĩnh Khang Backup',extensions:['sqlite']}]});if(p.canceled)return {canceled:true};let file=p.filePaths[0];if(fs.statSync(file).size>512*1024*1024)throw Error('Bản sao lưu quá 512 MB');let form=new FormData();form.append('file',new Blob([fs.readFileSync(file)]),'backup.sqlite');form.append('password',password);let r=await fetch(base+'/api/restore',{method:'POST',headers:{'X-VK-Bridge':secret,Authorization:'Bearer '+token},body:form});let b=await r.json();if(!r.ok)throw Error(b.error||'Không khôi phục được');return b;});
ipcMain.handle('import-excel',async(e,{token})=>{checkSender(e);await authorize(token);let p=await dialog.showOpenDialog(win,{title:'Chọn sổ thu chi Excel',defaultPath:'D:/Codex/Downloads',properties:['openFile'],filters:[{name:'Excel',extensions:['xlsx']}]});if(p.canceled)return {canceled:true};let file=p.filePaths[0];if(fs.statSync(file).size>10*1024*1024)throw Error('File Excel quá 10 MB');let form=new FormData();form.append('file',new Blob([fs.readFileSync(file)]),path.basename(file));active++;try{if(maintenance)throw Error('App đang chuẩn bị cập nhật');let r=await fetch(base+'/api/import/upload',{method:'POST',headers:{'X-VK-Bridge':secret,Authorization:'Bearer '+token},body:form});let b=await r.json();if(!r.ok)throw Error(b.error||'Không đọc được Excel');return b;}finally{active--;}});
ipcMain.handle('updates',async(e,{action,token,url})=>{checkSender(e);if(action==='status')return updates.snapshot();if(action==='configure')return updates.save({token,url});if(action==='check')return updates.check(token);if(action==='download')return updates.download(token);if(action==='install'){installToken=token;return updates.install(token);}throw Error('Thao tác không hợp lệ');});
function runWarehouseTool(java,args){return new Promise((resolve,reject)=>{let output='';const p=spawn(java,args,{windowsHide:true,stdio:['ignore','pipe','pipe']});p.stdout.on('data',b=>output+=b);p.stderr.on('data',b=>output+=b);let timeout=setTimeout(()=>{p.kill();reject(Error('Kết nối Kho quá thời gian. Đóng app Kho rồi thử lại.'));},30000);p.once('error',e=>{clearTimeout(timeout);reject(e);});p.once('exit',code=>{clearTimeout(timeout);if(code===0)resolve();else reject(Error('Chưa bật được kết nối. Đóng app Kho và chọn đúng thư mục dữ liệu rồi thử lại.'));});});}
ipcMain.handle('pick-warehouse',async(e,{token})=>{checkSender(e);await authorize(token);const guesses=['D:/Codex/Projects/vinhkhang_QLK/data/finance-sync.json',path.join(app.getPath('appData'),'VinhKhangWarehouse/data/finance-sync.json')];let defaultPath=guesses.find(p=>fs.existsSync(p))||'D:/Codex/Projects';let p=await dialog.showOpenDialog(win,{title:'Chọn dữ liệu Kho; hoặc chọn app Kho để bật kết nối lần đầu',defaultPath,properties:['openFile'],filters:[{name:'Dữ liệu kết nối / App Kho',extensions:['json','exe']}]});if(p.canceled)return {canceled:true};const file=p.filePaths[0];if(path.extname(file).toLowerCase()==='.json')return {path:file};const warehouseJar=path.join(path.dirname(file),'resources/backend.jar');if(!fs.existsSync(warehouseJar))throw Error('Chọn file mở app Kho đã cài.');const folder=await dialog.showOpenDialog(win,{title:'Chọn thư mục dữ liệu app Kho (có warehouse.mv.db)',defaultPath:path.join(app.getPath('appData'),'VinhKhangWarehouse/data'),properties:['openDirectory']});if(folder.canceled)return {canceled:true};const dir=folder.filePaths[0];if(!fs.existsSync(path.join(dir,'warehouse.mv.db')))throw Error('Thư mục chưa có dữ liệu app Kho.');const java=app.isPackaged?path.join(process.resourcesPath,'runtime/bin/java.exe'):path.join(root,'runtime/bin/java.exe');const jar=app.isPackaged?path.join(process.resourcesPath,'backend.jar'):path.join(root,'backend/target/thuchi-1.1.3.jar');await runWarehouseTool(java,['-jar',jar,'--enable-warehouse',warehouseJar]);await runWarehouseTool(java,['-Dloader.main=vn.vinhkhang.warehouse.FinanceSnapshot','-cp',warehouseJar,'org.springframework.boot.loader.launch.PropertiesLauncher',dir]);const snapshot=path.join(dir,'finance-sync.json');if(!fs.existsSync(snapshot))throw Error('Chưa tạo được kết nối. Đóng app Kho và thử lại.');return {path:snapshot};});
const evidencePicks=new Map();
function prunePicks(){for(const [k,v] of evidencePicks)if(v.at<Date.now()-15*60*1000)evidencePicks.delete(k);}
ipcMain.handle('pick-evidence',async(e,{token})=>{checkSender(e);await authorize(token);prunePicks();const p=await dialog.showOpenDialog(win,{title:'Chọn ảnh / PDF bằng chứng',defaultPath:'D:/Codex/Downloads',properties:['openFile','multiSelections'],filters:[{name:'Ảnh / PDF',extensions:['png','jpg','jpeg','pdf']}]});if(p.canceled)return [];if(p.filePaths.length>20)throw Error('Chọn tối đa 20 file');const picked=[];let total=[...evidencePicks.values()].reduce((s,v)=>s+v.bytes.length,0);for(const file of p.filePaths){if(fs.statSync(file).size>8*1024*1024)throw Error('Mỗi file tối đa 8 MB');const bytes=fs.readFileSync(file);total+=bytes.length;if(total>128*1024*1024)throw Error('Quá nhiều file đang chờ tải. Lưu chứng từ trước khi chọn thêm.');picked.push({key:crypto.randomUUID(),bytes,name:path.basename(file),mime:path.extname(file).toLowerCase()==='.pdf'?'application/pdf':path.extname(file).toLowerCase()==='.png'?'image/png':'image/jpeg',token,at:Date.now()});}for(const v of picked)evidencePicks.set(v.key,v);return picked.map(v=>({key:v.key,name:v.name,mime:v.mime,bytes:v.bytes.length}));});
ipcMain.handle('upload-evidence',async(e,{entity,id,key,caption,token})=>{checkSender(e);await authorize(token);prunePicks();const v=evidencePicks.get(key);if(!v||v.token!==token)throw Error('File chờ đã hết hạn, hãy chọn lại');if(!['vouchers','obligations'].includes(entity)||!Number.isSafeInteger(Number(id)))throw Error('Chứng từ không hợp lệ');if(maintenance)throw Error('App đang cập nhật');active++;try{const f=new FormData();f.append('file',new Blob([v.bytes],{type:v.mime}),v.name);f.append('caption',String(caption||''));const r=await fetch(base+'/api/evidence/'+entity+'/'+id,{method:'POST',headers:{'X-VK-Bridge':secret,Authorization:'Bearer '+token},body:f});const b=await r.json();if(!r.ok)throw Error(b.error||'Không lưu được bằng chứng');evidencePicks.delete(key);return b;}finally{active--;}});
ipcMain.handle('discard-evidence',(e,{keys,token})=>{checkSender(e);for(const k of (keys||[])){if(evidencePicks.get(k)?.token===token)evidencePicks.delete(k);}return true;});
ipcMain.handle('download-evidence',async(e,{id,token})=>{checkSender(e);await api('/api/auth/me','GET',null,token);const b=await api('/api/evidence/file/'+Number(id),'GET',null,token);if(!fs.existsSync('D:/'))throw Error('Không có ổ D');fs.mkdirSync('D:/Codex/Downloads',{recursive:true});const p=await dialog.showSaveDialog(win,{title:'Lưu bằng chứng',defaultPath:path.join('D:/Codex/Downloads',path.basename(b.name)),filters:[{name:'Bằng chứng',extensions:[b.mime==='application/pdf'?'pdf':b.mime==='image/png'?'png':'jpg']}]});if(p.canceled)return {canceled:true};fs.writeFileSync(p.filePath,Buffer.from(b.base64,'base64'));return {file:p.filePath};});

function setupUpdates(){const {UpdateManager}=require('./updates.cjs');updates=new UpdateManager({updater:autoUpdater,version:app.getVersion(),packaged:app.isPackaged,dataDir:data,defaults:{url:'https://github.com/DoanHuy002/ThuChiVK'},authorize,notify,prepareInstall:async()=>{await api('/api/backup','POST',null,installToken);maintenance=true;try{for(let i=0;active>0&&i<100;i++)await new Promise(r=>setTimeout(r,100));if(active)throw Error('Còn thao tác chưa hoàn tất');await stop(false);}catch(e){maintenance=false;throw e;}}});}
if(lock)app.whenReady().then(async()=>{try{await boot();setupUpdates();win=new BrowserWindow({width:1450,height:940,minWidth:1050,minHeight:700,title:'Thu Chi Vĩnh Khang',icon:path.join(__dirname,'logo.ico'),show:process.env.VK_TEST_HIDDEN!=='true',webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true,backgroundThrottling:process.env.VK_TEST_HIDDEN!=='true'}});win.webContents.setWindowOpenHandler(()=>({action:'deny'}));win.webContents.on('will-navigate',(e,url)=>{if(url!==win.webContents.getURL())e.preventDefault();});await win.loadFile(path.join(root,'dist/index.html'));if(app.isPackaged){const check=()=>updates.check(null,true).catch(()=>{});setTimeout(check,5000).unref();setInterval(check,4*60*60*1000).unref();}child.on('exit',()=>{if(!closing&&!maintenance)dialog.showErrorBox('Dịch vụ dữ liệu đã dừng','Đóng app và mở lại trước khi tiếp tục ghi phiếu.');});}catch(e){dialog.showErrorBox('Không mở được app',e.message);await stop();closing=true;app.quit();}});
app.on('window-all-closed',()=>app.quit());
app.on('before-quit',e=>{if(!closing&&child?.exitCode===null){e.preventDefault();closing=true;stop().finally(()=>app.quit());}});
